### ISSUE TITLE
[BUG] --filename does not take effect - Still uses default setting

### ISSUE THREAD

**Issue by Thonolanj** [anidl/multi-downloader-nx#122]
** Main info: **

Script version:  4.12.4
Show ID: any
Episode ID: any
Command used:node funi.js -p 9 -s 124389 -e 89 --filename '${title} - S${season}E${episode}'

** Additional Info: **
this results in a file named. 
[Funimation] My Hero Academia - 89 [1080p].mkv

I have tried this with the Windows .exe version, the Node js version in Windows. and the Linux Node Js version in Ubuntu 20.04
all three act the same way. 

No matter which show I try it keeps using the Default filename string.

**Comment by Evoley** [comment]
I can actually confirm that this is true. This is my command and it's still using the default string

./aniDL --service funi --username  --password   -s 34200 --e 0001 --dubLang jpn eng --dlsubs all -q 10 --mp4 --mks --partsize 60 --fileName ${showTitle} ${season} ${episode} ${title}

**Comment by bgette** [comment]
--fileName "${showTitle} ${season} ${episode} ${title}" try with that

**Comment by Evoley** [comment]
> --fileName "${showTitle} ${season} ${episode} ${title}" try with that

That just gets saved as a noname file.

**Comment by Evoley** [comment]
Managed to fix it. --fileName '${showTitle} ${season} ${episode} ${title}' is the correct way to do it.
