### ISSUE TITLE
[ISSUE] cannot find module

### ISSUE THREAD

**Issue by iidankmoo** [anidl/multi-downloader-nx#131]
Command: node funi.js
C:\Users\Admin\Downloads\funimation-downloader-nx-5.0.0-win64>node funi.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\Admin\Downloads\funimation-downloader-nx-5.0.0-win64\funi.js'
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

**Comment by DragonVsKira** [comment]
what the code r u running...... just use "funi your code " your using the .exe u do not need "node funi.js"

**Comment by izu-co** [comment]
@iidankmoo Please follow the BUG template

**Comment by izu-co** [comment]
Since we merged both downloaders, your issue may be invalid. Please check and reopen if this issue persists.
