### ISSUE TITLE
[BUG] [Funimation/Crunchy] Error: Cannot find module

### ISSUE THREAD

**Issue by malzen** [anidl/multi-downloader-nx#136]
command does is not working. node funi.js --auth o node funi --auth does work for me

C:\Users\Shangaran\Desktop\Anime 2021\multi-downloader-nx-1.0.0-win64\multi-downloader-nx-1.0.0-win64>node funi --auth
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\Shangaran\Desktop\Anime 2021\multi-downloader-nx-1.0.0-win64\multi-downloader-nx-1.0.0-win64\funi.js'
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

C:\Users\Shangaran\Desktop\Anime 2021\multi-downloader-nx-1.0.0-win64\multi-downloader-nx-1.0.0-win64>

**Comment by izu-co** [comment]
It seams like you are using the exe version.
In that case use aniDl.exe instead of node funi

**Comment by StabbedYa** [comment]
mine is the same but im not exe I don't even know where to get the exe

**Comment by malzen** [comment]
When I open aniDl.exe it closes immediately.

**Comment by StabbedYa** [comment]
you dont open the exe by clicking on it you use it in commands just replace the node funi.js with the exe versions. example here...
funi.exe --auth
(or even this)
funi --auth

**Comment by StabbedYa** [comment]
the instructions are not very clear the other thing I found out the instructions don't tell you is that they changed the location of where ffmpeg and mkvmerge has to be you can see it in 
.\config\bin-path.yml 
ffmpeg: "./bin/ffmpeg/ffmpeg.exe"
mkvmerge: "./bin/mkvtoolnix/mkvmerge.exe"

So make sure that matches up because you probley will have the same issue as I did

**Comment by malzen** [comment]
Thank you for helping me

**Comment by malzen** [comment]
When I typed funi.exe --auth this comes up with 'funi' is not recognized as an internal or external command,
operable program or batch file.

**Comment by malzen** [comment]
What about for get Show ID, Download Video, Muxing and Proxy. 

As I don't know how to do these.

**Comment by izu-co** [comment]
Use `--help` instead of `--auth` to get a list of possible options

**Comment by malzen** [comment]
The command you gave me for auth does work. I am asking for the other commands.

**Comment by izu-co** [comment]
What did not work. Give me the console output

**Comment by malzen** [comment]
I meant this code aniDL.exe --service 'funi' --auth does work.

**Comment by malzen** [comment]
What are the command for these since I am using aniDL.exe.
--search <s> 
Download Video
-s <i> -e <s> 
-q <i>
--all 
--alt 
--subLang 
--allSubs 
--dub 
--allDubs 
--simul 
-x, --server select server
--novids 
--nosubs 
--noaudio 

Muxing
--mp4 
--mks

**Comment by malzen** [comment]
aniDL.exe -f 'funi' --search deep insanity the lost child
aniDL.exe -s 1007443 -q 10 --nosubs -e 1-12"
(sub)
aniDL.exe -s titleidnumber -q 0 --sub -e 1-12

**Comment by izu-co** [comment]
It muxes by default as long as you have the path set. 

And if you want to download subs use `--subLang`

**Comment by malzen** [comment]
What are the correct command for these please:
aniDL.exe -f 'funi' --search deep insanity the lost child
aniDL.exe -s 1007443 -q 10 --nosubs -e 1-12"
(sub)
aniDL.exe -s titleidnumber -q 0 --sub -e 1-12

**Comment by izu-co** [comment]
I am not going to explain the whole tool to you, sorry, but I don't have the time. Either another community member finds the time or you use the `--help` command,

**Comment by malzen** [comment]
I figured it out now

**Comment by malzen** [comment]
[ERROR] Track not selected

**Comment by izu-co** [comment]
Ok I will say it one last time. 
You can give me the console log and I can try to help you or I can't do nothing

**Comment by malzen** [comment]
aniDL.exe --service 'funi' --search deep insanity the lost child
aniDL.exe --service 'funi' -s 2831743 -q 0 --subenUS -e 4 --dub jaJP

Both of these codes work. I just tested this out.
