### ISSUE TITLE
[CLI] <-- allDubs -- allSubs>

### ISSUE THREAD

**Issue by drknss89** [anidl/multi-downloader-nx#141]
** Main info: -- allDubs only downloading Eng and -- allSubs not downloading any subs**

Script version: 1.0.0
Service: -- allDubs  -- allSubs
What do you want to do: want to be able to download all dubs and subs with said commands

** Additional Info: **
anidl.exe --service "funi" - s 1007443 - e 1 - q 0 -- allDubs --allSubs

Not sure if this could be the issue but Eng audio is 1007443 while Jap audio is 1008381

**Comment by izu-co** [comment]
@drknss89 Where do you get the language ids from? Funimation doesn’t have those.
Can you give me the console output?

**Comment by izu-co** [comment]
Should be fixed with the newest release

**Comment by drknss89** [comment]
I will give it a try when I get home, sorry I couldn't get you the output, had to work

**Comment by drknss89** [comment]
@izu-co it works, thank you so much, this is an amazing project and it's great to have, I can get my animes onto my media server without having to wait for someone else to do it first, ty ty ty

**Comment by izu-co** [comment]
Glad you like it
