### ISSUE TITLE
[BUG] [Funimation/Crunchy] Can't find FFmpeg & MKVmerge

### ISSUE THREAD

**Issue by DinoVikingo** [anidl/multi-downloader-nx#145]
** Main info: **

Script version: 1.01
Service: Funimation
Show ID: 1019573
Episode ID:  0001
Command used: aniDL.exe --service 'funi' -s 1019573 -q 0 --sub esLA -e 1 --dub jaJP
Console output: 
![image](https://user-images.githubusercontent.com/89960654/140568939-02344b18-dcac-457f-a939-c7baead28e68.png)

Hi, programm doesn't find/use the video tools even when i have them in the right bin place and only downloads English subtitles D:

**Comment by izu-co** [comment]
Can you give me the `bin.yml` file as well as an image that contains the path to and the tools.

**Comment by DinoVikingo** [comment]
Wait... the bin isn't a folder? D:

**Comment by DinoVikingo** [comment]
![image](https://user-images.githubusercontent.com/89960654/140569584-cb570005-057f-4ba8-afb5-afb29dfa6b46.png)

**Comment by izu-co** [comment]
What I mean is the bin file in config

**Comment by DinoVikingo** [comment]
It doesn't let me upload the YML file, ill put it as a zi
[bin-path.zip](https://github.com/anidl/multi-downloader-nx/files/7488565/bin-path.zip)
p

**Comment by izu-co** [comment]
Try setting it to 
```
ffmpeg: ".\\bin\\ffmpeg\\ffmpeg.exe"
mkvmerge: ".\\bin\\mkvtoolnix\\mkvmerge.exe"
```

If that doesn't work, I have to dig deeper.

**Comment by DinoVikingo** [comment]
It worked!
Now it's just an .MKV file :D
But subtitles are still on english :,D

**Comment by izu-co** [comment]
For Funimation you have to use `--subLang`

**Comment by DinoVikingo** [comment]
Oh, sorry. 😅
Well, now is everything okey! :D
I am very grateful, if you have a donations page or paetron or so i'll support :D

**Comment by izu-co** [comment]
No I don't have any of those.
I am a student, so I live at the expense of my parents. That's why there is no need to pay bills or something like that.

Enjoy the downloader and feel free to open up another issue any time.

**Comment by izu-co** [comment]
Just wanted to add that my answer can take some time because of school.
