### ISSUE TITLE
SUBS

### ISSUE THREAD

**Issue by xslaayer29** [anidl/multi-downloader-nx#147]
Main info: I need help with the subs since I used a command that worked before with some series, but now it does not work with any and I do not know which one indicated the correct one **

Script version: 
Service: 
What do you want to do: I want to download only the subtitles in esLA

** Additional Info: **
this is the command i use:
node funi.js -s 19373 -q 10 --novids --subLang esLA --noaudio -e 0001

**Comment by DinoVikingo** [comment]
Hi!
I wanna know if there's a way to change the subtitle font.
I think that the KG Love Somebody have a better look.
(it's a manga type font)

**Comment by izu-co** [comment]
@xslaayer29 It seams like you are using an outdated version?
@DinoVikingo changekng the font for funi or crunchy?

**Comment by DinoVikingo** [comment]
> @xslaayer29 It seams like you are using an outdated version? @DinoVikingo changekng the font for funi or crunchy?

For funi, it's not that important if there's  no way to change the font tho.

**Comment by DinoVikingo** [comment]
> Main info: I need help with the subs since I used a command that worked before with some series, but now it does not work with any and I do not know which one indicated the correct one **
> 
> Script version: Service: What do you want to do: I want to download only the subtitles in esLA
> 
> ** Additional Info: ** this is the command i use: node funi.js -s 19373 -q 10 --novids --subLang esLA --noaudio -e 0001

Bro, try using:
`aniDL.exe --service 'funi' -s 2831743 -q 0 --subLang esLA -e 1 --dub jaJP --novids --noaudio`
or in your case:
`node funi.js -s 2831743 -q 0 --subLang esLA -e 1 --dub jaJP --novids --noaudio`

**Comment by izu-co** [comment]
@DinoVikingo Implemented it just for you in the newest release

**Comment by kanohn** [comment]
Hello,

Could someone tell me what the proper command to download only subtitles? thanks!

**Comment by xslaayer29** [comment]
> > Main info: I need help with the subs since I used a command that worked before with some series, but now it does not work with any and I do not know which one indicated the correct one **
> > Script version: Service: What do you want to do: I want to download only the subtitles in esLA
> > ** Additional Info: ** this is the command i use: node funi.js -s 19373 -q 10 --novids --subLang esLA --noaudio -e 0001
> 
> Bro, try using: `aniDL.exe --service 'funi' -s 2831743 -q 0 --subLang esLA -e 1 --dub jaJP --novids --noaudio` or in your case: `node funi.js -s 2831743 -q 0 --subLang esLA -e 1 --dub jaJP --novids --noaudio`

Thank you so much
