### ISSUE TITLE
[BUG] [Funimation/Crunchy] If download only subtitle, that sub is not sync with video

### ISSUE THREAD

**Issue by kanohn** [anidl/multi-downloader-nx#148]
Hello,

I have downloaded sometimes with the program, and in my tests:

1 - If i download the video full like:
aniDL.exe --service 'funi' -s 541361 -q 7 --subLang ptBR -e 1 --dub jaJP

Subs are OK.

If i download only subs:
aniDL.exe --service 'funi' -s 541361 -q 7 --subLang ptBR --all --dub jaJP --novids --noaudio

The subs get downloaded, however its not synchronization with the video..

**Comment by kanohn** [comment]
I have looking more into this bug, and i saw that when i hit the command:
aniDL.exe --service 'funi' -s 541361 -q 7 --subLang ptBR --all --dub jaJP --novids --noaudio

at the firsts downloads it download the correctly syncs subs, however after the program finish the downloads, these files get modified.

**Comment by kanohn** [comment]
I found the bug, was the --all parameter.

If i download with:
aniDL.exe --service 'funi' -s 541361 --subLang ptBR --dub jaJP -e 1,2,3,4 --novids --noaudio

the subs get downloaded correctly.

**Comment by kanohn** [comment]
Sorry saying again, but i found other issue:

aniDL.exe --service 'funi' -s 541361 --subLang ptBR --dub jaJP -e 4 --novids --noaudio

EP 4 on funimation have ptBR language, however it's only download english, just for this episode, very weird.

**Comment by izu-co** [comment]
It can't be caused by the `--all` tho...

**Comment by kanohn** [comment]
Yes, its not by the all command, however some shows have subs on PtBR that the program download only english... could you look into this?
https://www.funimation.com/shows/irina-the-vampire-cosmonaut/?qid=

this anime its a example, that have two episodes that the program download only in english, and they have all subs in PtBR.

**Comment by izu-co** [comment]
I recently looked into a similar issue. You may have to use the simulcast version instead.
