### ISSUE TITLE
[feature request] add --download-archive

### ISSUE THREAD

**Issue by erickyun** [anidl/multi-downloader-nx#149]
Could you add yt-dlp --download-archive feature?
Feature to look in archive for Episode İD and skip already downloaded İD. Like an auto download command.

**Comment by izu-co** [comment]
Already though about it, but it's a crap ton of work. 

Might do in the future, so I will let it open.

**Comment by erickyun** [comment]
> Already though about it, but it's a crap ton of work.
> 
> Might do in the future, so I will let it open.

Ok thank you.

maybe it is related with topic but could you add an option to show download speed?
also does it use ffmpeg to download video?

**Comment by izu-co** [comment]
Working on it!

**Comment by izu-co** [comment]
This has been implemented in the newest release!

@OryWareKyrie  @erickyun, Since you are both active, let me know if it works for you and if you find any bugs.

If you have any troubles, please open up an issue for CLI or bugs.

**Comment by erickyun** [comment]
> This has been implemented in the newest release!
> 
> @OryWareKyrie @erickyun, Since you are both active, let me know if it works for you and if you find any bugs.
> 
> If you have any troubles, please open up an issue for CLI or bugs.

Thank you I did just try and it works fine. 👍 

But I have question does it also archive Episode ID's ?

**Comment by izu-co** [comment]
It works only on -s and --series

**Comment by erickyun** [comment]
> It works only on -s and --series

Any plans to -e too?

**Comment by izu-co** [comment]
Not just yet.
