### ISSUE TITLE
[issue] Slow download speed?

### ISSUE THREAD

**Issue by erickyun** [anidl/multi-downloader-nx#151]
Does it use ffmpeg to download video?
Cuz I know from ytdlp it downloads slow with ffmpeg. 
With aria2 mine download will take 2-3 minutes to finish with ffmpeg it would take 12-13 minutes to finish.
Would it not better to use aria2c to bypass download speed limit?

**Comment by izu-co** [comment]
No it downloads the raw streams, decrypts them and adds them to the file.
It should be as fast as possible.

**Comment by erickyun** [comment]
> No it downloads the raw streams, decrypts them and adds them to the file. It should be as fast as possible.

I did just download latest word trigger Episode with ytdlp and it took 2 minutes to finish but with anidl.exe it did take 13 minutes?

**Comment by izu-co** [comment]
Can you use `ffprobe -i "File"` to send me the metadata of the downloaded file?

**Comment by erickyun** [comment]
> Can you use `ffprobe -i "File"` to send me the metadata of the downloaded file?

This one is downloaded with [ytdlp](https://pastebin.com/raw/4ExghJ2f) and this is downloaded with [anidl.exe](https://pastebin.com/raw/HUd5vN1P)

**Comment by izu-co** [comment]
Alright, I see your issue. I can tell that you have a good connection speed, so could you try to raise the batch size by doing `--partsize number`. 10 is default. Try playing with it and test if that fixes anything.

**Comment by erickyun** [comment]
yes that did fix it.
I thank you for your help.
I'm closing it.

**Comment by izu-co** [comment]
Don't mention it. Feel free to open up an issue if you think you found something, so we can improve!
