### ISSUE TITLE
[CLI] 403:FORBIDDEN

### ISSUE THREAD

**Issue by DinoVikingo** [anidl/multi-downloader-nx#152]
** Main info: **

Script version: 1.0.3
Service: funi

I'm trying to get the Overlord series but it says "403: Forbidden" but i can watch the anime in the funi website.
Maybe i'm putting the command wrong?

![image](https://user-images.githubusercontent.com/89960654/140620043-8a67085b-0401-4f23-b2db-b2d48cc8fdef.png)

I'm using `aniDL.exe --service 'funi' -s 103522 -q 0 --subLang esLA -e 1 --dub jaJP`

**Comment by izu-co** [comment]
Hey there. Thanks for reporting this.

It seems like it was flagged as mature content. If that has an impact on the downloader, IDK, but I will investigate.

**Comment by DinoVikingo** [comment]
> Hey there. Thanks for reporting this.
> 
> It seems like it was flagged as mature content. If that has an impact on the downloader, IDK, but I will investigate.

Oh, yeah. it has C label.
It's interesting, i'll keep caution :D (idk if that's a correct sentence XD)

**Comment by DinoVikingo** [comment]
> Hey there. Thanks for reporting this.
> 
> It seems like it was flagged as mature content. If that has an impact on the downloader, IDK, but I will investigate.

Broooo
It's fully a web issue.

To avoid that error you have to get off the "Hide mature content" on your account preferences.

![image](https://user-images.githubusercontent.com/89960654/140620509-748412bd-4b31-4f0d-b4ea-c2d577c69bca.png)

I uncheked that options and now can download it.
(I didn't know about the existence of the option but it's good to know)

**Comment by izu-co** [comment]
Just wanted to report that I didn't find anything.
After logging in, the error, disappeared once I logged in.

So I was about to tell you to check your settings.

Don't worry and don't be afraid to open up a new issue once you encounter a problem.
