### ISSUE TITLE
[BUG] [Funimation/Crunchy] episode released but does not appear in the list

### ISSUE THREAD

**Issue by kanohn** [anidl/multi-downloader-nx#153]
The episode 3 of The Vampire Dies in No Time have released on ptBR, i watched on funimation, but i can't download it on the downloader.. it's saying that only have japanese:

aniDL.exe --service 'funi' -s 2657893 -q 7 --nosubs -e 3 --dub ptBR

Have some delay to the program get the episode available for the language?

**Comment by izu-co** [comment]
Please check that you are accessing from the right point in the world.

It showed up for me.

**Comment by kanohn** [comment]
https://i.postimg.cc/GpRRB0Lr/123.png
Still not showing ep 3 ptbr for me.. but its available on the site..

i'm accessing in Brazil.

**Comment by Kambura147** [comment]
I'm having the exact same problem.

I've tried both with the dub option released today and the 6th episode, also released today.

**Comment by malzen** [comment]
Same issue as well does not show the latest episode only previous episodes.

**Comment by Mytic-Slander** [comment]
Here is also the same problem, the audio does not appear in Portuguese and the recently released episode does not appear the new episode. Episode 6 came out but only shows up to episode 5

**Comment by izu-co** [comment]
Alright I will investigate it later. If I still don’t have the issue myself, I might need some of you to run some debiting code.

**Comment by Mytic-Slander** [comment]
> Tudo bem, vou investigar isso mais tarde. Se eu ainda não tiver o problema, talvez precise de alguns de vocês para executar algum código de débito.

Ok, thanks ;)

**Comment by STRATOS99K** [comment]
> Alright I will investigate it later. If I still don’t have the issue myself, I might need some of you to run some debiting code.

The api url is not getting updates anymore https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/2657893, I'll attach a log, I guess you could check this https://d33et77evd9bgg.cloudfront.net/data/v2/shows/the-vampire-dies-in-no-time.json
Command aniDL.exe --service 'funi' -s 2657893 -e 6 -q 0
[Log.txt](https://github.com/anidl/multi-downloader-nx/files/7506031/Log.txt)

**Comment by izu-co** [comment]
@STRATOS99K Can you quickly update me on where you are getting the information from?

Although I think you might be right.

**Comment by STRATOS99K** [comment]
> @STRATOS99K Can you quickly update me on where you are getting the information from?
> 
> Although I think you might be right.

I was just checking with and addon Netmon for now, I can PM you in discord

**Comment by izu-co** [comment]
Sure

**Comment by malzen** [comment]
Any update on this issue

**Comment by STRATOS99K** [comment]
> Any update on this issue

Izu-co is looking into the issue, you should have no problems downloading eps at this moment

**Comment by izu-co** [comment]
I haven't found any issue recently. I will assume that it was a mistake on funis side and close this issue.

If it persists, please open up a new issue.
