### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by JuanF007** [anidl/multi-downloader-nx#154]
I have problems executing

![image](https://user-images.githubusercontent.com/43446222/140793262-b441c03e-fdeb-46b0-97c7-0f28ae0c2d02.png)

**Comment by izu-co** [comment]
You have to give the argument `--service` like it sais below.

**Comment by Mytic-Slander** [comment]
> You have to give the argument `--service` like it sais below.

How to use this now? before I used this to authenticate: node funi --auth. But now its not work, I'm opening the command in the "lib" folder is it correct?

**Comment by Mytic-Slander** [comment]
Using this command " node funi --auth" show this message: Missing required argument: service

How do i work?

**Comment by izu-co** [comment]
Do `node index.js —service 'funi' —auth`

**Comment by Mytic-Slander** [comment]
> Do `node index.js —service 'funi' —auth`

Thanks, its work
