### ISSUE TITLE
 Mux Subs in video

### ISSUE THREAD

**Issue by Kstilho** [anidl/multi-downloader-nx#157]
Hello thanks for the work, i have the following "problem". Where I run the download of the videos is not pulling the subtitle in pt br, I downloaded these subtitles on another machine is there the option to make the mux when placing these subtitles inside the folder? I tried with the flag --mks but it only pulls the English subtitles.

![image](https://user-images.githubusercontent.com/93347339/140973975-fea4c6f2-31a7-4276-b75d-d7210d863a5f.png)

comand - ./funi -s 1072618 -e 1 --fileName '${showTitle}/[GuedesFlix] ${showTitle} - ${season}E${episode} - ${title} [${height}p]'  --nocleanup -q0 --mks

**Comment by izu-co** [comment]
`funi.js` is discontinued. Please use the newest release and use `node index.js --service 'funi'`
