### ISSUE TITLE
[feature-request] allow multiple dub selection (instead of all dubs)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [anidl/multi-downloader-nx#158]
I like to dual audio most of my anime, but using --alldubs would also DL Russian, Spanish, Portuguese etc if available...

I would also like this to be made available for Crunchyroll as well? any way how since each show language uses its own separate show ID. maybe with crunchy provide the show id's as well with the dub flag? while with funi just list the languages like eng, jpn

lately, I've been doing manual audio extraction & remixing...

**Comment by izu-co** [comment]
I talked about this earlier, but for crunchy it's hard to add multi dub per file since it is separated into different groups.

**Comment by izu-co** [comment]
Proud to announce that I am working on this.

**Comment by izu-co** [comment]
Please try something like `node .\index.js --service 'crunchy' --srz GVDHX8DM5 -e 1 --dubLang eng jpn -q 1`.

You can insert any general show ID 
```
  [Z:GVDHX8DM5] 86 EIGHTY-SIX (Seasons: 6, EPs: 74) [SIMULCAST, SUB, DUB] <----- This one
  [S:G65VCD2NN] 86 EIGHTY-SIX (Portuguese Dub) (Season: 1) [SIMULCAST, DUB]
  [S:GYGGCVM52] 86 EIGHTY-SIX (German Dub) (Season: 1) [SIMULCAST, DUB]
  [S:G6Q4CZD0N] 86 EIGHTY-SIX (Spanish Dub) (Season: 1) [SIMULCAST, DUB]
  [S:GYWEC39M3] 86 EIGHTY-SIX (French Dub) (Season: 1) [SIMULCAST, DUB]
  [S:GR09CX3WM] 86 EIGHTY-SIX (English Dub) (Season: 1) [SIMULCAST, DUB]
  [S:GR09CXQJ5] 86 EIGHTY-SIX (Season: 2) [SIMULCAST, SUB]
```

If you find problems, please report it back :)
