### ISSUE TITLE
[BUG] [Funimation/Crunchy] < Problem downloading Episode 1>

### ISSUE THREAD

**Issue by JuanF007** [anidl/multi-downloader-nx#160]
I'm trying to download Episode 1 of the Assassination Classroom anime
but I get an error when downloading
Instead when you download Episode 2, if you download it
The problem is chapter 1

Command used:
anidl.exe --service funi -s 19373 -e 1 -q 10 --dub esLA

![image](https://user-images.githubusercontent.com/43446222/141130937-40004883-8e2a-4360-99f5-f537cc728c80.png)

**Comment by STRATOS99K** [comment]
![Screenshot 2021-11-11 123450](https://user-images.githubusercontent.com/72719473/141365523-ac777e8b-ccb6-4110-9bbf-68ea3964bb96.png)
Maybe it was an issue with funi, I had no problems with the same command
