### ISSUE TITLE
[feature request] Use MediaID to download

### ISSUE THREAD

**Issue by kiriasan** [anidl/multi-downloader-nx#161]
could you add an option so we can download an episode using media id
it was working very well in crunchyroll nx i hope you can add it to multi nx too <3

**Comment by kiriasan** [comment]
Will you add this feature?

**Comment by izu-co** [comment]
Don't know yet. Depending on my time

**Comment by izu-co** [comment]
Someday for sure tho

**Comment by izu-co** [comment]
This is already possible? Just use `-e`. If that is not what you want, please explain further.

**Comment by kiriasan** [comment]
example from crunchyroll downloader nx:
node crunchy -s 25728 -e m816145 or node crunchy -e m816145
I hope you understand me
![Capture](https://user-images.githubusercontent.com/93961338/143667202-1c321ef4-7059-4e0b-a671-07c5f31126b3.PNG)

**Comment by bgette** [comment]
is it already possible...

**Comment by bgette** [comment]
It's already possible...

**Comment by kiriasan** [comment]
it doesn't work for me
which command do you used?

**Comment by izu-co** [comment]
The command you used is incorrect.

This program now uses beta API only, therefor show ID must contain `9` characters. 
If think you are using an old, outdated version.

Please use the right show id and try again.

**Comment by izu-co** [comment]
@kiriasan 
I now know what you mean, and it is implemented in the [newest release](https://github.com/anidl/multi-downloader-nx/releases/tag/2.0.5)

**Comment by BraveSail** [comment]
what the correct command now? 
eg: direct download from http://www.crunchyroll.com/dropkick-on-my-devil/episode-3-the-deadly-party-whistle-852541

**Comment by izu-co** [comment]
No new questions will be answered on old threads. Please open up a new issue.
