### ISSUE TITLE
dumb but maybe important commands? QOL 

### ISSUE THREAD

**Issue by Jotinator** [anidl/multi-downloader-nx#163]
Hi thnx you for this app!,

- In both funi and crunchy is there a command to change  the MS time from this?

"ERROR: Timeout awaiting 'request' for 60000ms"

I think reducing it could help alot when a part is missing and instead of wainting 1 min for retryng it could be faster.

- There is a equivalent for "--partsize X" for the crunchy app?

The one in funi works verywell but crunchy does not recognize it and it use 5 as default.

thnx you, J.

**Comment by izu-co** [comment]
Yes there is if I remember correctly its `--timeout`. But see `--help` for that.
