### ISSUE TITLE
[BUG] [Funimation] <Does not download dubbing Selected>

### ISSUE THREAD

**Issue by JuanF007** [anidl/multi-downloader-nx#164]
I am trying to download only the audio from the anime "Assassination Classroom"
but I get the following message

**[INFO] Unable to locate a video AND audio file**

The command line used is the following
anidl.exe --service "funi" -s 19373 -e 1 -q 0 --novids --dub esLA

Am I using the Command correctly or am I making a mistake?

![image](https://user-images.githubusercontent.com/43446222/142281548-021685ed-8444-4e90-bc01-c1d353266d57.png)

**Comment by izu-co** [comment]
I thinks it’s because this show does not separate audio and video.
They are both in one file - if you skip the video you skip the audio as well.

Going to check later tho, closing it for now
