### ISSUE TITLE
[CLI] <Short description here>i can't download and it said [ERROR] HTTPError 403: FORBIDDEN

### ISSUE THREAD

**Issue by rayanve** [anidl/multi-downloader-nx#168]
** Main info: **

Script version: 
Service: 
What do you want to do: 
![Administrator_ C__Windows_System32_cmd exe 11_19_2021 4_23_39 PM](https://user-images.githubusercontent.com/94682144/142611534-75248ed4-f32e-4f09-a192-390678c95160.png)

** Additional Info: **

**Comment by izu-co** [comment]
Please give me the command you used.

**Comment by izu-co** [comment]
Closed due to lack of information
