### ISSUE TITLE
[BUG] [Funimation/Crunchy] About skipmux only subtitle

### ISSUE THREAD

**Issue by kanohn** [anidl/multi-downloader-nx#172]
Hello,

i'm sorry if i'm posting on wrong place, i didn't find where i can request something.

The point is, could we skipmux only the subtitle, i saw that have --skipmux but it only skip mux everything..

I think somepeople like to mix the videos and leave the subtitle separated...

thank you in advance, i hope that feature be added <3

**Comment by izu-co** [comment]
Implemented in the newest release
