### ISSUE TITLE
[Suggestion] ScaledBorderAndShadow: yes

### ISSUE THREAD

**Issue by narutojawad** [anidl/multi-downloader-nx#177]
Greetings,

Subs downloaded from services like crunchyroll comes with ScaledBorderAndShadow off by default, however if we compare it to the ones that are on the site they look a bit different. So if possible to add an option to add "ScaledBorderAndShadow: yes" line to subs before muxing them to the video will be nice.

Regards,

**Comment by izu-co** [comment]
Hey there no need to be so formal.

The `.ass` subtitles already have the line `ScaledBorderAndShadow: yes`

**Comment by narutojawad** [comment]
Hey, 
Thanks for your efforts. :)

**Comment by izu-co** [comment]
It was added in the newest release.
