### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by DragonVsKira** [anidl/multi-downloader-nx#178]
the option to addArchive then download the anime just add it to addArchive or the option to addArchive then download if u can ....y my power trun off something i do have backup power 4 my pc but not for my network i ben using this 

```
@echo off
set /p D=What The Anime key Number?

 "C:\funidownloader-nx\multi-downloader-nx-win64\aniDL.exe"    --service 'funi' -s "%D%" --addArchive
timeout 5


 "C:\funidownloader-nx\multi-downloader-nx-win64\aniDL.exe"    --service 'funi' --downloadArchive    --all -q "0" --partsize  "50" --mkv --mks   --fileName  "${showTitle}\\season ${season}\\${showTitle} - S${season}E${episode} - ${title} - [${height}p] [FuniDub]
timeout 30
```

it will make it easyer for me if u can't it all good just asking 

maybe a options in "cli-defaults.yml" addArchive then download =false or  true

**Comment by izu-co** [comment]
So you want to both add and download? 
I don’t think that this is a command worth adding tho. If you just want to download the whole anime use —but. The downloaded episodes will be saved anyway

**Comment by DragonVsKira** [comment]
was just asking all good because youtube-dl.exe does something like that may i ask if u can add the anime name to the Archive.json ? to make it easy to read if not i can just look up the anime id ps thanks u 4 all your hard work

**Comment by izu-co** [comment]
Adding the anime is not possible since the id is used to get down the path - very sorry tho.

**Comment by DragonVsKira** [comment]
This is my last question Is there a way to make it check to see if you haven’t already added the anime to the archive file because you can add double I did by accident and had to redo it because I broke the archive file by accident after you reply I will close this

**Comment by izu-co** [comment]
Leave it open. It should check against doubles and I will add that. 
And yes, I am grateful for your suggestions. Just don't be discouraged or disappointed if I can't do them.

**Comment by izu-co** [comment]
Added with the newest commit
