### ISSUE TITLE
Missing font for Subtitle

### ISSUE THREAD

**Issue by erickyun** [anidl/multi-downloader-nx#180]
Player: [mpv 0.34.0-89-gf08db00d26](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20211128-git-f08db00.7z/download)

`This without arialbd.ttf`
![mpv-shot0001](https://user-images.githubusercontent.com/71968711/144705711-7469368b-9e5c-4bf8-8e1c-d25d120bfd46.jpg)

`This with arialbd.ttf`
![mpv-shot0003](https://user-images.githubusercontent.com/71968711/144705713-bc68edba-3d87-4f0b-af2f-3de3eaca4bbb.jpg)

[arialbd.zip](https://github.com/anidl/multi-downloader-nx/files/7653733/arialbd.zip)

EDİT:

This is the Attachments that multi-dl mux for the subtitle: arial.ttf / trebuc.ttf / times.ttf / cour.ttf / AdobeArabic-Bold.otf

These are the Attachments that is needed for the subtitle: `arialbd.ttf / arialbi.ttf / Arial_0.ttf / ariblk_0.TTF / calibri.ttf / comicbd.ttf / comic_0.ttf / georgiab.ttf / georgiaz.ttf / georgia_0.ttf / impact_0.ttf / Tahoma_0.ttf / times_0.ttf / trebuc_0.ttf / verdana_0.ttf / AdobeArabic-Bold.otf / AdobeArabic-BoldItalic.otf / AdobeArabic-Italic.otf / AdobeArabic-Regular.otf`

could you add the missing fonts as attachment too? 👍 
[attachments.zip](https://github.com/anidl/multi-downloader-nx/files/7659702/attachments.zip)

**Comment by izu-co** [comment]
Have you tryed `--dlfonts?`

**Comment by izu-co** [comment]
And another side note, where did you get the font list from?

**Comment by erickyun** [comment]
> And another side note, where did you get the font list from?

I got the fonts from **erai-raws** 

> Have you tryed `--dlfonts?`

I did try `--dlfonts` it does download the fonts but some fonts are missing when I use `--dlfonts`  like `calibri.ttf, AdobeArabic-BoldItalic.otf, AdobeArabic-Italic.otf, AdobeArabic-Regular.otf`

also multi-dl won't include the fonts I listed above as attachments
it only includes `arial.ttf / trebuc.ttf / times.ttf / cour.ttf / AdobeArabic-Bold.otf`
 and

**Comment by izu-co** [comment]
We will (finally) be working on a way to fix this issue. 
Some fonts you mention are not from crunchyroll e.g. `calibri.ttf` and therefor won't be supported.

As far as adding the zip goes, since we don't own the copyright to the fonts, we can't add them.

PS: I don't know where erai got the fonts from, but we won't add stuff because they have them. We only support the fonts used by crunchyroll.

**Comment by izu-co** [comment]
Fixed
