### ISSUE TITLE
[BUG] [Funimation/Crunchy] dlsubs "en" option missing causing Invalid Argument errors

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [anidl/multi-downloader-nx#181]
** Main info: **

Script version: Multi Downloader NX 2.0.7 Commit: 667f02fae25db3dd10454e3901562bfe8b62289e
Service: Funi & Crunchy (Argument Belongs to Crunchy, triggers on any service though due to config file)
Show ID: N/A
Episode ID: N/A
Command used: aniDL --service crunchy --dlsubs en  

Console output: 
```text
Invalid values:
  Argument: dlsubs, Given: "en", Choices: "all", "none", "es-419", "es", "pt-BR", "fr", "de", "ar", "it", "ru", "tr", "ja", "zh"
```

** Additional Info: **
![Screen Shot 2021-12-08 at 6 04 28 am](https://user-images.githubusercontent.com/2242880/145090685-42dd4dcf-9784-44a7-abd4-2e096fc1f614.jpg)
![Screen Shot 2021-12-08 at 6 04 37 am](https://user-images.githubusercontent.com/2242880/145090697-5d5c53d2-7f21-4fba-a8fc-d569c07e7b91.jpg)

What happened to "en" English support for subs?

I started getting this error after some recent updates. this initially triggered because I always had this in my config
![Screen Shot 2021-12-08 at 6 08 13 am](https://user-images.githubusercontent.com/2242880/145090956-d3f382ab-b6fd-4f89-85aa-a219caadaa09.jpg)

**Comment by XxUnkn0wnxX** [comment]
also, no streams are being detected for any shows on Funimation...

`aniDL --service funi -s 2831743 -e 9`
`aniDL --service funi -s 1311428 -e 21`

Show ID: 2831743, EP 9 (Deep Insanity: The Lost Child)
Show ID: 1311428, EP 21 (Mushoku Tensei: Jobless Reincarnation)
![Screen Shot 2021-12-08 at 6 32 18 am](https://user-images.githubusercontent.com/2242880/145094323-6118e6e3-8f8f-485a-b48a-612308d28f43.jpg)

![Screen Shot 2021-12-08 at 6 31 51 am](https://user-images.githubusercontent.com/2242880/145094340-f265775d-1f99-4f61-87dc-5c68b54bcd70.jpg)

Says track not selected... & its not showing any available streams.

**Comment by izu-co** [comment]
Alright so...
 As you might have noticed, I have merged the command line arguments for subs and dubs for both funi and crunchy into one per category. Track not selected just means that you haven't selected the Japanese audio. Please refer to the help for the new options for subs and dubs.
 
 As to where the en sub went - idfk I will take a look into it tomorrow

**Comment by XxUnkn0wnxX** [comment]
I see `dubLanguage` which used to be crunchy config only is affect funi, shower this is not shown in funi help page..

**Comment by izu-co** [comment]
Should be tho...

**Comment by XxUnkn0wnxX** [comment]
ya i saw its in help page...

to DL subs only now such a long command though `aniDL --service funi -s 2831743 -e 9 --dubLang jpn --novids --noaudio --dlsubs all` "all" still works just cant specify "en" for English only :(

**Comment by izu-co** [comment]
I plan to auto create the CLI defaults file when the programm is build

**Comment by izu-co** [comment]
For now, the newest commit is fixing the English problem

**Comment by XxUnkn0wnxX** [comment]
@izu-co as of commit: c89cea218c3fe00b64429b6ab17d85e57bf745f0 this is broken again
i have `dlSubs: en` set in config, i tried to set "none" "jp" etc and within the script, it just doesn't recognise it, it keeps saying the default is all even though its not 

![Screen Shot 2022-01-07 at 2 54 16 am](https://user-images.githubusercontent.com/2242880/148411089-5e5e5497-15ee-4125-9779-e883d78683bf.jpg)

**Comment by izu-co** [comment]
Will look into it

**Comment by izu-co** [comment]
I just looked into it @XxUnkn0wnxX, and I've changed `dlSubs` to `dlsubs`. Since the newest update, all config option are `exactly` the same as if you would pass it to args. So since it would be `--dlsubs` it is also now `dlsubs: [number]` in the config.

As for the missing partsize, this has been added with 05d65d3d540b6c439184676598f77c817e0bc62f.
