### ISSUE TITLE
[ERROR] Track not selected

### ISSUE THREAD

**Issue by IzukuDeku01** [anidl/multi-downloader-nx#184]
Suddenly getting this Dunno why.

aniDL --service "funi" -s 519865 -e 138 --mks --subLang --partsize 120 this is the command I gave and got this 

[INFO] Selected Episodes: 0138

[INFO] Black Clover - S3E138 - In Zara's Footsteps
[INFO] Available streams (Non-Encrypted):
[#1453159] English [Uncut]
[#1191546] English [Simulcast]
[ERROR] Track not selected

I also tried with aniDL --service "funi" -s 519865 -e 138 -q 0 --mks --subLang --partsize 120 --simul but same error
Am I doing anything wrong or missing out on any command !!! :/

**Comment by izu-co** [comment]
Which version are you using? 
In recent changes, the default language was set to Japanese. You might want to change that to English by using `--dubLang`

**Comment by IzukuDeku01** [comment]
> Which version are you using? In recent changes, the default language was set to Japanese. You might want to change that to English by using `--dubLang`

using the latest and --dubLang eng worked. Thanks :3

**Comment by izu-co** [comment]
I would recommend you read the patch notes as well. All changes are noted there :)
