### ISSUE TITLE
[BUG] [Funimation/Crunchy] This is a issue for both services not able to download in the latest version. 

### ISSUE THREAD

**Issue by malzen** [anidl/multi-downloader-nx#185]
[INFO] Output filename: [Funimation] Deep Insanity THE LOST CHILD - S01E08 [1080p].ts
[INFO] Saving stream to «C:\Program Files\multi-downloader-nx-2.0.9-win64\videos\[Funimation] Deep Insanity THE LOST CHILD - S01E08 [1080p].video.ts»...
[INFO] 10 of 713 parts downloaded [1%] (2m02s | 9.3Mb/s)
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: EPERM: operation not permitted, open 'C:\Program Files\multi-downloader-nx-2.0.9-win64\videos\[Funimation] Deep Insanity THE LOST CHILD - S01E08 [1080p].video.ts'
    at Object.openSync (node:fs:585:3)
    at Object.openSync (pkg/prelude/bootstrap.js:739:32)
    at Object.writeFileSync (node:fs:2153:35)
    at hlsDownload.download (C:\snapshot\multi-downloader-nx\node_modules\hls-download\src\hls-download.js:201:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4048,
  syscall: 'open',
  code: 'EPERM',
  path: 'C:\\Program Files\\multi-downloader-nx-2.0.9-win64\\videos\\[Funimation] Deep Insanity THE LOST CHILD - S01E08 [1080p].video.ts'
}

This is the issue I am having on v2.0.9.

**Comment by malzen** [comment]
![alt text](https://i.imgur.com/EZKXjGB.png)

**Comment by izu-co** [comment]
It seams to me that you don’t have permission to edit the Programm files.
To do so you need to elevate the shell with administrative permission.
I would otherwise recommend putting the tool on your desktop or so

**Comment by malzen** [comment]
It works when I run cmd as admin is this fine.
