### ISSUE TITLE
[Request] [Funimation/Crunchy] Add queue list with download links

### ISSUE THREAD

**Issue by kanohn** [anidl/multi-downloader-nx#186]
Hi

It will be very good to put a queue list with all submited download links that will start automatically after the last is done..

Should this feature be possible to be implemented?

**Comment by izu-co** [comment]
You can already put anime you want in a list and download new episodes later?

**Comment by kanohn** [comment]
Its more a feature to leave it download automatically while we are away from pc/sleeping.. this will save a lot of time..

with some flag on the command that add to queue, after download an episode, the next on the queue will get downloaded automatically..

**Comment by izu-co** [comment]
I think it would be best for you to make a `.bat` or `.sh` file for that.

**Comment by kanohn** [comment]
Thanks, it works.
