### ISSUE TITLE
Feature to download last epoisde of show without need to specify its number

### ISSUE THREAD

**Issue by MEGZ99** [anidl/multi-downloader-nx#188]
as title 
want feature to download the last episode without need to specify the number 
say like 
-e last

**Comment by izu-co** [comment]
There is currently no framework for implementing something like this. Please use the auto downloader in order to download only the latest episodes.

**Comment by MEGZ99** [comment]
@izu-co 
what it the auto downloader 
there is no commond like that in help
aniDL.exe --service "crunchy" -s GYVNC2VPW -e 2 -q 5 --dlsubs ar --skipSubMux --fileName "Kimetsu no Yaiba - S${season}E${episode} [${height}p]"

what should I add to this code
