### ISSUE TITLE
Malformed Style on Subtitles

### ISSUE THREAD

**Issue by real89mx2** [anidl/multi-downloader-nx#202]
I tried to edit some of the subs downloaded from funimation and this massage appear on aegisub 
![err](https://user-images.githubusercontent.com/58614964/147391484-605cabc3-744d-43af-ac58-e2b997e47528.PNG)
I opened it in notepad and noticed that there is a missing value in the line to create the Style: MainTop
![err2](https://user-images.githubusercontent.com/58614964/147391582-b586a6c7-6411-428e-963c-099d955e8c92.PNG)
Any chance to fix that on your next release?

Thanks.

**Comment by izu-co** [comment]
Please open an issue using the given template.

**Comment by izu-co** [comment]
I've added it, and it will be included in the next release.

This is an exception: Please stick to the issue template next time, since I usually need the extra information the template requests.
