### ISSUE TITLE
enhancement - Download Audio

### ISSUE THREAD

**Issue by JuanF007** [anidl/multi-downloader-nx#205]
![Proyecto sin título](https://user-images.githubusercontent.com/43446222/147689023-f5df1510-bd51-467f-a364-c09878ba7500.gif)

**Comment by sl1pkn07** [comment]
TS is only a container. inside have the audio stream (already in AAC format)

ffmpeg only demux it

![Screenshot_20211229_205517](https://user-images.githubusercontent.com/462213/147698760-009d0580-3ae4-47bc-a729-0df2dd3cfb68.png)

**Comment by izu-co** [comment]
That’s correct. The audio is already acc.
