### ISSUE TITLE
FFmpeg and MKVMerge not found

### ISSUE THREAD

**Issue by BuckMisterFullerene** [anidl/multi-downloader-nx#207]
The error shows up unless bin-path.yml is configured from:

> ffmpeg: "ffmpeg.exe"
> mkvmerge: "mkvmerge.exe"

to:

> FFmpeg: "ffmpeg.exe"
> MKVMerge: "mkvmerge.exe"

**Comment by izu-co** [comment]
Unable to confirm. Please reopen using the bug template to give me all needed information
