### ISSUE TITLE
add downloader - aria2c

### ISSUE THREAD

**Issue by cfandora** [anidl/multi-downloader-nx#210]
Thanks for your working!
Could you please add downloader aria2c?

**Comment by izu-co** [comment]
What do you mean adding by adding `aria2c`? `aria2c` is a library like `youtubedl` to download from known sources?
Also, what advantage do you think we are getting from adding it?

**Comment by cfandora** [comment]
aria2 is a pro downloader. wW could get faster speed from it. Also, when the network is not good, we could use aria2c to continuou broken downloading. In short, aria2 is very worthy to use.

You can know more about it from here:
[https://aria2.github.io](https://aria2.github.io)

**Comment by izu-co** [comment]
The speed cannot get faster. We request the parts directly from funimation/crunchy decrypt them ourselves and adding them to the download file. You can increase the amount of simultaneous downloads by using the `--partsize` option. 

Interrupted downloads can be continued, we already provide this feature. 
It makes no sense for us to implement aria2 therefor the proposal is rejected.
