### ISSUE TITLE
Add support for "search-type" as a config option?

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [anidl/multi-downloader-nx#211]
was thinking I could set  `search-type: series` in config however it doesn't get detected..

can you make that any flags that have multiple choices able to be set in the config file? like anything that reads a "default" should be able set in config
![Screen Shot 2022-01-09 at 8 02 56 am](https://user-images.githubusercontent.com/2242880/148659997-02f1e72f-7ac7-49b2-9e07-365f7ee2a753.jpg)

![Screen Shot 2022-01-09 at 8 02 51 am](https://user-images.githubusercontent.com/2242880/148659998-53354555-f50e-4a82-96b8-5ba841a64522.jpg)

**Comment by izu-co** [comment]
I added support for this in 1b001438d94dd264833fcbf22ca23ade5b91f4fa.
In 32b10e7ba1e63323dc8e3d79ba402490d834c986 you can set every option in the cli-default that has a default value.
