### ISSUE TITLE
Crunchyroll New EP not listed, old script lists it?

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [anidl/multi-downloader-nx#212]
This is starting to become more frequent with new shows/episodes 

when using multi downloader to find an episode that was released within the last 2-3 hours it never shows, however, the old Crunchyroll script "Crunchyroll Downloader NX 5.3.2" shows them?
<img width="2384" alt="new EP not showing" src="https://user-images.githubusercontent.com/2242880/148665516-8e6187bc-34f6-4920-a465-6f2d714a395b.png">

In this above case: Show 86 Eighty Six, MultiDL ID: GR09CX3WM. Old Script ID: 25678
& I am using a premium account.

**Comment by izu-co** [comment]
Please remember that these are two different APIs.
Maybe they are fed different information from Crunchyroll? I can't tell, but I can't do very much about it since these endpoints work (just not as fast or something, again idk).

**Comment by XxUnkn0wnxX** [comment]
then would it be possible to incorporate the other API as a different --search flag `--search-legacy` or something?
Legacy API support?

**Comment by izu-co** [comment]
It _would_ be possible but a **lot** of work.
And seeing that I have school starting tomorrow and my own personal Projekt growing in complexity it's not likely I have time for that.
