### ISSUE TITLE
EBUSY

### ISSUE THREAD

**Issue by luannbr** [anidl/multi-downloader-nx#213]
Why does it happen?
There's no way, when that happens, he restarts the episode again?
![Screenshot_1235](https://user-images.githubusercontent.com/18580842/148670431-7727c4ba-fc3e-496f-a709-32582a095197.jpg)

**Comment by CMoranO** [comment]
Sometimes it happens to me, try to disable windows defender real-time protection.

**Comment by starm7md** [comment]
**
![image](https://user-images.githubusercontent.com/65809932/148682492-12c10815-7359-4bc9-bd62-888ae921e4fc.png)
**

why this happens when i want to login using this command 

node funi.js --auth

**Comment by izu-co** [comment]
@starm7md Please open up a new issue instead of commenting on others.

@luannbr It seems like you are either:
 - Missing permission for the folder
 - Something other than the tool (e.g. an antivirus) is using the file at the time of downloading

**Comment by luannbr** [comment]
Hi! I don't use antivirus, my windows defender is disabled 80% of the time.
I don't think it's folder permission

I'll try to leave windows defend disabled longer

**Comment by starm7md** [comment]
> Hi! I don't use antivirus, my windows defender is disabled 80% of the time. I don't think it's folder permission
> 
> I'll try to leave windows defend disabled longer

i disabled windows defender but still same error

**Comment by izu-co** [comment]
@luannbr Has it been working for you?

**Comment by luannbr** [comment]
> 

I disabled Windows Defender, apparently it stopped showing up on EBUSY, but I need to do more testing, I'm going to download some big anime just to be sure

**Comment by izu-co** [comment]
Idk what is using the file, but something is.

**Comment by izu-co** [comment]
@luannbr Were you able to resolve the issue, or do you still have this problem?

**Comment by luannbr** [comment]
i'm still having this problem.
What I'm thinking it could be, is Funimation/Crunchyroll "cutting the connection" and this is happening.

**Comment by izu-co** [comment]
I don’t think so. If it does the part get reloaded.
Can you take a look at [this](https://github.com/anidl/multi-downloader-nx/issues/223#issuecomment-1013941029) it seems to have helped another user with the same issue.

**Comment by izu-co** [comment]
Please see the newest release. I've added an option where the downloader will now retry 3 times if an error during the writing process occurs (hopefully enough time for whatever process used to file to get the f** out).
You can increase the time the downloader waits between each attempt by using a command (please see the documentation).

**Comment by luannbr** [comment]
I will download the latest version and test.
I will also try to test the post you quoted

**Comment by luannbr** [comment]
@izu-co I downloaded an anime here 4x had no problems with EBUSY, it was possibly solved in this last update
