### ISSUE TITLE
login error 

### ISSUE THREAD

**Issue by starm7md** [anidl/multi-downloader-nx#215]
### Program version

2.0.15

### Service

Funimation

### Command used

node funi.js --auth

### Show ID

1

### Episode

1

### Console Output

![image](https://user-images.githubusercontent.com/65809932/148694294-1a1ef2cf-62ae-4f38-b001-bee30e8f6535.png)

i can't login to funimation by this command node funi.js --auth , it displays this error 

can anyone help me please

**Comment by izu-co** [comment]
Please send me a screenshot of the folder. If you are using the download option from [here](https://github.com/anidl/multi-downloader-nx/releases/tag/2.0.15) please use `.\anidl.exe` instead of `node funi.js`

**Comment by starm7md** [comment]
> Please send me a screenshot of the folder. If you are using the download option from [here](https://github.com/anidl/multi-downloader-nx/releases/tag/2.0.15) please use `.\anidl.exe` instead of `node funi.js`

![image](https://user-images.githubusercontent.com/65809932/148696065-6e2f9517-ed76-46f8-974e-dac3fc3c2c7c.png)

![image](https://user-images.githubusercontent.com/65809932/148696081-f9fb5ea0-3f35-4e77-990f-3f7f2d9c82b2.png)


can you please tell me how i can just login and download the episodes , what commands i should use because i'm very newbie

**Comment by izu-co** [comment]
use `.\aniDL.exe --service funi --auth`

**Comment by starm7md** [comment]
> `.\aniDL.exe`

thanks a lot now it works , could you please tell me what command i should use to download episodes ?

**Comment by starm7md** [comment]
> > `.\aniDL.exe`
> 
> thanks a lot now it works , could you please tell me what command i should use to download episodes ?

i figured it out , thank u anyway
