### ISSUE TITLE
MKVMerge is not working 

### ISSUE THREAD

**Issue by starm7md** [anidl/multi-downloader-nx#216]
### Program version

2.0.15

### Service

Funimation

### Command used

.\aniDL.exe --service funi -s 2637753 -e 2 -q 1 --simul --dubLang eng

### Show ID

2637753 

### Episode

2

### Console Output

![image](https://user-images.githubusercontent.com/65809932/148794820-0e022d3c-9d2c-4a22-8f73-b55d23a600f2.png)
![image](https://user-images.githubusercontent.com/65809932/148794848-c198ad78-9c45-4aeb-9494-63e3fe824bdd.png)
![image](https://user-images.githubusercontent.com/65809932/148794928-2f142021-bab3-4b0b-bd06-140f513440fc.png)

can anyone tell me why MKVMerge is not working please , i assume it is an installation problem , but i can't figure it out . can anyone help me please 

.\aniDL.exe --service funi -s 2637753 -e 2 -q 1 --simul --dubLang eng

**Comment by luannbr** [comment]
In config/bin-path.yml 

change 

FFmpeg: "ffmpeg.exe"
MKVMerge: "mkvmerge.exe"

to

FFmpeg: "./bin/ffmpeg/ffmpeg.exe"
MKVMerge: "./bin/mkvtoolnix/mkvmerge.exe"
https://prnt.sc/26c4v09

**Comment by starm7md** [comment]
> In config/bin-path.yml
> 
> change
> 
> FFmpeg: "ffmpeg.exe" MKVMerge: "mkvmerge.exe"
> 
> to
> 
> FFmpeg: "./bin/ffmpeg/ffmpeg.exe" MKVMerge: "./bin/mkvtoolnix/mkvmerge.exe" https://prnt.sc/26c4v09

thanks a lot now it works <3
