### ISSUE TITLE
Feature request: Customizable ffmpeg batch commands

### ISSUE THREAD

**Issue by DAREK0N** [anidl/multi-downloader-nx#219]
As the title says, make it possible to customize the ffmpeg arguments.

Through a file like cli-defaults but for the ffmpeg defaults. Make the "standard" command(s) visible there and changeble for the "advanced" users.

**Comment by izu-co** [comment]
The commands are custom generated and are quite complex. Changing something might break the whole muxing process. I will leave this issue open, so everyone can give their thoughts if they would like said feature.
If there is enough support, I will work on this.

**Comment by izu-co** [comment]
If you tell me what you want to do, maybe I can add the option to do exactly that.
If you want to change the video codec for example, this would be possible.

**Comment by DAREK0N** [comment]
Yeah, exactly that. It would be great if I could change the Video and Audio codec and the target Bitrate in the downloader and not afterwards manually per ffmpeg batch.

**Comment by JuanF007** [comment]
> Yeah, exactly that. It would be great if I could change the Video and Audio codec and the target Bitrate in the downloader and not afterwards manually per ffmpeg batch.

I have managed to change the audio codec to AC3
but i can't add to video (mkv)

**Comment by izu-co** [comment]
What do you mean by that? You changed the code of the downloader or did you do it afterwards?

**Comment by JuanF007** [comment]
> What do you mean by that? You changed the code of the downloader or did you do it afterwards?

after

![Proyecto sin título](https://user-images.githubusercontent.com/43446222/149795034-172012d6-5644-4379-b4cd-fd3bf51f5f59.gif)

**Comment by izu-co** [comment]
Ah

**Comment by AnimeDL** [comment]
I believe `--ffmpegOptions` exists and should resolve this issue, so I'm going to close this. Feel free to re-open if that flag doesn't do what you need
