### ISSUE TITLE
[ERROR] HTTPError 404: Not Found

### ISSUE THREAD

**Issue by hayupadhyaya** [anidl/multi-downloader-nx#220]
### Program version

2.0.16

### Service

Funimation

### Command used

node index.js --service funi --auth

### Show ID

None

### Episode

None

### Console Output

root@raspberrypi:/home/pi/multi-downloader-nx/lib# node index.js --service funi --auth

=== Multi Downloader NX 2.0.16 ===

[Q] LOGIN/EMAIL: XXXXXXXXXX@gmail.com
[Q] PASSWORD   : XXXXXX
[DEBUG] GOT OPTIONS:
{
  method: 'POST',
  retry: {
    limit: 2,
    methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
    statusCodes: [
      408, 413, 429, 500,
      502, 503, 504, 521,
      522, 524
    ],
    errorCodes: [
      'ETIMEDOUT',
      'ECONNRESET',
      'EADDRINUSE',
      'ECONNREFUSED',
      'EPIPE',
      'ENOTFOUND',
      'ENETUNREACH',
      'EAI_AGAIN'
    ],
    maxRetryAfter: Infinity,
    calculateDelay: [Function: calculateDelay]
  },
  timeout: {},
  headers: {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0',
    'accept-encoding': 'gzip, deflate, br',
    'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
    origin: 'https://ww.funimation.com',
    accept: 'application/json, text/javascript, */*; q=0.01',
    'content-length': '53'
  },
  hooks: {
    beforeRequest: [ [Function (anonymous)] ],
    init: [],
    beforeRedirect: [],
    beforeError: [],
    beforeRetry: [],
    afterResponse: []
  },
  cache: undefined,
  dnsCache: undefined,
  decompress: true,
  throwHttpErrors: true,
  followRedirect: true,
  isStream: false,
  responseType: 'text',
  resolveBodyOnly: false,
  maxRedirects: 10,
  prefixUrl: [Getter/Setter],
  methodRewriting: true,
  ignoreInvalidCookies: false,
  http2: false,
  allowGetBody: false,
  https: undefined,
  pagination: {
    transform: [Function: transform],
    paginate: [Function: paginate],
    filter: [Function: filter],
    shouldContinue: [Function: shouldContinue],
    countLimit: Infinity,
    backoff: 0,
    requestLimit: 10000,
    stackAllItems: true
  },
  parseJson: [Function: parseJson],
  stringifyJson: [Function: stringifyJson],
  cacheOptions: {},
  url: URL {
    href: 'https://prod-api-funimationnow.dadcdigital.com/api/auth/login/',
    origin: 'https://prod-api-funimationnow.dadcdigital.com',
    protocol: 'https:',
    username: '',
    password: '',
    host: 'prod-api-funimationnow.dadcdigital.com',
    hostname: 'prod-api-funimationnow.dadcdigital.com',
    port: '',
    pathname: '/api/auth/login/',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },
  username: '',
  password: '',
  [Symbol(isNormalizedAlready)]: true
}
HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (/home/pi/multi-downloader-nx/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1642092800111,
    socket: 1642092800118,
    lookup: 1642092800133,
    connect: 1642092800199,
    secureConnect: 1642092800288,
    upload: 1642092800289,
    response: 1642092800616,
    end: 1642092800630,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 7,
      dns: 15,
      tcp: 66,
      tls: 89,
      request: 1,
      firstByte: 327,
      download: 14,
      total: 519
    }
  }
}
[ERROR] HTTPError 404: Not Found

### Additional Information

```Text
I am using this on a Raspberry pi (all the required libraries are correctly installed.)
Is there a specific browser I need to install in order to get it working? I have chromium install on the pi, (Raspberry Pi 4 - Bulls Eye-64 bit)
```

**Comment by izu-co** [comment]
Have you deleted the username and password from the got debug or was it the tool?

If you did it good, try to check if you can use funimation in your region. A browser is not required.
If you don’t, that’s probably the issue

**Comment by izu-co** [comment]
Closed due to inactivity.
