### ISSUE TITLE
BUG help

### ISSUE THREAD

**Issue by shoyrock** [anidl/multi-downloader-nx#222]
### Program version

2.0.17

### Service

Funimation

### Command used

anidl.exe --service funi -s 20224 -q 10 --nosubs -e 644

### Show ID

non

### Episode

644

### Console Output

[INFO] One Piece - S11E644 - A Blow of Anger! A Giant vs. Lucy!
[INFO] Available streams (Non-Encrypted):
[#52017] Japanese [Simulcast]
[#1337898] English [Uncut]
[#1337899] Japanese [Uncut] (selected)
[INFO] Servers available:
        vmfst-api.prd.funimationsvc.com
[INFO] Available qualities:
         1: 416x234 (474KiB/s)
         2: 640x360 (718KiB/s)
         3: 768x432 (1171KiB/s)
         4: 768x432 (1677KiB/s)
         5: 960x540 (2724KiB/s)
         6: 1280x720 (3961KiB/s)
         7: 1280x720 (5936KiB/s)
         8: 1920x1080 (7300KiB/s)
         9: 1920x1080 (9520KiB/s)
[INFO] Selected layer: 9 (1920x1080) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/V2141799/7b336dee-f30a-47b6-9c3c-e8a30ba3a306strnv-hl154_streaming_video_1920_1080_7800000_index.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC9WMjE0MTc5OS8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjQyMzEzMzgyfX19XX0_&Signature=Av%7Ei%7E21mk0C5L%7ESiKEM3OY7rtc0cJGL7h5-Sx7qCLSUtibFNN4xLRTuMri8dT3kGWLXJtxv3B53tOmDQHmPEd9ijFC2w6kT0uzlj8MLbPngWCeWAKtVNoE0Kk8KuTHy67coGlNGcg6Hm10pCJrJSGG9M%7EI2oJGZ9ob3z1kfe2Mxudu2sYZDxeEnv9%7EWD-4uWUpuJoxT8UDupyIsNL1qDht0N9UfT5GbZI9qOOnawfeAyJP0G3-zAuYNdWnVbDuFDhkSChgezzpMWEKUryx-JDX2uybz4Ow33kVwm0xwT1gjKeROoyyD1wWHKutdDMkqa%7EYo1yD8z3FV0wF7blc2h2A__&rt=1431030
[INFO] Output filename: [Funimation] One Piece - S11E644 [1080p].ts
[INFO] Saving stream to «D:\Funimation dl\videos\[Funimation] One Piece - S11E644 [1080p].video.ts»...
[INFO] 10 of 724 parts downloaded [1%] (3m13s | 6.6Mb/s)
[INFO] 20 of 724 parts downloaded [3%] (2m56s | 7.3Mb/s)
[INFO] 30 of 724 parts downloaded [4%] (2m42s | 7.3Mb/s)
[INFO] 40 of 724 parts downloaded [6%] (3m15s | 5.9Mb/s)
[INFO] 50 of 724 parts downloaded [7%] (3m12s | 6.1Mb/s)
[INFO] 60 of 724 parts downloaded [8%] (3m10s | 6.0Mb/s)
[INFO] 70 of 724 parts downloaded [10%] (2m57s | 6.3Mb/s)
[INFO] 80 of 724 parts downloaded [11%] (2m48s | 6.5Mb/s)
[INFO] 90 of 724 parts downloaded [12%] (2m38s | 6.8Mb/s)
[INFO] 100 of 724 parts downloaded [14%] (2m29s | 7.1Mb/s)
[INFO] 110 of 724 parts downloaded [15%] (2m25s | 7.2Mb/s)
[INFO] 120 of 724 parts downloaded [17%] (2m18s | 7.4Mb/s)
[INFO] 130 of 724 parts downloaded [18%] (2m12s | 7.6Mb/s)
[INFO] 140 of 724 parts downloaded [19%] (2m08s | 7.7Mb/s)
[INFO] 150 of 724 parts downloaded [21%] (2m04s | 7.8Mb/s)
[INFO] 160 of 724 parts downloaded [22%] (2m03s | 7.7Mb/s)
[INFO] 170 of 724 parts downloaded [23%] (1m59s | 7.8Mb/s)
[INFO] 180 of 724 parts downloaded [25%] (1m56s | 7.9Mb/s)
[INFO] 190 of 724 parts downloaded [26%] (1m53s | 7.9Mb/s)
[INFO] 200 of 724 parts downloaded [28%] (1m50s | 8.0Mb/s)
[INFO] 210 of 724 parts downloaded [29%] (1m46s | 8.1Mb/s)
[INFO] 220 of 724 parts downloaded [30%] (1m43s | 8.2Mb/s)
[INFO] 230 of 724 parts downloaded [32%] (1m41s | 8.2Mb/s)
[INFO] 240 of 724 parts downloaded [33%] (1m39s | 8.1Mb/s)
[INFO] 250 of 724 parts downloaded [35%] (1m38s | 8.0Mb/s)
[INFO] 260 of 724 parts downloaded [36%] (1m35s | 8.1Mb/s)
[INFO] 270 of 724 parts downloaded [37%] (1m33s | 8.1Mb/s)
[INFO] 280 of 724 parts downloaded [39%] (1m30s | 8.2Mb/s)
[INFO] 290 of 724 parts downloaded [40%] (1m27s | 8.3Mb/s)
[INFO] 300 of 724 parts downloaded [41%] (1m25s | 8.2Mb/s)
[INFO] 310 of 724 parts downloaded [43%] (1m26s | 7.9Mb/s)
[INFO] 320 of 724 parts downloaded [44%] (1m24s | 7.9Mb/s)
[INFO] 330 of 724 parts downloaded [46%] (1m22s | 8.0Mb/s)
[INFO] 340 of 724 parts downloaded [47%] (1m19s | 8.0Mb/s)
[INFO] 350 of 724 parts downloaded [48%] (1m17s | 8.1Mb/s)
[INFO] 360 of 724 parts downloaded [50%] (1m15s | 8.1Mb/s)
[INFO] 370 of 724 parts downloaded [51%] (1m13s | 8.1Mb/s)
[INFO] 380 of 724 parts downloaded [52%] (1m10s | 8.1Mb/s)
[INFO] 390 of 724 parts downloaded [54%] (1m11s | 7.8Mb/s)
[INFO] 400 of 724 parts downloaded [55%] (1m09s | 7.8Mb/s)
[INFO] 410 of 724 parts downloaded [57%] (1m06s | 7.8Mb/s)
[INFO] 420 of 724 parts downloaded [58%] (1m03s | 7.9Mb/s)
[INFO] 430 of 724 parts downloaded [59%] (1m01s | 7.9Mb/s)
[INFO] 440 of 724 parts downloaded [61%] (59s | 7.9Mb/s)
[INFO] 450 of 724 parts downloaded [62%] (57s | 7.9Mb/s)
[INFO] 460 of 724 parts downloaded [64%] (55s | 7.9Mb/s)
[INFO] 470 of 724 parts downloaded [65%] (53s | 7.9Mb/s)
[INFO] 480 of 724 parts downloaded [66%] (50s | 7.9Mb/s)
[INFO] 490 of 724 parts downloaded [68%] (49s | 7.9Mb/s)
[INFO] 500 of 724 parts downloaded [69%] (47s | 7.9Mb/s)
[INFO] 510 of 724 parts downloaded [70%] (44s | 7.9Mb/s)
[INFO] 520 of 724 parts downloaded [72%] (42s | 8.0Mb/s)
[INFO] 530 of 724 parts downloaded [73%] (39s | 8.0Mb/s)
[INFO] 540 of 724 parts downloaded [75%] (37s | 8.1Mb/s)
[INFO] 550 of 724 parts downloaded [76%] (35s | 8.1Mb/s)
[INFO] 560 of 724 parts downloaded [77%] (33s | 8.1Mb/s)
[INFO] 570 of 724 parts downloaded [79%] (31s | 8.1Mb/s)
[INFO] 580 of 724 parts downloaded [80%] (29s | 8.1Mb/s)
[INFO] 590 of 724 parts downloaded [81%] (27s | 8.1Mb/s)
[INFO] 600 of 724 parts downloaded [83%] (25s | 8.1Mb/s)
[INFO] 610 of 724 parts downloaded [84%] (23s | 8.1Mb/s)
[INFO] 620 of 724 parts downloaded [86%] (21s | 8.1Mb/s)
[INFO] 630 of 724 parts downloaded [87%] (19s | 8.1Mb/s)
[INFO] 640 of 724 parts downloaded [88%] (17s | 8.1Mb/s)
[INFO] 650 of 724 parts downloaded [90%] (15s | 8.1Mb/s)
[INFO] 660 of 724 parts downloaded [91%] (13s | 8.2Mb/s)
[INFO] 670 of 724 parts downloaded [93%] (11s | 8.2Mb/s)
[INFO] 680 of 724 parts downloaded [94%] (9s | 8.2Mb/s)
[INFO] 690 of 724 parts downloaded [95%] (7s | 8.2Mb/s)
[INFO] 700 of 724 parts downloaded [97%] (5s | 8.3Mb/s)
[INFO] 710 of 724 parts downloaded [98%] (3s | 8.3Mb/s)
[INFO] 720 of 724 parts downloaded [99%] (1s | 8.3Mb/s)
[INFO] 724 of 724 parts downloaded [100%] (0s | 8.3Mb/s)
[INFO] Saving stream to «D:\Funimation dl\videos\[Funimation] One Piece - S11E644 [1080p].audio.jpn.ts»...
[INFO] 10 of 725 parts downloaded [1%] (16s | 2.8Mb/s)
[INFO] 20 of 725 parts downloaded [3%] (13s | 3.5Mb/s)
[INFO] 30 of 725 parts downloaded [4%] (12s | 3.9Mb/s)
[INFO] 40 of 725 parts downloaded [6%] (11s | 4.1Mb/s)
[INFO] 50 of 725 parts downloaded [7%] (10s | 4.3Mb/s)
[INFO] 60 of 725 parts downloaded [8%] (10s | 4.3Mb/s)
[INFO] 70 of 725 parts downloaded [10%] (10s | 4.3Mb/s)
[INFO] 80 of 725 parts downloaded [11%] (9s | 4.4Mb/s)
[INFO] 90 of 725 parts downloaded [12%] (9s | 4.4Mb/s)
[INFO] 100 of 725 parts downloaded [14%] (10s | 3.9Mb/s)
[INFO] 110 of 725 parts downloaded [15%] (10s | 3.9Mb/s)
[INFO] 120 of 725 parts downloaded [17%] (10s | 3.9Mb/s)
[INFO] 130 of 725 parts downloaded [18%] (10s | 4.0Mb/s)
[INFO] 140 of 725 parts downloaded [19%] (9s | 4.0Mb/s)
[INFO] 150 of 725 parts downloaded [21%] (9s | 4.1Mb/s)
[INFO] 160 of 725 parts downloaded [22%] (9s | 4.1Mb/s)
[INFO] 170 of 725 parts downloaded [23%] (9s | 4.2Mb/s)
[INFO] 180 of 725 parts downloaded [25%] (8s | 4.2Mb/s)
[INFO] 190 of 725 parts downloaded [26%] (8s | 4.3Mb/s)
[INFO] 200 of 725 parts downloaded [28%] (8s | 4.3Mb/s)
[INFO] 210 of 725 parts downloaded [29%] (8s | 4.3Mb/s)
[INFO] 220 of 725 parts downloaded [30%] (7s | 4.4Mb/s)
[INFO] 230 of 725 parts downloaded [32%] (7s | 4.4Mb/s)
[INFO] 240 of 725 parts downloaded [33%] (7s | 4.5Mb/s)
[INFO] 250 of 725 parts downloaded [34%] (7s | 4.4Mb/s)
[INFO] 260 of 725 parts downloaded [36%] (7s | 4.4Mb/s)
[INFO] 270 of 725 parts downloaded [37%] (7s | 4.5Mb/s)
[INFO] 280 of 725 parts downloaded [39%] (6s | 4.5Mb/s)
[INFO] 290 of 725 parts downloaded [40%] (6s | 4.5Mb/s)
[INFO] 300 of 725 parts downloaded [41%] (6s | 4.5Mb/s)
[INFO] 310 of 725 parts downloaded [43%] (6s | 4.5Mb/s)
[INFO] 320 of 725 parts downloaded [44%] (6s | 4.5Mb/s)
[INFO] 330 of 725 parts downloaded [46%] (6s | 4.6Mb/s)
[INFO] 340 of 725 parts downloaded [47%] (5s | 4.6Mb/s)
[INFO] 350 of 725 parts downloaded [48%] (5s | 4.6Mb/s)
[INFO] 360 of 725 parts downloaded [50%] (5s | 4.6Mb/s)
[INFO] 370 of 725 parts downloaded [51%] (5s | 4.6Mb/s)
[INFO] 380 of 725 parts downloaded [52%] (5s | 4.6Mb/s)
[INFO] 390 of 725 parts downloaded [54%] (5s | 4.6Mb/s)
[INFO] 400 of 725 parts downloaded [55%] (5s | 4.6Mb/s)
[INFO] 410 of 725 parts downloaded [57%] (4s | 4.6Mb/s)
[INFO] 420 of 725 parts downloaded [58%] (4s | 4.6Mb/s)
[INFO] 430 of 725 parts downloaded [59%] (4s | 4.5Mb/s)
[INFO] 440 of 725 parts downloaded [61%] (4s | 4.5Mb/s)
[INFO] 450 of 725 parts downloaded [62%] (4s | 4.5Mb/s)
[INFO] 460 of 725 parts downloaded [63%] (4s | 4.5Mb/s)
[INFO] 470 of 725 parts downloaded [65%] (4s | 4.5Mb/s)
[INFO] 480 of 725 parts downloaded [66%] (4s | 4.5Mb/s)
[INFO] 490 of 725 parts downloaded [68%] (3s | 4.5Mb/s)
[INFO] 500 of 725 parts downloaded [69%] (3s | 4.5Mb/s)
[INFO] 510 of 725 parts downloaded [70%] (3s | 4.5Mb/s)
[INFO] 520 of 725 parts downloaded [72%] (3s | 4.2Mb/s)
[INFO] 530 of 725 parts downloaded [73%] (3s | 4.1Mb/s)
[INFO] 540 of 725 parts downloaded [74%] (3s | 4.2Mb/s)
[INFO] 550 of 725 parts downloaded [76%] (3s | 4.2Mb/s)
[INFO] 560 of 725 parts downloaded [77%] (3s | 4.1Mb/s)
[INFO] 570 of 725 parts downloaded [79%] (2s | 4.1Mb/s)
[INFO] 580 of 725 parts downloaded [80%] (2s | 4.1Mb/s)
[INFO] 590 of 725 parts downloaded [81%] (2s | 4.1Mb/s)
[INFO] 600 of 725 parts downloaded [83%] (2s | 4.1Mb/s)
[INFO] 610 of 725 parts downloaded [84%] (2s | 4.2Mb/s)
[INFO] 620 of 725 parts downloaded [86%] (2s | 4.1Mb/s)
[INFO] 630 of 725 parts downloaded [87%] (1s | 4.1Mb/s)
[INFO] 640 of 725 parts downloaded [88%] (1s | 4.1Mb/s)
[INFO] 650 of 725 parts downloaded [90%] (1s | 4.2Mb/s)
[INFO] 660 of 725 parts downloaded [91%] (1s | 4.2Mb/s)
[INFO] 670 of 725 parts downloaded [92%] (1s | 4.2Mb/s)
[INFO] 680 of 725 parts downloaded [94%] (1s | 4.2Mb/s)
[INFO] 690 of 725 parts downloaded [95%] (1s | 4.2Mb/s)
[INFO] 700 of 725 parts downloaded [97%] (0s | 4.2Mb/s)
[INFO] 710 of 725 parts downloaded [98%] (0s | 4.1Mb/s)
[INFO] 720 of 725 parts downloaded [99%] (0s | 4.1Mb/s)
[INFO] 725 of 725 parts downloaded [100%] (0s | 4.1Mb/s)
[WARN] MKVMerge not found, skip muxing...

[INFO] Done!

### Additional Information

```Text
I've been trying to download the dubbed version of one piece but I keep getting the jap version,
also can I get an example on how to configure bin-path.yml I keep getting [WARN] MKVMerge not found, skip muxing...
```

**Comment by Evoley** [comment]
--dubLang jpn eng

**Comment by ChrisCrashX** [comment]
I'm having a similar issue with
"[WARN] MKVMerge not found, skip muxing..."

**Comment by Evoley** [comment]
> I'm having a similar issue with "[WARN] MKVMerge not found, skip muxing..."

Did you download it and edit the bin.yml?

**Comment by ChrisCrashX** [comment]
> > I'm having a similar issue with "[WARN] MKVMerge not found, skip muxing..."
> 
> Did you download it and edit the bin.yml?

Yes, but it was previously installed on my PC, I'm not quite sure what to change the bin-path.yml to

**Comment by Evoley** [comment]
> 

Generally wherever you have the exe.'s. For example.. my exe's are in L:\funi\bin\xxx. I would just change the yml to
 ffmpeg: ".\\bin\\ffmpeg\\ffmpeg.exe"
mkvmerge: ".\\bin\\mkvtoolnix\\mkvmerge.exe"

**Comment by ChrisCrashX** [comment]
> > 
> 
> Generally wherever you have the exe.'s. For example.. my exe's are in L:\funi\bin\xxx. I would just change the yml to ffmpeg: ".\bin\ffmpeg\ffmpeg.exe" mkvmerge: ".\bin\mkvtoolnix\mkvmerge.exe"

Thanks, that worked 🙏

**Comment by shoyrock** [comment]
> 

thanks you're a life saver I had it as // not \\

**Comment by izu-co** [comment]
I think this issue has been resolved.
Thanks @Evoley
