### ISSUE TITLE
i dont know if this is a bug or not

### ISSUE THREAD

**Issue by shoyrock** [anidl/multi-downloader-nx#223]
been trying to download this this episode and it hasn't been downloaded it's not locked and it's not busy.
![Screenshot_3](https://user-images.githubusercontent.com/51036435/149674112-3e1ba1ab-ffbe-424e-8139-271614e4db06.png)

anidl.exe --service funi -s 20224 -q 10 --nosubs --dubLang eng --mkv -e 656 --fileName "${showTitle} - S${season}E${episode} - ${title}

**Comment by izu-co** [comment]
If this error happens, please follow the following steps:
```
Press windows key plus R on your keyboard to open the run command box and type this

resmon.exe

click OK to open resource monitor
In the monitor, navigate to CPU tab
Under Associated Handles in the search box, copy the path to the file or folder in question and paste it in there
Click on the search icon
```
Send me a screenshot if you find a running process.
Also, is this error reproducible (does it happen on the same episode every time?)

**Comment by shoyrock** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/51036435/149677192-dd629542-7eac-441c-b6b3-cba3b0635108.png)

yes its reproducible, and it also happened on episode One Piece - S11E658 - A Big Surprise! The True Identity of the Toy Soldier

**Comment by shoyrock** [comment]
I ended the process and reloaded Explorer and that seems to work. not sure what was the problem

**Comment by izu-co** [comment]
Good to hear
