### ISSUE TITLE
EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by shoyrock** [anidl/multi-downloader-nx#224]
im still having the same problem 
![Screenshot_5](https://user-images.githubusercontent.com/51036435/149683533-5a71053f-3be8-4633-ace4-5257a8255042.png)
idk what to do at this point

**Comment by izu-co** [comment]
Please see the newest release. I've added an option where the downloader will now retry 3 times if an error during the writing process occurs (hopefully enough time for whatever process used to file to get the f** out).
You can increase the time the downloader waits between each attempt by using a command (please see the documentation).

**Comment by shoyrock** [comment]
seems like the update works haven't had that problem since I've updated, still keeping an eye out

**Comment by izu-co** [comment]
Nice to hear
