### ISSUE TITLE
BUG undefined series name on dubs (--srz)

### ISSUE THREAD

**Issue by CMoranO** [anidl/multi-downloader-nx#226]
### Program version

2.0.18

### Service

Crunchyroll

### Command used

node index.js --service crunchy --srz 'GP5HJ800Z'  --dubLang spa jpn --dlsubs es-419 -q 5 -e 9

### Show ID

GP5HJ800Z

### Episode

9

### Console Output

PS G:\Funimation\lib> node index.js --service crunchy --srz 'GP5HJ800Z'  --dubLang spa jpn --dlsubs es-419 -q 5 -e 9

=== Multi Downloader NX 2.0.18 ===

[INFO] USER: undefined (****@gmail.com)
[INFO] Your Country: **

[Z:GP5HJ800Z] SAKUGAN (Seasons: 7, EPs: 57) [SIMULCAST, SUB, DUB]
  [S:GYX0C4DD9] SAKUGAN (Portuguese Dub) (Season: 1) [SIMULCAST, DUB]
  [S:G649C733E] SAKUGAN (German Dub) (Season: 1) [SIMULCAST, DUB]
  [S:G69PC2XXP] SAKUGAN (Spanish Dub) (Season: 1) [SIMULCAST, DUB]
  [S:G6JQC1MM3] SAKUGAN (English Dub) (Season: 1) [SIMULCAST, DUB]
  [S:GR19CP330] SAKUGAN (French Dub) (Season: 1) [SIMULCAST, DUB]
  [S:GRNQCJZ8D] SAKUGAN (Season: 2) [SIMULCAST, SUB]
[S1E1] SAKUGAN (Portuguese Dub) - FATHERS & DAUGHTERS [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[S1E2] SAKUGAN (Portuguese Dub) - GOOD DAY, GOOD BYE [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[S1E3] SAKUGAN (Portuguese Dub) - BRAINS & HEARTS [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[S1E4] SAKUGAN (Portuguese Dub) - LADIES & GENTLEMEN [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[S1E5] SAKUGAN (Portuguese Dub) - NO WORK, NO LIFE [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[S1E6] SAKUGAN (Portuguese Dub) - JUSTICE FOR VILLAINS [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[S1E7] SAKUGAN (Portuguese Dub) - ON THE ROAD [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[S1E8] SAKUGAN (Portuguese Dub) - MEMORIES & REGRETS [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[S1E9] SAKUGAN (Portuguese Dub) - END OF VACATION [☆ Portuguese, ☆ German, ☆ Spanish, ☆ English, ☆ French]
[S2E1] SAKUGAN - FATHERS & DAUGHTERS [Japanese]
[S2E2] SAKUGAN - GOOD DAY, GOOD BYE [Japanese]
[S2E3] SAKUGAN - BRAINS & HEARTS [Japanese]
[S2E4] SAKUGAN - LADIES & GENTLEMEN [Japanese]
[S2E5] SAKUGAN - NO WORK, NO LIFE [Japanese]
[S2E6] SAKUGAN - JUSTICE FOR VILLAINS [Japanese]
[S2E7] SAKUGAN - ON THE ROAD [Japanese]
[S2E8] SAKUGAN - MEMORIES & REGRETS [Japanese]
[S2E9] SAKUGAN - END OF VACATION [Japanese]
[S2E10] SAKUGAN - OH MY TONY [Japanese]
[S2E11] SAKUGAN - SOUND OF DREAM [Japanese]
[S2E12] SAKUGAN - TO BE CONTINUED [Japanese]

------------------------------

[S1E9] - END OF VACATION [✓ Spanish]
[S2E9] - END OF VACATION [✓ Japanese]
[INFO] Requesting: [GPWUK5QMP] ...
[INFO] Selecting raw stream
[INFO] Full stream found! (✓1: adaptive_hls/spa/- )
[INFO] Full stream found! ( 2: download_hls/spa/- )
[INFO] Full stream found! ( 3: vo_adaptive_hls/spa/- )
[INFO] Downloading video...
[INFO] Playlists URL: https://pl.crunchyroll.com/evs1/bcda11d8a81926ecdfa0568d96925e13/assets/5a09a23f222c7008a24575da2f08d7de_,4264167.mp4,4264168.mp4,4264166.mp4,4264164.mp4,4264165.mp4,4264163.mp4,.urlset/master.m3u8?Expires=1642665975&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9iY2RhMTFkOGE4MTkyNmVjZGZhMDU2OGQ5NjkyNWUxMy9hc3NldHMvNWEwOWEyM2YyMjJjNzAwOGEyNDU3NWRhMmYwOGQ3ZGVfLDQyNjQxNjcubXA0LDQyNjQxNjgubXA0LDQyNjQxNjYubXA0LDQyNjQxNjQubXA0LDQyNjQxNjUubXA0LDQyNjQxNjMubXA0LC51cmxzZXQvbWFzdGVyLm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDI2NjU5NzV9fX1dfQ__&Signature=NIBk~U5XEU1JOkmPLm6enaZFgH8GTqdzWgIEI9vv-maPtrjZv-v31hY3QbGlIAZcFc-JGgDHbzr73pvldzt4u5uLZob8MTvsJDJ3UZJhXDvpAQtzpQIInx4Bc1ZjhCkvhYwSyJ1qYtJ3MsB82JBcYuGtrxNi9GLVlsn1iW1KeIoUMJGZqgevaS58ouQEnzcoh1Jw4lEgg9oXLNUc219gHA9Fp~M0kI~QnERR0i7Iu4bNlxGsiBcUJb-0Ry53QWsuD9Yv-izcgqxyWCYzpyysqIPqEHqJYyjBM5tWd2VjG1hUpgFb4W8wsh5epRqj1rIRjZF~c8f4a1HIVlLX6koUcg__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA (adaptive_hls/spa/-)
[INFO] Servers available:
        pl.crunchyroll.com (ll-prod)
        pl.crunchyroll.com (fy-prod)
[INFO] Available qualities:
        [1] 144x80 (191KiB/s)
        [2] 428x240 (549KiB/s)
        [3] 640x360 (1068KiB/s)
        [4] 848x480 (2042KiB/s)
        [5] 1280x720 (4022KiB/s)
        [6] 1920x1080 (7915KiB/s)
[INFO] Selected quality: 1280x720 @ pl.crunchyroll.com (ll-prod)
[INFO] Output filename: [CR] undefined - S01E09 [720p].Spanish
[INFO] Total parts in stream: 710 (71*10)
[INFO] Saving stream to «G:\Funimation\lib\videos\[CR] undefined - S01E09 [720p].Spanish.ts»...
[INFO] 10 of 710 parts downloaded [1%] (1m14s | 14Mb/s)
[INFO] 20 of 710 parts downloaded [3%] (1m05s | 16Mb/s)
[INFO] 30 of 710 parts downloaded [4%] (1m00s | 17Mb/s)
[INFO] 40 of 710 parts downloaded [6%] (56s | 17Mb/s)
[INFO] 50 of 710 parts downloaded [7%] (58s | 16Mb/s)
[INFO] 60 of 710 parts downloaded [8%] (53s | 17Mb/s)
[INFO] 70 of 710 parts downloaded [10%] (54s | 16Mb/s)
[INFO] 80 of 710 parts downloaded [11%] (53s | 16Mb/s)
[INFO] 90 of 710 parts downloaded [13%] (55s | 16Mb/s)
[INFO] 100 of 710 parts downloaded [14%] (55s | 16Mb/s)
[INFO] 110 of 710 parts downloaded [15%] (54s | 16Mb/s)
[INFO] 120 of 710 parts downloaded [17%] (54s | 16Mb/s)
[INFO] 130 of 710 parts downloaded [18%] (52s | 15Mb/s)
[INFO] 140 of 710 parts downloaded [20%] (51s | 15Mb/s)
[INFO] 150 of 710 parts downloaded [21%] (50s | 15Mb/s)
[INFO] 160 of 710 parts downloaded [23%] (48s | 15Mb/s)
[INFO] 170 of 710 parts downloaded [24%] (47s | 15Mb/s)
[INFO] 180 of 710 parts downloaded [25%] (46s | 15Mb/s)
[INFO] 190 of 710 parts downloaded [27%] (44s | 15Mb/s)
[INFO] 200 of 710 parts downloaded [28%] (44s | 14Mb/s)
[INFO] 210 of 710 parts downloaded [30%] (43s | 15Mb/s)
[INFO] 220 of 710 parts downloaded [31%] (42s | 14Mb/s)
[INFO] 230 of 710 parts downloaded [32%] (42s | 14Mb/s)
[INFO] 240 of 710 parts downloaded [34%] (41s | 14Mb/s)
[INFO] 250 of 710 parts downloaded [35%] (40s | 14Mb/s)
[INFO] 260 of 710 parts downloaded [37%] (40s | 14Mb/s)
[INFO] 270 of 710 parts downloaded [38%] (39s | 14Mb/s)
[INFO] 280 of 710 parts downloaded [39%] (38s | 14Mb/s)
[INFO] 290 of 710 parts downloaded [41%] (37s | 14Mb/s)
[INFO] 300 of 710 parts downloaded [42%] (36s | 14Mb/s)
[INFO] 310 of 710 parts downloaded [44%] (35s | 14Mb/s)
[INFO] 320 of 710 parts downloaded [45%] (34s | 14Mb/s)
[INFO] 330 of 710 parts downloaded [46%] (33s | 14Mb/s)
[INFO] 340 of 710 parts downloaded [48%] (31s | 14Mb/s)
[INFO] 350 of 710 parts downloaded [49%] (31s | 14Mb/s)
[INFO] 360 of 710 parts downloaded [51%] (30s | 14Mb/s)
[INFO] 370 of 710 parts downloaded [52%] (29s | 14Mb/s)
[INFO] 380 of 710 parts downloaded [54%] (28s | 14Mb/s)
[INFO] 390 of 710 parts downloaded [55%] (27s | 14Mb/s)
[INFO] 400 of 710 parts downloaded [56%] (26s | 14Mb/s)
[INFO] 410 of 710 parts downloaded [58%] (25s | 14Mb/s)
[INFO] 420 of 710 parts downloaded [59%] (25s | 14Mb/s)
[INFO] 430 of 710 parts downloaded [61%] (24s | 14Mb/s)
[INFO] 440 of 710 parts downloaded [62%] (23s | 14Mb/s)
[INFO] 450 of 710 parts downloaded [63%] (22s | 14Mb/s)
[INFO] 460 of 710 parts downloaded [65%] (21s | 14Mb/s)
[INFO] 470 of 710 parts downloaded [66%] (20s | 14Mb/s)
[INFO] 480 of 710 parts downloaded [68%] (19s | 14Mb/s)
[INFO] 490 of 710 parts downloaded [69%] (18s | 14Mb/s)
[INFO] 500 of 710 parts downloaded [70%] (17s | 14Mb/s)
[INFO] 510 of 710 parts downloaded [72%] (17s | 14Mb/s)
[INFO] 520 of 710 parts downloaded [73%] (16s | 14Mb/s)
[INFO] 530 of 710 parts downloaded [75%] (15s | 14Mb/s)
[INFO] 540 of 710 parts downloaded [76%] (14s | 13Mb/s)
[INFO] 550 of 710 parts downloaded [77%] (13s | 13Mb/s)
[INFO] 560 of 710 parts downloaded [79%] (12s | 13Mb/s)
[INFO] 570 of 710 parts downloaded [80%] (11s | 13Mb/s)
[INFO] 580 of 710 parts downloaded [82%] (10s | 13Mb/s)
[INFO] 590 of 710 parts downloaded [83%] (10s | 13Mb/s)
[INFO] 600 of 710 parts downloaded [85%] (9s | 13Mb/s)
[INFO] 610 of 710 parts downloaded [86%] (8s | 13Mb/s)
[INFO] 620 of 710 parts downloaded [87%] (7s | 13Mb/s)
[INFO] 630 of 710 parts downloaded [89%] (6s | 13Mb/s)
[INFO] 640 of 710 parts downloaded [90%] (6s | 13Mb/s)
[INFO] 650 of 710 parts downloaded [92%] (5s | 13Mb/s)
[INFO] 660 of 710 parts downloaded [93%] (4s | 13Mb/s)
[INFO] 670 of 710 parts downloaded [94%] (3s | 13Mb/s)
[INFO] 680 of 710 parts downloaded [96%] (2s | 13Mb/s)
[INFO] 690 of 710 parts downloaded [97%] (2s | 13Mb/s)
[INFO] 700 of 710 parts downloaded [99%] (1s | 13Mb/s)
[INFO] 710 of 710 parts downloaded [100%] (0s | 13Mb/s)
[WARN] Can't find urls for subtitles!

> "mkvmerge" -o "G:\Funimation\lib\videos\[CR] undefined - S01E09 [720p].mkv" --no-date --disable-track-statistics-tags --engage no_variable_data --video-tracks 0 --audio-tracks 1 --track-name 0:"Spanish [Uncut]" --track-name 1:"Spanish [Uncut]" --language 1:spa "G:\Funimation\lib\videos\[CR] undefined - S01E09 [720p].Spanish.ts" --no-subtitles --no-attachments
mkvmerge v61.0.0 ('So') 64-bit
'G:\Funimation\lib\videos\[CR] undefined - S01E09 [720p].Spanish.ts': Using the demultiplexer for the format 'MPEG transport stream'.
'G:\Funimation\lib\videos\[CR] undefined - S01E09 [720p].Spanish.ts' track 0: Using the output module for the format 'AVC/H.264 (unframed)'.
'G:\Funimation\lib\videos\[CR] undefined - S01E09 [720p].Spanish.ts' track 1: Using the output module for the format 'AAC'.
The file 'G:\Funimation\lib\videos\[CR] undefined - S01E09 [720p].mkv' has been opened for writing.
'G:\Funimation\lib\videos\[CR] undefined - S01E09 [720p].Spanish.ts' track 0: Extracted the aspect ratio information from the video bitstream and set the display dimensions to 1280/720.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 6 seconds.
[INFO] Requesting: [GVWU0PMEP] SAKUGAN - 9 - END OF VACATION
[INFO] Selecting raw stream
[INFO] Full stream found! (✓1: adaptive_hls/jpn/- )
[INFO] Full stream found! ( 2: download_hls/jpn/- )
[INFO] Full stream found! ( 3: vo_adaptive_hls/jpn/- )
[INFO] Downloading video...
[INFO] Playlists URL: https://pl.crunchyroll.com/evs1/66b0792e63d585ec855b9dfbb943a32d/assets/b98515c153fc368ce424227d15a763fa_,4226518.mp4,4226519.mp4,4226517.mp4,4226515.mp4,4226516.mp4,4226514.mp4,.urlset/master.m3u8?Expires=1642666040&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS82NmIwNzkyZTYzZDU4NWVjODU1YjlkZmJiOTQzYTMyZC9hc3NldHMvYjk4NTE1YzE1M2ZjMzY4Y2U0MjQyMjdkMTVhNzYzZmFfLDQyMjY1MTgubXA0LDQyMjY1MTkubXA0LDQyMjY1MTcubXA0LDQyMjY1MTUubXA0LDQyMjY1MTYubXA0LDQyMjY1MTQubXA0LC51cmxzZXQvbWFzdGVyLm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDI2NjYwNDB9fX1dfQ__&Signature=AptTnfFiOc3tfub2lq340M6Nlai0ZgrLk1cDDR-B8R7VkRhpyJwPRfS0WQp8uA2i9CE6gETm-UzwGMHfl~FE6~pSw06fI8jUmx-wWwod0rxs4T-qzANWa5yJIAg8SDznvJSJyd80m12FOsqptXZMytjHBNEONkHG7wdtOLS4Tm~Zjs6-LLqAbDsI2M3LFfPTpJvEzc1QHJcB4izLEx3gBEpBm9lngy67pYVNcrhmEsXC5Ke537EygfR5WLT2VRvI6gZZm-A302ccWSPx2IHdsJnN~-czwVUN2uFDEUPdDOFgOo4bVBccAaGsxI33ub-muJYXukNMVlWyBd438iQ4DQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA (adaptive_hls/jpn/-)
[INFO] Servers available:
        pl.crunchyroll.com (ll-prod)
        pl.crunchyroll.com (fy-prod)
[INFO] Available qualities:
        [1] 144x80 (191KiB/s)
        [2] 428x240 (549KiB/s)
        [3] 640x360 (1066KiB/s)
        [4] 848x480 (2038KiB/s)
        [5] 1280x720 (4025KiB/s)
        [6] 1920x1080 (7905KiB/s)
[INFO] Selected quality: 1280x720 @ pl.crunchyroll.com (ll-prod)
[INFO] Output filename: [CR] SAKUGAN - S02E09 [720p].Japanese
[INFO] Total parts in stream: 710 (71*10)
[INFO] Saving stream to «G:\Funimation\lib\videos\[CR] SAKUGAN - S02E09 [720p].Japanese.ts»...
[INFO] 10 of 710 parts downloaded [1%] (1m34s | 9.9Mb/s)
[INFO] 20 of 710 parts downloaded [3%] (1m22s | 12Mb/s)
[INFO] 30 of 710 parts downloaded [4%] (1m15s | 13Mb/s)
[INFO] 40 of 710 parts downloaded [6%] (1m12s | 13Mb/s)
[INFO] 50 of 710 parts downloaded [7%] (1m08s | 13Mb/s)
[INFO] 60 of 710 parts downloaded [8%] (1m09s | 12Mb/s)
[INFO] 70 of 710 parts downloaded [10%] (1m13s | 11Mb/s)
[INFO] 80 of 710 parts downloaded [11%] (1m10s | 12Mb/s)
[INFO] 90 of 710 parts downloaded [13%] (1m08s | 12Mb/s)
[INFO] 100 of 710 parts downloaded [14%] (1m11s | 12Mb/s)
[INFO] 110 of 710 parts downloaded [15%] (1m10s | 12Mb/s)
[INFO] 120 of 710 parts downloaded [17%] (1m08s | 12Mb/s)
[INFO] 130 of 710 parts downloaded [18%] (1m06s | 12Mb/s)
[INFO] 140 of 710 parts downloaded [20%] (1m05s | 12Mb/s)
[INFO] 150 of 710 parts downloaded [21%] (1m03s | 12Mb/s)
[INFO] 160 of 710 parts downloaded [23%] (1m01s | 12Mb/s)
[INFO] 170 of 710 parts downloaded [24%] (58s | 12Mb/s)
[INFO] 180 of 710 parts downloaded [25%] (56s | 12Mb/s)
[INFO] 190 of 710 parts downloaded [27%] (54s | 11Mb/s)
[INFO] 200 of 710 parts downloaded [28%] (53s | 11Mb/s)
[INFO] 210 of 710 parts downloaded [30%] (53s | 11Mb/s)
[INFO] 220 of 710 parts downloaded [31%] (52s | 11Mb/s)
[INFO] 230 of 710 parts downloaded [32%] (51s | 11Mb/s)
[INFO] 240 of 710 parts downloaded [34%] (50s | 11Mb/s)
[INFO] 250 of 710 parts downloaded [35%] (49s | 11Mb/s)
[INFO] 260 of 710 parts downloaded [37%] (49s | 11Mb/s)
[INFO] 270 of 710 parts downloaded [38%] (47s | 11Mb/s)
[INFO] 280 of 710 parts downloaded [39%] (46s | 11Mb/s)
[INFO] 290 of 710 parts downloaded [41%] (45s | 11Mb/s)
[INFO] 300 of 710 parts downloaded [42%] (43s | 12Mb/s)
[INFO] 310 of 710 parts downloaded [44%] (42s | 12Mb/s)
[INFO] 320 of 710 parts downloaded [45%] (40s | 12Mb/s)
[INFO] 330 of 710 parts downloaded [46%] (40s | 11Mb/s)
[INFO] 340 of 710 parts downloaded [48%] (38s | 11Mb/s)
[INFO] 350 of 710 parts downloaded [49%] (37s | 11Mb/s)
[INFO] 360 of 710 parts downloaded [51%] (36s | 11Mb/s)
[INFO] 370 of 710 parts downloaded [52%] (35s | 11Mb/s)
[INFO] 380 of 710 parts downloaded [54%] (34s | 11Mb/s)
[INFO] 390 of 710 parts downloaded [55%] (33s | 11Mb/s)
[INFO] 400 of 710 parts downloaded [56%] (32s | 11Mb/s)
[INFO] 410 of 710 parts downloaded [58%] (31s | 11Mb/s)
[INFO] 420 of 710 parts downloaded [59%] (30s | 11Mb/s)
[INFO] 430 of 710 parts downloaded [61%] (28s | 11Mb/s)
[INFO] 440 of 710 parts downloaded [62%] (27s | 11Mb/s)
[INFO] 450 of 710 parts downloaded [63%] (26s | 11Mb/s)
[INFO] 460 of 710 parts downloaded [65%] (25s | 11Mb/s)
[INFO] 470 of 710 parts downloaded [66%] (24s | 11Mb/s)
[INFO] 480 of 710 parts downloaded [68%] (23s | 11Mb/s)
[INFO] 490 of 710 parts downloaded [69%] (22s | 11Mb/s)
[INFO] 500 of 710 parts downloaded [70%] (21s | 11Mb/s)
[INFO] 510 of 710 parts downloaded [72%] (20s | 11Mb/s)
[INFO] 520 of 710 parts downloaded [73%] (19s | 11Mb/s)
[INFO] 530 of 710 parts downloaded [75%] (18s | 11Mb/s)
[INFO] 540 of 710 parts downloaded [76%] (17s | 11Mb/s)
[INFO] 550 of 710 parts downloaded [77%] (16s | 11Mb/s)
[INFO] 560 of 710 parts downloaded [79%] (15s | 11Mb/s)
[INFO] 570 of 710 parts downloaded [80%] (14s | 11Mb/s)
[INFO] 580 of 710 parts downloaded [82%] (13s | 11Mb/s)
[INFO] 590 of 710 parts downloaded [83%] (12s | 11Mb/s)
[INFO] 600 of 710 parts downloaded [85%] (11s | 11Mb/s)
[INFO] 610 of 710 parts downloaded [86%] (10s | 11Mb/s)
[INFO] 620 of 710 parts downloaded [87%] (9s | 11Mb/s)
[INFO] 630 of 710 parts downloaded [89%] (8s | 11Mb/s)
[INFO] 640 of 710 parts downloaded [90%] (7s | 11Mb/s)
[INFO] 650 of 710 parts downloaded [92%] (6s | 11Mb/s)
[INFO] 660 of 710 parts downloaded [93%] (5s | 11Mb/s)
[INFO] 670 of 710 parts downloaded [94%] (4s | 11Mb/s)
[INFO] 680 of 710 parts downloaded [96%] (3s | 11Mb/s)
[INFO] 690 of 710 parts downloaded [97%] (2s | 11Mb/s)
[INFO] 700 of 710 parts downloaded [99%] (1s | 11Mb/s)
[INFO] 710 of 710 parts downloaded [100%] (0s | 11Mb/s)
[INFO] Subtitle downloaded: [CR] SAKUGAN - S02E09 [720p].01 spa Latin American Spanish.ass

[INFO] Subtitles: es-419 (Total: 1)
[INFO] Required fonts: Trebuchet MS, Arial, Times New Roman (Total: 3)

> "mkvmerge" -o "G:\Funimation\lib\videos\[CR] SAKUGAN - S02E09 [720p].mkv" --no-date --disable-track-statistics-tags --engage no_variable_data --video-tracks 0 --audio-tracks 1 --track-name 0:"Japanese [Uncut]" --track-name 1:"Japanese [Uncut]" --language 1:jpn "G:\Funimation\lib\videos\[CR] SAKUGAN - S02E09 [720p].Japanese.ts" --track-name 0:"Latin American Spanish" --language 0:"spa" "G:\Funimation\lib\videos\[CR] SAKUGAN - S02E09 [720p].01 spa Latin American Spanish.ass" --no-attachments
mkvmerge v61.0.0 ('So') 64-bit
'G:\Funimation\lib\videos\[CR] SAKUGAN - S02E09 [720p].Japanese.ts': Using the demultiplexer for the format 'MPEG transport stream'.
'G:\Funimation\lib\videos\[CR] SAKUGAN - S02E09 [720p].01 spa Latin American Spanish.ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'G:\Funimation\lib\videos\[CR] SAKUGAN - S02E09 [720p].Japanese.ts' track 0: Using the output module for the format 'AVC/H.264 (unframed)'.
'G:\Funimation\lib\videos\[CR] SAKUGAN - S02E09 [720p].Japanese.ts' track 1: Using the output module for the format 'AAC'.
'G:\Funimation\lib\videos\[CR] SAKUGAN - S02E09 [720p].01 spa Latin American Spanish.ass' track 0: Using the output module for the format 'SSA/ASS text subtitles'.
The file 'G:\Funimation\lib\videos\[CR] SAKUGAN - S02E09 [720p].mkv' has been opened for writing.
'G:\Funimation\lib\videos\[CR] SAKUGAN - S02E09 [720p].Japanese.ts' track 0: Extracted the aspect ratio information from the video bitstream and set the display dimensions to 1280/720.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 6 seconds.

### Additional Information

```Text
Output files:

[CR] SAKUGAN - S02E09 [720p].mkv (jpn audio, spa subs)
[CR] undefined - S01E09 [720p].mkv (spa audio)
```

**Comment by izu-co** [comment]
Fixed with the newest commit.
