### ISSUE TITLE
bug [ERROR] Track not selected

### ISSUE THREAD

**Issue by shoyrock** [anidl/multi-downloader-nx#228]
![Screenshot_6](https://user-images.githubusercontent.com/51036435/150396676-3dc1d4c3-97bd-49ed-ab1e-4a4445cdac00.png)

it works find on the site but anidl isn't finding it

**Comment by izu-co** [comment]
First of all please stick to the bug template. It is there for a reason (I need the information that is asked there).
Please check again that you are logged in and relogin if you are.

**Comment by shoyrock** [comment]
> First of all please stick to the bug template. It is there for a reason (I need the information that is asked there).
> Please check again that you are logged in and relogin if you are.

Yes I’m logged in the other episodes downloaded without the problem

**Comment by izu-co** [comment]
It works on my machine.
Also, please note that the tool hasn't found any English streams. Please make sure they are available in your region.

**Comment by shoyrock** [comment]
> It works on my machine.
> Also, please note that the tool hasn't found any English streams. Please make sure they are available in your region.

It’s wasn’t working before I tested yesterday was it still wasn’t, I just tried it after I read your message and it works fine now. Maybe it was a problem on funi side
