### ISSUE TITLE
BUG jpn audio not downloaded (--srz)

### ISSUE THREAD

**Issue by CMoranO** [anidl/multi-downloader-nx#230]
### Program version

last commit

### Service

Crunchyroll

### Command used

node index.js --service crunchy --srz 'GP5HJ800Z' --dubLang spa jpn --dlsubs es-419 -q 5 -e 9

### Show ID

GP5HJ800Z

### Episode

9

### Console Output

PS G:\Funimation\lib> node index.js --service crunchy --srz 'GP5HJ800Z' --dubLang spa jpn --dlsubs es-419 -q 5 -e 9

=== Multi Downloader NX 2.0.18 ===

[INFO] USER: undefined (*****@gmail.com)
[INFO] Your Country: **

[Z:GP5HJ800Z] SAKUGAN (Seasons: 7, EPs: 62) [SIMULCAST, SUB, DUB]
  [S:GYX0C4DD9] SAKUGAN (Portuguese Dub) (Season: 1) [SIMULCAST, DUB]
  [S:G649C733E] SAKUGAN (German Dub) (Season: 1) [SIMULCAST, DUB]
  [S:G69PC2XXP] SAKUGAN (Spanish Dub) (Season: 1) [SIMULCAST, DUB]
  [S:G6JQC1MM3] SAKUGAN (English Dub) (Season: 1) [SIMULCAST, DUB]
  [S:GR19CP330] SAKUGAN (French Dub) (Season: 1) [SIMULCAST, DUB]
  [S:GRNQCJZ8D] SAKUGAN (Season: 2) [SIMULCAST, SUB]
[E1] SAKUGAN - Season 1 - FATHERS & DAUGHTERS [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[E2] SAKUGAN - Season 1 - GOOD DAY, GOOD BYE [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[E3] SAKUGAN - Season 1 - BRAINS & HEARTS [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[E4] SAKUGAN - Season 1 - LADIES & GENTLEMEN [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[E5] SAKUGAN - Season 1 - NO WORK, NO LIFE [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[E6] SAKUGAN - Season 1 - JUSTICE FOR VILLAINS [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[E7] SAKUGAN - Season 1 - ON THE ROAD [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[E8] SAKUGAN - Season 1 - MEMORIES & REGRETS [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[E9] SAKUGAN - Season 1 - END OF VACATION [☆ Portuguese, ☆ German, ☆ Spanish, English, ☆ French]
[E10] SAKUGAN - Season 1 - OH MY TONY [☆ Portuguese, ☆ German, ☆ Spanish, ☆ English, ☆ French]
[E11] SAKUGAN - Season 2 - FATHERS & DAUGHTERS [Japanese]
[E12] SAKUGAN - Season 2 - GOOD DAY, GOOD BYE [Japanese]
[E13] SAKUGAN - Season 2 - BRAINS & HEARTS [Japanese]
[E14] SAKUGAN - Season 2 - LADIES & GENTLEMEN [Japanese]
[E15] SAKUGAN - Season 2 - NO WORK, NO LIFE [Japanese]
[E16] SAKUGAN - Season 2 - JUSTICE FOR VILLAINS [Japanese]
[E17] SAKUGAN - Season 2 - ON THE ROAD [Japanese]
[E18] SAKUGAN - Season 2 - MEMORIES & REGRETS [Japanese]
[E19] SAKUGAN - Season 2 - END OF VACATION [Japanese]
[E20] SAKUGAN - Season 2 - OH MY TONY [Japanese]
[E21] SAKUGAN - Season 2 - SOUND OF DREAM [Japanese]
[E22] SAKUGAN - Season 2 - TO BE CONTINUED [Japanese]

------------------------------

[S1E9] - END OF VACATION [✓ Spanish]
{
  data: [
    {
      mediaId: 'GPWUK5QMP',
      playback: 'https://pl.crunchyroll.com/asset/5a09a23f222c7008a24575da2f08d7de/v/bcda11d8a81926ecdfa0568d96925e13/languages/en-US?*&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9wbC5jcnVuY2h5cm9sbC5jb20vYXNzZXQvNWEwOWEyM2YyMjJjNzAwOGEyNDU3NWRhMmYwOGQ3ZGUvdi9iY2RhMTFkOGE4MTkyNmVjZGZhMDU2OGQ5NjkyNWUxMy8~KiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY0MzA5MzMxNH19fV19&Signature=WqBxrJIVzeMvSffSm2jtmMAEfWzC7Kd1yAKyMeU6F3Af7u1j6AkDIYh8tVZgW5vRyQeUQZETv4ZEOVq18iVjf4mYDJcY8Sp7Kv~B8Bo3mXT2VUVMWcyGbGk74WvFDffoBs-4KVfC39X9UIKeiX9e~bzKprDp7v1nUWpz5v7WJGU07g7lgLZleXAaWolV8yMvwWtatgZ1UQL~LP1UicxdPWDFYo3WUk5~k69Owx~wxVLP8XBDIHl936eKaSL~u61~oNu4glAaNUJDoUqAIH9E2HESR1JVlQO97eWzZx54JUZa53Whhhr2KuWQWWB0dr~HUBz9TlLxio1X51eDYt5OGA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA',
      lang: [Object]
    }
  ],
  seasonTitle: 'SAKUGAN',
  episodeNumber: '9',
  episodeTitle: 'END OF VACATION',
  seasonID: 'G69PC2XXP',
  season: 1
}
[INFO] Requesting: [GPWUK5QMP] SAKUGAN - 9 - END OF VACATION
[INFO] Selecting raw stream
[INFO] Full stream found! (✓1: adaptive_hls/spa/- )
[INFO] Full stream found! ( 2: download_hls/spa/- )
[INFO] Full stream found! ( 3: vo_adaptive_hls/spa/- )
[INFO] Downloading video...
[INFO] Playlists URL: https://pl.crunchyroll.com/evs1/bcda11d8a81926ecdfa0568d96925e13/assets/5a09a23f222c7008a24575da2f08d7de_,4264167.mp4,4264168.mp4,4264166.mp4,4264164.mp4,4264165.mp4,4264163.mp4,.urlset/master.m3u8?Expires=1643096492&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9iY2RhMTFkOGE4MTkyNmVjZGZhMDU2OGQ5NjkyNWUxMy9hc3NldHMvNWEwOWEyM2YyMjJjNzAwOGEyNDU3NWRhMmYwOGQ3ZGVfLDQyNjQxNjcubXA0LDQyNjQxNjgubXA0LDQyNjQxNjYubXA0LDQyNjQxNjQubXA0LDQyNjQxNjUubXA0LDQyNjQxNjMubXA0LC51cmxzZXQvbWFzdGVyLm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDMwOTY0OTJ9fX1dfQ__&Signature=BQMEjeiVxcBseeTAV8eV2fL83i6rBtG6sOovMXb3dEjjJpUNckstQvLImbxmr36ROXRNORGEzma6tHr1Dk8YIL9aqPO1bO7bfMZZO~xEkM4mrInsFMDbFjJWT4tgY9xx12bTLz2WPWbIxCumOWqdxeJrXe972YQ-aFaLS5MwF6ON-s8M31ZyFZGypR3dyZgq~hqL5dNgE2bHIxlgwi7WOvuyP7soejoVijaJlQ9IetLUKCw-dZREslZD36zWSFSqGfElmUtXRCTfEXAzOn6ZsVj7pldIKf-0zGR7y0cXUgd85saZkkhFWaKkBDx-vdKC3uyVxZb0bXDoCsO1lKGSUQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA (adaptive_hls/spa/-)
[INFO] Servers available:
        pl.crunchyroll.com (ll-prod)
        pl.crunchyroll.com (fy-prod)
[INFO] Available qualities:
        [1] 144x80 (191KiB/s)
        [2] 428x240 (549KiB/s)
        [3] 640x360 (1068KiB/s)
        [4] 848x480 (2042KiB/s)
        [5] 1280x720 (4022KiB/s)
        [6] 1920x1080 (7915KiB/s)
[INFO] Selected quality: 1280x720 @ pl.crunchyroll.com (ll-prod)
[INFO] Output filename: [CR] SAKUGAN - S01E09 [720p].Spanish
[INFO] Total parts in stream: 710 (71*10)
[INFO] Saving stream to «G:\Funimation\lib\videos\[CR] SAKUGAN - S01E09 [720p].Spanish.ts»...
[INFO] 10 of 710 parts downloaded [1%] (1m30s | 11Mb/s)
[INFO] 20 of 710 parts downloaded [3%] (1m16s | 14Mb/s)
[INFO] 30 of 710 parts downloaded [4%] (1m11s | 14Mb/s)
[INFO] 40 of 710 parts downloaded [6%] (1m07s | 15Mb/s)
[INFO] 50 of 710 parts downloaded [7%] (1m04s | 15Mb/s)
[INFO] 60 of 710 parts downloaded [8%] (1m00s | 15Mb/s)
[INFO] 70 of 710 parts downloaded [10%] (1m03s | 14Mb/s)
[INFO] 80 of 710 parts downloaded [11%] (1m01s | 14Mb/s)
[INFO] 90 of 710 parts downloaded [13%] (1m00s | 14Mb/s)
[INFO] 100 of 710 parts downloaded [14%] (59s | 15Mb/s)
[INFO] 110 of 710 parts downloaded [15%] (58s | 15Mb/s)
[INFO] 120 of 710 parts downloaded [17%] (57s | 15Mb/s)
[INFO] 130 of 710 parts downloaded [18%] (55s | 15Mb/s)
[INFO] 140 of 710 parts downloaded [20%] (53s | 15Mb/s)
[INFO] 150 of 710 parts downloaded [21%] (51s | 15Mb/s)
[INFO] 160 of 710 parts downloaded [23%] (50s | 15Mb/s)
[INFO] 170 of 710 parts downloaded [24%] (47s | 15Mb/s)
[INFO] 180 of 710 parts downloaded [25%] (45s | 15Mb/s)
[INFO] 190 of 710 parts downloaded [27%] (44s | 15Mb/s)
[INFO] 200 of 710 parts downloaded [28%] (42s | 15Mb/s)
[INFO] 210 of 710 parts downloaded [30%] (41s | 15Mb/s)
[INFO] 220 of 710 parts downloaded [31%] (40s | 15Mb/s)
[INFO] 230 of 710 parts downloaded [32%] (39s | 15Mb/s)
[INFO] 240 of 710 parts downloaded [34%] (38s | 15Mb/s)
[INFO] 250 of 710 parts downloaded [35%] (37s | 15Mb/s)
[INFO] 260 of 710 parts downloaded [37%] (37s | 15Mb/s)
[INFO] 270 of 710 parts downloaded [38%] (36s | 15Mb/s)
[INFO] 280 of 710 parts downloaded [39%] (35s | 15Mb/s)
[INFO] 290 of 710 parts downloaded [41%] (34s | 15Mb/s)
[INFO] 300 of 710 parts downloaded [42%] (33s | 15Mb/s)
[INFO] 310 of 710 parts downloaded [44%] (32s | 15Mb/s)
[INFO] 320 of 710 parts downloaded [45%] (31s | 15Mb/s)
[INFO] 330 of 710 parts downloaded [46%] (30s | 15Mb/s)
[INFO] 340 of 710 parts downloaded [48%] (29s | 15Mb/s)
[INFO] 350 of 710 parts downloaded [49%] (28s | 15Mb/s)
[INFO] 360 of 710 parts downloaded [51%] (27s | 15Mb/s)
[INFO] 370 of 710 parts downloaded [52%] (26s | 15Mb/s)
[INFO] 380 of 710 parts downloaded [54%] (26s | 15Mb/s)
[INFO] 390 of 710 parts downloaded [55%] (25s | 15Mb/s)
[INFO] 400 of 710 parts downloaded [56%] (24s | 15Mb/s)
[INFO] 410 of 710 parts downloaded [58%] (23s | 15Mb/s)
[INFO] 420 of 710 parts downloaded [59%] (22s | 15Mb/s)
[INFO] 430 of 710 parts downloaded [61%] (21s | 15Mb/s)
[INFO] 440 of 710 parts downloaded [62%] (20s | 15Mb/s)
[INFO] 450 of 710 parts downloaded [63%] (19s | 15Mb/s)
[INFO] 460 of 710 parts downloaded [65%] (19s | 15Mb/s)
[INFO] 470 of 710 parts downloaded [66%] (18s | 15Mb/s)
[INFO] 480 of 710 parts downloaded [68%] (17s | 15Mb/s)
[INFO] 490 of 710 parts downloaded [69%] (16s | 15Mb/s)
[INFO] 500 of 710 parts downloaded [70%] (16s | 15Mb/s)
[INFO] 510 of 710 parts downloaded [72%] (15s | 15Mb/s)
[INFO] 520 of 710 parts downloaded [73%] (14s | 15Mb/s)
[INFO] 530 of 710 parts downloaded [75%] (13s | 15Mb/s)
[INFO] 540 of 710 parts downloaded [76%] (12s | 15Mb/s)
[INFO] 550 of 710 parts downloaded [77%] (12s | 15Mb/s)
[INFO] 560 of 710 parts downloaded [79%] (11s | 15Mb/s)
[INFO] 570 of 710 parts downloaded [80%] (10s | 15Mb/s)
[INFO] 580 of 710 parts downloaded [82%] (9s | 15Mb/s)
[INFO] 590 of 710 parts downloaded [83%] (8s | 15Mb/s)
[INFO] 600 of 710 parts downloaded [85%] (8s | 15Mb/s)
[INFO] 610 of 710 parts downloaded [86%] (7s | 15Mb/s)
[INFO] 620 of 710 parts downloaded [87%] (6s | 15Mb/s)
[INFO] 630 of 710 parts downloaded [89%] (6s | 15Mb/s)
[INFO] 640 of 710 parts downloaded [90%] (5s | 15Mb/s)
[INFO] 650 of 710 parts downloaded [92%] (4s | 15Mb/s)
[INFO] 660 of 710 parts downloaded [93%] (4s | 15Mb/s)
[INFO] 670 of 710 parts downloaded [94%] (3s | 15Mb/s)
[INFO] 680 of 710 parts downloaded [96%] (2s | 15Mb/s)
[INFO] 690 of 710 parts downloaded [97%] (1s | 15Mb/s)
[INFO] 700 of 710 parts downloaded [99%] (1s | 15Mb/s)
[INFO] 710 of 710 parts downloaded [100%] (0s | 15Mb/s)
[WARN] Can't find urls for subtitles!

> "mkvmerge" -o "G:\Funimation\lib\videos\[CR] SAKUGAN - S01E09 [720p].mkv" --no-date --disable-track-statistics-tags --engage no_variable_data --video-tracks 0 --audio-tracks 1 --track-name 0:"Spanish [Uncut]" --track-name 1:"Spanish [Uncut]" --language 1:spa "G:\Funimation\lib\videos\[CR] SAKUGAN - S01E09 [720p].Spanish.ts" --no-subtitles --no-attachments
mkvmerge v61.0.0 ('So') 64-bit
'G:\Funimation\lib\videos\[CR] SAKUGAN - S01E09 [720p].Spanish.ts': Using the demultiplexer for the format 'MPEG transport stream'.
'G:\Funimation\lib\videos\[CR] SAKUGAN - S01E09 [720p].Spanish.ts' track 0: Using the output module for the format 'AVC/H.264 (unframed)'.
'G:\Funimation\lib\videos\[CR] SAKUGAN - S01E09 [720p].Spanish.ts' track 1: Using the output module for the format 'AAC'.
The file 'G:\Funimation\lib\videos\[CR] SAKUGAN - S01E09 [720p].mkv' has been opened for writing.
'G:\Funimation\lib\videos\[CR] SAKUGAN - S01E09 [720p].Spanish.ts' track 0: Extracted the aspect ratio information from the video bitstream and set the display dimensions to 1280/720.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 7 seconds.

### Additional Information

```Text
Good morning, thank you for your work. After #226 fix I'm facing this problem, series name is correct but japanese audio is not present.

Output files:

[CR] SAKUGAN - S02E09 [720p].mkv (spa audio)

"--allDubs" option presents the same error.
```

**Comment by izu-co** [comment]
I am sorry, but there is nothing I can do about it.
Crunchyroll has labeled the jap version as season 2 and therefor the tool picks it up as season 2. This problem is on funimations side.
