### ISSUE TITLE
English subtitle 

### ISSUE THREAD

**Issue by rudesniper44444** [anidl/multi-downloader-nx#233]
### Program version

2.0.15

### Service

Funimation

### Command used

  .\aniDL.exe --service funi -s 29716 -q1 --dubLang eng --dlsubs en --hslang en -e 1

### Show ID

29716 

### Episode

1

### Console Output

i just wanna know how i can download both subbed and dubbed in English  from **Funimation** website , i tried to download soft and hard English subtitles with English dubbed but i couldn't , i can only choice one whether it's dubbed or subbed . is it possible to download both ? does anyone know ? 

`.\aniDL.exe --service funi -s 29716 -q1 --dubLang eng --dlsubs en --hslang en -e 1`

**Comment by izu-co** [comment]
Please take a look at the [documentation for `--hslang`](https://github.com/anidl/multi-downloader-nx/blob/master/docs/DOCUMENTATION.md#--hslang). As you can see, this option only applies to crunchyroll. By the way, for me, subbed is `jap` audio with `eng` subtitles. You can download both `jap` and `eng` audio by typing `--dubLang eng jap`.

**Comment by rudesniper44444** [comment]
> Please take a look at the [documentation for `--hslang`](https://github.com/anidl/multi-downloader-nx/blob/master/docs/DOCUMENTATION.md#--hslang). As you can see, this option only applies to crunchyroll. By the way, for me, subbed is `jap` audio with `eng` subtitles. You can download both `jap` and `eng` audio by typing `--dubLang eng jap`.

thank you so much for your help but , is there anyway i can download English dubbed with the English caption , because downloading eng/jpn dubbed with english subtitle its different from what actually is saying in anime , 

so is there any options that i can download english dubbed with english caption ??

and thanks again for ur help .
