### ISSUE TITLE
not a bug Just an inquiry

### ISSUE THREAD

**Issue by rudesniper44444** [anidl/multi-downloader-nx#234]
### Program version

2.0.15

### Service

Funimation

### Command used

  .\aniDL.exe --service funi -s 29716 -q1 --dubLang eng --dlsubs en -e 1

### Show ID

29716 

### Episode

1

### Console Output

@izu-co sorry to disturb you again but i have just one more question please , 

can I download English dubbed with the English caption , because downloading eng/jpn dubbed with english subtitle its different from what actually is saying in anime 

so is there any options that i can download english dubbed with english caption ??

and thank you so much for ur help .

**Comment by izu-co** [comment]
There are two types of subtitles. If you download English dub and have eng included in your dlsubs, you only get the CC subtitles. If you download the Japanese dub as well, you get the OC subtitles.

**Comment by rudesniper44444** [comment]
> There are two types of subtitles. If you download English dub and have eng included in your dlsubs, you only get the CC subtitles. If you download the Japanese dub as well, you get the OC subtitles.

`.\aniDL.exe --service funi -s 29716 -q1 --dubLang eng --dlsub en  -e 4`


yes , I tried it again and i released that there is something wrong with this anime in particular

**Fullmetal Alchemist: Brotherhood , -s 29716** 

the script can't detect the CC in this anime 

![image](https://user-images.githubusercontent.com/97499870/151316518-9bf253f1-43b7-42a8-a209-4e5b2a0a89ad.png)


also it doesn't work with **My Hero Academia**  ,  Demon Slayer: Kimetsu no Yaiba

![image](https://user-images.githubusercontent.com/97499870/151318646-1699edd9-016d-4075-a086-c536771b6e1a.png)

![image](https://user-images.githubusercontent.com/97499870/151319314-fb52266d-9e7b-4bc4-b5a6-3a4edd58c1c3.png)



but it works normally **one piece** the script detect the CC
![image](https://user-images.githubusercontent.com/97499870/151317858-f2893231-4bac-4195-8758-1ce0c1bc6334.png)


is there any solutions for this ? , do you know if its possible to fix this in the script or i can download an external extension to download the CC to fix this purpose only . and thanks a lot
