### ISSUE TITLE
the script can't detect the English subtitle 

### ISSUE THREAD

**Issue by rudesniper44444** [anidl/multi-downloader-nx#236]
### Program version

2.0.15

### Service

Funimation

### Command used

 .\aniDL.exe --service funi -s 20224 -q1 --dubLang eng jpn --sublang en --hslang en -e 1

### Show ID

1

### Episode

1

### Console Output

.\aniDL.exe --service funi -s 29716 -q1 --dubLang eng --dlsub en -e 4

yes , I tried it again and i released that there is something wrong with this anime in particular

Fullmetal Alchemist: Brotherhood , -s 29716

the script can't detect the CC in this anime
![image](https://user-images.githubusercontent.com/97499870/151663407-3d87a6f4-0b41-4d29-8c29-390f70d8b917.png)

![image](https://user-images.githubusercontent.com/97499870/151537063-428ca9ab-7197-4fea-8ae3-428d11b9e1b7.png)
![image](https://user-images.githubusercontent.com/97499870/151663303-fb373f9e-7646-4451-8ddf-8ef7ab2589aa.png)

but it works normally with **one piece** the script detect the CC
image

![image](https://user-images.githubusercontent.com/97499870/151537239-612eab47-9ac2-44fb-ab06-a501daa40717.png)

is there any solutions for this ? , do you know if its possible to fix this in the script or i can download an external extension to download the CC to fix this purpose only .please i need help from anyone and thanks a lot

**Comment by izu-co** [comment]
Are you sure that the command given is the command you used. In the given command you requested both eng and jap audio, yet in the image only English is downloaded.

**Comment by rudesniper44444** [comment]
> Are you sure that the command given is the command you used. In the given command you requested both eng and jap audio, yet in the image only English is downloaded.

no i don't use this command

**Comment by izu-co** [comment]
Some shows might not have English CC subtitles.

**Comment by izu-co** [comment]
Please try again with the newest commit.
