### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by levaculik2** [anidl/multi-downloader-nx#237]
### Program version

Multi Downloader NX 2.0.18

### Service

Crunchyroll

### Command used

node index.js --service "crunchy" --auth

### Show ID

no ID

### Episode

no Episode

### Console Output

=== Multi Downloader NX 2.0.18 ===

[Q] LOGIN/EMAIL: **********@gmail.com
[Q] PASSWORD   : *******
[ERROR] HTTPError 401: Unauthorized
[ERROR] Body: {"code":"auth.obtain_access_token.invalid_credentials","context":[],"error":"invalid_grant"}
[ERROR] Authentication failed!

whenever I try to authenticate it is giving this error.

I'm having the same error when I try to use the other tool  "crunchyroll-downloader-nx-5.3.1"

=== Crunchyroll Downloader NX 5.3.1 ===

[INFO] Authentication
[Q] LOGIN/EMAIL: ***************@gmail.com
[Q] PASSWORD   : ***********
[INFO] Cookies were updated! (c_visitor, session_id)

[ERROR] Auth Error:
[ERROR] Bad captcha. Please resubmit.

### Additional Information

```Text
I've always used it and never had a problem with both tools, but since this morning it's been giving this error. Last week it got this error, but then it works again.
I got to do a test with the vpn on to see if it worked and it didn't work either, it keeps giving the same error.
```

**Comment by izu-co** [comment]
You could try to log in on Crunchyroll. The tool can't display captchas and therefore can't solve them. You have to ensure that there is no need to solve a captcha.
