### ISSUE TITLE
aniDL v2.0.18 when downloading all dubs has series name "undefined"

### ISSUE THREAD

**Issue by sww724** [anidl/multi-downloader-nx#238]
### Program version

2.0.18

### Service

Crunchyroll

### Command used

aniDL --service crunchy --srz GQWH0M455 --fileName "crunchy\..PlayingNow\Don't Toy with Me, Miss Nagatoro! Series\${showTitle}\Season ${season}\Episode ${episode} - ${title}" --allDubs true --dlsubs "all" -e 1-3

### Show ID

GQWH0M455

### Episode

1-3

### Console Output

When just getting the dub episodes by language, each language goes into "showTitle (Language DUB)" directory, but when using --srz to get all dubs muxed down to one file there isn't a clear directory name. Might want to catch this condition and use "showTitle (All DUBS)"

**Comment by izu-co** [comment]
d25fbe4f1cc0fdee285317aa05d6b4084a53d64e should have fixed said issue. It hasn't been made into a release yet.

**Comment by izu-co** [comment]
Fixed as the commit has been released in the `3.0.0` release.
