### ISSUE TITLE
error downloading premium episodes

### ISSUE THREAD

**Issue by levaculik2** [anidl/multi-downloader-nx#248]
### Program version

Multi Downloader NX 2.0.18

### Service

Crunchyroll

### Command used

node index.js  --service crunchy -s G675CD5Z2 -e 05 --dubLang "jpn" -q "0" --dlsubs "all" --mp4

### Show ID

G675CD5Z2

### Episode

04/05

### Console Output

node index.js  --service crunchy -s G675CD5Z2 -e 04 --dubLang "jpn" -q "0" --dlsubs "all" --mp4

=== Multi Downloader NX 2.0.18 ===

[INFO] USER: ToughFly (anaajuanita@gmail.com)
[INFO] Your Country: BR

[S:G675CD5Z2] SABIKUI BISCO (Season: 1) [SIMULCAST, SUB]
  [01|E:G50UZ4JJ9] 1 - The Man Worth 800,000 [23m40s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [02|E:GWDU8KNNX] 2 - Soar on King Trumpets [23m40s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [03|E:GG1U2E778] 3 - Tag Team [23m40s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
 ✓[04|E:G0DUN0QQ8] 4 - Ride the Crab [23m40s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [05|E:GEVUZG55N] ☆ 5 - Children's Fortress [23m40s, SUB]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en

[INFO] Requesting: [G0DUN0QQ8] SABIKUI BISCO - 4 - Ride the Crab
[INFO] Selecting raw stream
[INFO] Full stream found! (✓1: adaptive_hls/jpn/- )
[INFO] Full stream found! ( 2: download_hls/jpn/- )
[INFO] Full stream found! ( 3: vo_adaptive_hls/jpn/- )
[INFO] Downloading video...
[INFO] Playlists URL: https://pl.crunchyroll.com/evs1/0c3195c3805d4f982e5ffec495ffb1e3/assets/dfb50918a3026b7c63d37fa75bf03e0e_,4283209.mp4,4283210.mp4,4283208.mp4,4283206.mp4,4283207.mp4,4283205.mp4,.urlset/master.m3u8?Expires=1644551658&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS8wYzMxOTVjMzgwNWQ0Zjk4MmU1ZmZlYzQ5NWZmYjFlMy9hc3NldHMvZGZiNTA5MThhMzAyNmI3YzYzZDM3ZmE3NWJmMDNlMGVfLDQyODMyMDkubXA0LDQyODMyMTAubXA0LDQyODMyMDgubXA0LDQyODMyMDYubXA0LDQyODMyMDcubXA0LDQyODMyMDUubXA0LC51cmxzZXQvbWFzdGVyLm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDQ1NTE2NTh9fX1dfQ__&Signature=n2rha~G-tvAsUXgK8mJu8sf20ON-CR8q8Qb9slObmGOJ94xVCf1LW1vT3GIHC5PrEhc-rpYJezp3Q7yHOKVtq8K0XtNqv6DMsW1yPJE6FoSSl5nBklCIYfiW1jD5nKHUmZZARJLJRki3HUXIYQKNiui-HrVIBo2lZh1TgmEcdp0AzCBoV8T-MrKYG9HOZqCFwUGx5Cxhd9yvez6gmbjgoSYakL8SxEnswoi2IC5yrrYjXOm3s8a5iVPxVd1VOw3I0BEdFoJFqvx5bfECuxtZYpqkFnJ8VDgJjTFp1nQPoRj6-hcUO4s1f9OOdj5-x5OhyQWEHcBb-vCoe2eYLUfGlg__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA (adaptive_hls/jpn/-)
[INFO] Servers available:
	pl.crunchyroll.com (ll-prod)
	pl.crunchyroll.com (fy-prod)
[INFO] Available qualities:
	[1] 144x80 (191KiB/s)
	[2] 428x240 (549KiB/s)
	[3] 640x360 (1068KiB/s)
	[4] 848x480 (2044KiB/s)
	[5] 1280x720 (4017KiB/s)
	[6] 1920x1080 (7920KiB/s)
[INFO] Selected quality: 1920x1080 @ pl.crunchyroll.com (ll-prod)
[INFO] Output filename: [CR] SABIKUI BISCO - S01E04 [1080p].Japanese
[INFO] Total parts in stream: 710 (71*10)
[INFO] Saving stream to «/media/levaculik/HDNovo/animes/[CR] SABIKUI BISCO - S01E04 [1080p].Japanese.ts»...

___________________________________________________________________________________________________________________________________

node index.js  --service crunchy -s G675CD5Z2 -e 05 --dubLang "jpn" -q "0" --dlsubs "all" --mp4

=== Multi Downloader NX 2.0.18 ===

[INFO] USER: ToughFly (anaajuanita@gmail.com)
[INFO] Your Country: BR

[S:G675CD5Z2] SABIKUI BISCO (Season: 1) [SIMULCAST, SUB]
  [01|E:G50UZ4JJ9] 1 - The Man Worth 800,000 [23m40s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [02|E:GWDU8KNNX] 2 - Soar on King Trumpets [23m40s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [03|E:GG1U2E778] 3 - Tag Team [23m40s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [04|E:G0DUN0QQ8] 4 - Ride the Crab [23m40s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [05|E:GEVUZG55N] ☆ 5 - Children's Fortress [23m40s, SUB]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en

[INFO] Episodes not selected!
![errormulti01](https://user-images.githubusercontent.com/57818248/153119242-55162b3d-9eca-45f6-8742-17e953e1f38a.png)
![errormulti02](https://user-images.githubusercontent.com/57818248/153119245-afe60728-ac02-4290-9a8b-585957124366.png)

### Additional Information

```Text
I'm having trouble downloading the premium episodes that have just been released. The funniest thing that doesn't show any error at all, it just gives the message that no episode was selected, then when I select another episode without being premiun it downloads normally.
follow images
```

**Comment by izu-co** [comment]
Please try to reauthenticate and check that you indeed have a premium account.

**Comment by izu-co** [comment]
Closed due to inactivity. Feel free to reopen with new information at any time.
