### ISSUE TITLE
[Feature] Adding OLD RSS (Redirect to beta)

### ISSUE THREAD

**Issue by ArturiaPendragon** [anidl/multi-downloader-nx#249]
### Program version

2.0.18

### Service

Crunchyroll

### Command used

--service crunchy -e 824319--dlsubs fr --tsparts 15 -q 0 --fileName "file.1080p" --nomux --mp4 -a Refrain --page-locale "fr-FR" --partsize 15 --kstream 7 -x 1

### Show ID

GQWH0M90V

### Episode

5

### Console Output

```
=== Multi Downloader NX 2.0.18 ===

[INFO] USER: xxxxxx
[INFO] Your Country: FR

[INFO] Requested object ID: 824319
[ERROR] HTTPError 404: Not Found
[ERROR] Objects Request FAILED!
[INFO] Body: {
        "__class__": "error",
        "__href__": "",
        "__links__": {},
        "__actions__": {},
        "type": "Not Found",
        "code": "404",
        "message": "Invalid object identifier",
        "context": {}
}
```

### Additional Information

```Text
Hello, I use your old project using the old API of Crunchyroll (using their RSS, which I can't find in their beta version by the way).

So I was using this command in old version :

`nodejs /home/anubis/crunchyroll-downloader-nx/crunchy.js -e 824319 --dlsubs fr --tsparts 15 -q max --filename "file.1080p" --nomux --mp4 -a Refrain --page-locale "fr-FR"`

Would it be possible to add a function that for example could redirect the RSS page (Example: https://www.crunchyroll.com/fr/life-with-an-ordinary-guy-who-reincarnated-into-a-total-fantasy-knockout/episode-5-a-guy-who-reincarnated-as-a-fantasy-knockout-and-armor-that-moves-824319) and redirect us to the page in beta (Example: https://beta.crunchyroll.com/fr/watch/GVWU0ZV0X/a-guy-who-reincarnated-as-a-fantasy-knockout-and-armor-that-moves)

`./aniDL --service crunchy -e GVWU0ZV0X --dlsubs fr --tsparts 15 -q 0 --fileName "file.1080p" --nomux --mp4 -a Refrain --page-locale "fr-FR" --partsize 15 --kstream 7 -x 1`

Thanks in advance !
```

**Comment by izu-co** [comment]
I failed to see how that would be useful. If you search with the beta api like you would with the old one you would get the ID to use?

**Comment by ArturiaPendragon** [comment]
I do not use the function to search, I use Bash scripts to get URL given by RSS for Crunchyroll (which is not the beta URL at the moment), so it is not possible to add the redirect?

**Comment by izu-co** [comment]
I don't know if its possible to be honest. The crunchy api has been build by anidl and while I know enough to make changes to it, I have no clue about the underlying architecture.

**Comment by ArturiaPendragon** [comment]
And wouldn't it be possible to simply add a curl to get the episode id? 

We don't need the crunchy api to have the redirection, just that the account is in beta and to pass him the cookies. 

But i can do it because i have cloudflare stop me :(
