### ISSUE TITLE
BUG - CLI Help page now empty? 

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [anidl/multi-downloader-nx#259]
### Program version

3.0.0

### Service

Both

### Command used

node ~/Apps/Animie/anidl/multi-downloader-nx/lib/index.js --service funi

### Show ID

N/A

### Episode

N/A

### Console Output

```text
❯ funi --help

=== Multi Downloader NX 3.0.0 ===

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
```
![Screen Shot 2022-02-17 at 8 14 23 am](https://user-images.githubusercontent.com/2242880/154358577-b655563a-3259-4c29-8b05-f5a19b40ec3c.jpg)

### Additional Information

```Text
I'm running the one built from source via "npm run tsc"
```

**Comment by izu-co** [comment]
I will investigate this as well. Can you confirm if the tool is unsable?

**Comment by XxUnkn0wnxX** [comment]
> I will investigate this as well. Can you confirm if the tool is usable?

ya I think it does I did a search query & gave results.. just help page hidden

**Comment by izu-co** [comment]
Another quick question: you said you build it from source, so is `funi` an alias for `node index.js`?

And you have just run `npm run tsc` without any arguments, correct?

**Comment by XxUnkn0wnxX** [comment]
> Another quick question: you said you build it from source, so is `funi` an alias for `node index.js`?
> 
> And you have just run `npm run tsc` without any arguments, correct?

ya I run it without anything, I wasn't aware there were any arguments for it?

**Comment by izu-co** [comment]
There are:
 The first one is for testing - if set to `test` `node_modules` and `.env` files get copied.
 The second one is if you want to build the gui - can only be set to `false`, `true` otherwise.
 
 So please try to build with `npm run tsc false false` although the gui cli `should` have a help

**Comment by izu-co** [comment]
Btw on Windows I get the help message, so I have no clue what's up with mac

**Comment by XxUnkn0wnxX** [comment]
running `npm run tsc false false` did not help, the help page still has nothing
also, I'm running node version v17.5.0, npm version: 8.5.0

running `build-macos-cli` which gives me the CLI binary gives me help page, but all the source methods gives me nothing but a blank.

also whenever I switch builds like `npm run tsc` to `npm run build-macos-gui` or in this case to `npm run tsc false false`
it fails on the removing lib step.
```text
❯ npm run tsc false false

> multi-downloader-nx@3.0.0 tsc
> ts-node tsc.ts "false" "false"

Removing lib dir... Error: ENOTEMPTY: directory not empty, rmdir 'lib/node_modules/rxjs'
    at Object.rmdirSync (node:fs:1167:10)
    at _rmdirSync (node:internal/fs/rimraf:260:21)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7) {
  errno: -66,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: 'lib/node_modules/rxjs'
}
```
```text
Removing lib dir... Error: ENOTEMPTY: directory not empty, rmdir 'lib'
    at Object.rmdirSync (node:fs:1167:10)
    at _rmdirSync (node:internal/fs/rimraf:260:21)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at Object.rmSync (node:fs:1216:10)
    at removeSync (/Users/Admin/Apps/Animie/anidl/multi-downloader-nx/node_modules/fs-extra/lib/remove/index.js:15:28)
    at /Users/Admin/Apps/Animie/anidl/multi-downloader-nx/tsc.ts:56:13
    at step (/Users/Admin/Apps/Animie/anidl/multi-downloader-nx/tsc.ts:33:23)
    at Object.next (/Users/Admin/Apps/Animie/anidl/multi-downloader-nx/tsc.ts:14:53)
    at /Users/Admin/Apps/Animie/anidl/multi-downloader-nx/tsc.ts:8:71
    at new Promise (<anonymous>) {
  errno: -66,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: 'lib'
}
```

**Comment by XxUnkn0wnxX** [comment]
Ok, I found the issue..
running `node ~/Apps/Animie/anidl/multi-downloader-nx/lib/index.js --service funi --help` doesn't give me a help page
running `node ~/Apps/Animie/anidl/multi-downloader-nx/lib/index.js --help` does 

same thing if run in the root dir `node index.js --service funi --help` gives me nothing

**Comment by izu-co** [comment]
Should be fixed with the newest commit, as `--help` will now ALWAYS display the help even if there is a valid command entered.
