### ISSUE TITLE
Add build instructions in README

### ISSUE THREAD

**Issue by DatCrazyDelphox** [anidl/multi-downloader-nx#262]
It's more a quality-of-life change with the objective to help building the app directly from git for creating PKGBUILDs and packages to other distros

**Comment by izu-co** [comment]
Yes that would be nice. I will add it tomorrow.

Are there any distros you have in mind?

**Comment by DatCrazyDelphox** [comment]
I think build instructions for three of the major ones, like debian/Ubuntu, Fedora and Arch would be enough for now

Also, thanks for the fast response

**Comment by izu-co** [comment]
Just wanted to add that I've written tomorrow but I’m reality it’s whenever I have time for it.

This should be done by the end of the weekend at most.

**Comment by izu-co** [comment]
9d8488ff2463e94e5b42470172ea3d39868c80a1
