### ISSUE TITLE
Absolutely no output

### ISSUE THREAD

**Issue by zeroreality** [anidl/multi-downloader-nx#263]
```
d:\Downloads\Funimation\lib>node funi.js --search hero

d:\Downloads\Funimation\lib>
```

I haven't used NodeJS before, but I was able to figure out getting npm and typescript installed.  However, now when I try to use any CLI command (not just search) I get no output and no error.

Any ideas?

(Also, I am very hopeful that this tool works, thanks for making it.)

**Comment by izu-co** [comment]
You have to use ˋnode index.jsˋ

**Comment by zeroreality** [comment]
pffft lol ok, that worked!

I think the CLI reference is fine, but it needs some examples for each of the options available.

**Comment by izu-co** [comment]
https://github.com/anidl/multi-downloader-nx/blob/master/docs/DOCUMENTATION.md
