### ISSUE TITLE
"I'm getting this error what should i do now" HTTPError 403: FORBIDDEN

### ISSUE THREAD

**Issue by bharathbunny126** [anidl/multi-downloader-nx#268]
![2022-02-28](https://user-images.githubusercontent.com/71566689/155945655-9e4204d5-e899-45c6-8815-fee0dd9b4496.png)
[INFO] Selected Episodes : 0083

[INFO] Attack on Titan - S5E83 - Pride
[INFO] Available streams (Non-Encryted):
[#4115941] Japanese [Simulcast] (selected) (using 'English', 'Spanish', 'Portugese' for subtitles)
[ERROR] HTTPError 403: FORBIDDEN

**Comment by izu-co** [comment]
Some episodes might require a premium account
