### ISSUE TITLE
[GUI] BUG Error occurred in handler for 'downloadItem'

### ISSUE THREAD

**Issue by FaceHiddenInsideTheDark** [anidl/multi-downloader-nx#272]
### Program version

3.0.2

### Service

Both

### Command used

[GUI]

### Show ID

4036736

### Episode

,7,8
7,8 
7-8

### Console Output
```
Error occurred in handler for 'downloadItem': Error: ENOENT, config\archive.json not found in C:\Users\W\AppData\Local\Programs\multi-downloader-nx\resources\app.asar
    at createError (node:electron/js2c/asar_bundle:5:1243)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1962)
    at Object.writeFileSync (node:fs:2153:35)
    at addToArchive (C:\Users\W\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\modules\module.downloadArchive.js:113:8)
    at downloaded (C:\Users\W\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\modules\module.downloadArchive.js:121:9)
    at Funi.<anonymous> (C:\Users\W\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\funi.js:706:69)
    at step (C:\Users\W\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\funi.js:67:23)
    at Object.next (C:\Users\W\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\funi.js:48:53)
    at fulfilled (C:\Users\W\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\funi.js:39:58) {
  code: 'ENOENT',
  errno: -2
}
```

### Additional Information

Program works at startup with a fresh command, downloads first episode perfectly the first time, but should you wish to do multiple episodes, it does not carry out the command. If you try to manually input the next episode exclusively after the first episode, the above error is logged, and the command is not carried out. I tried 3 different episode strings all yielding the same problem "7,8" ",7,8" and "7-8" none of them downloaded both episodes.  The program does not allow for a different show to be called afterwards either; say I download an episode of show A and then want to go to show B, I have to manually restart the program ending the task and starting it again between each cycle ("force reload" isn't enough.) "DOWNLOAD ALL" also does not work and spits the same error as above after the first episode completes. "DOWNLOAD ALL BUT" and selecting every episode of the series but the two I want, also only downloads the first of the two.

**Comment by FaceHiddenInsideTheDark** [comment]
The "Report a Bug" feature seems to be messed up, and won't let me submit a labeled, assigned bug report.

**Comment by izu-co** [comment]
> The "Report a Bug" feature seems to be messed up, and won't let me submit a labeled, assigned bug report.

Fixed. Thanks for the report.

**Comment by izu-co** [comment]
As for the reset. I will investigate now, but I've I don't respond, please know that I am on vacation for one week and therefor I can't work on the project.

**Comment by FaceHiddenInsideTheDark** [comment]
Vielen dank. Ich kann versuchen, das Problem selbst zu beheben und einen Pull-Request senden. Ruhe gut mein Freund.

**Comment by izu-co** [comment]
Wenn bis morgen nichts von mir hörst, leg ich es in deine Hände

**Comment by izu-co** [comment]
Dein Problem sollte mit dem neusten commit behoben sein. 
Eigentlich sind es sogar zwei Fehler gewesen:
 - Funimation has a false episode number -> It downloaded the requested items but showed it has `1` and `2`.
 - A file has been configured with the wrong path which led to the crash.
 
Hier in Englisch damit auch andere wissen was wir besprechen :).

Wenn du aber noch andere Sachen hast du hinzufügen oder beheben willst freue ich mich immer über Pull-Requests.
