### ISSUE TITLE
Question about downloading multiple dubs

### ISSUE THREAD

**Issue by f4rf1x** [anidl/multi-downloader-nx#274]
When I download shows with more than a dub, it downloads perfectly but always the default audio is japanese and default subs are set to english. Is there a way to change that behavior of the app, so I can select another language as default instead of japanese?

**Comment by izu-co** [comment]
Change the entries in the cli-default file

https://github.com/anidl/multi-downloader-nx/blob/master/docs/DOCUMENTATION.md

**Comment by f4rf1x** [comment]
I just tried with...

q: 0
nServer: 1
mp4mux: false
noCleanUp: false
dubLang: spa
dubLang: jpn

But after downloading the streams, it still uses jpn as default audio. Is there something that I might be losing?

**Comment by izu-co** [comment]
Try `dubLang: ["eng", "jpn"] `
