### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by oxyuser** [anidl/multi-downloader-nx#292]
### Program version

3.0.5

### Operating System

Windows

### Type

Gui

### Service

Irrelevant

### Command used

N/A

### Show ID

N/A

### Episode

N/A

### Console Output

Won't open

### Additional Information

```Text
New update won't open on Windows, shows up in task manager but won't show the GUI
```

**Comment by izu-co** [comment]
It opens for me.
Can you open a terminal and execute the following command and paste the result here?
`C:\Users\USER\AppData\Local\Programs\multi-downloader-nx` - replace USER with your user 
`multi-downloader-nx.exe`

**Comment by oxyuser** [comment]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Star\AppData\Local\Programs\multi-downloader-nx>multi-downloader-nx.exe

C:\Users\Star\AppData\Local\Programs\multi-downloader-nx>
Appdata C:\Users\Star\AppData\Roaming
Appdata C:\Users\Star\AppData\Roaming
Appdata C:\Users\Star\AppData\Roaming
(node:14604) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, copyfile 'C:\Users\Star\AppData\Local\Temp\4de143c1-2e69-4dab-943b-518c5327adbf.tmp.yml' -> 'C:\Users\Star\AppData\Roaming\multi-downloader-nx\config\bin-path.yml'
    at Object.copyFileSync (node:fs:2800:3)
    at Object.func [as copyFileSync] (node:electron/js2c/asar_bundle:5:2027)
    at C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\modules\module.cfg-loader.js:74:36
    at Array.forEach (<anonymous>)
    at Object.ensureConfig (C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\modules\module.cfg-loader.js:72:46)
    at C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\gui\electron\src\index.js:140:29
    at step (C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\gui\electron\src\index.js:56:23)
    at Object.next (C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\gui\electron\src\index.js:37:53)
    at fulfilled (C:\Users\Star\AppData\Local\Programs\multi-downloader-nx\resources\app.asar\gui\electron\src\index.js:28:58)
(Use `multi-downloader-nx --trace-warnings ...` to show where the warning was created)
(node:14604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by izu-co** [comment]
I sill can't confirm the issue. Please try to reinstall

**Comment by oxyuser** [comment]
i have

**Comment by izu-co** [comment]
I have no clu why it wont work

**Comment by oxyuser** [comment]
Fixed after using CLI version, the GUI version started working

**Comment by sww724** [comment]
Looks like the GUI didn't create a needed directory that the CLI did - "(node:14604) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, copyfile 'C:\Users\Star\AppData\Local\Temp\4de143c1-2e69-4dab-943b-518c5327adbf.tmp.yml' -> 'C:\Users\Star\AppData\Roaming\multi-downloader-nx\config\bin-path.yml'" I haven't seen this error since I mainly use the CLI and am just testing the GUI.

**Comment by izu-co** [comment]
Nice catch. Fixed with the newest commit.
