### ISSUE TITLE
Only downloads 1 dialect of the same language.

### ISSUE THREAD

**Issue by alph4om3ga** [anidl/multi-downloader-nx#298]
### Program version

3.0.5

### Operating System

Windows

### Type

Gui

### Service

Both

### Command used

All Subs

### Show ID

GR751KNZY

### Episode

76

### Console Output

[1648994352192.log](https://github.com/anidl/multi-downloader-nx/files/8404676/1648994352192.log)
[latest.log](https://github.com/anidl/multi-downloader-nx/files/8404677/latest.log)

### Additional Information

```Text
When selecting all subs, if there is a ES and a ES-419 track it only downloads the ES-419 track. In order to download ES I have to select just ES and download the video again. I have tested this on multiple shows and episodes.
```

**Comment by CMoranO** [comment]
This happens even choosing expecifically " --dlsubs es-419 es" not only with "all subs" option.

**Comment by izu-co** [comment]
Should be fixed in the newest commit.
