### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by KnownMax316** [anidl/multi-downloader-nx#300]
### Program version

3.0.5

### Operating System

Windows

### Type

Gui

### Service

Both

### Command used

node lib --help

### Show ID

1234

### Episode

1

### Console Output

How to use the AniDL GUI? Can someone explain me how to do it because it would be much easier for me to use the GUI because i am a beginner. Thanks for your time.

### Additional Information

```Text
How to use the AniDL GUI? Can someone explain me how to do it because it would be much easier for me to use the GUI because i am a beginner. Thanks for your time.
```

**Comment by StrPlayer** [comment]
[https://imgur.com/a/7b91Xgh](Imgur) here's a small tutorial

**Comment by KnownMax316** [comment]
> [imgur](https://imgur.com/a/7b91Xgh) here's a small tutorial

that GUI window wont open in my case. I am asking for a way to open it. Thanks.

**Comment by StrPlayer** [comment]
I see it's because it's not making a file go do this directory and create a folder called config 

"C:\Users\username\AppData\Roaming\multi-downloader-nx"

This will get fixed next update I believe

**Comment by StrPlayer** [comment]
Make sure it's closed in your task manager before doing this

**Comment by izu-co** [comment]
Since the issue seems to be quite frequent recently, the updates will be pushed forward to later today.

**Comment by izu-co** [comment]
@StrPlayer The fixes have been made into a release, so a fix should be easier to communicate.
Thanks for your help!

**Comment by rayanve** [comment]
> [imgur](https://imgur.com/a/7b91Xgh) here's a small tutorial

How can i open like that link u show in the photo
