### ISSUE TITLE
Movie download from funi fails with [Episodes not selected!]

### ISSUE THREAD

**Issue by fuxxociety** [anidl/multi-downloader-nx#301]
### Program version

3.0.6 (Commit fb056aeb167b6f46a75f7824a0a26688155c6108 )

### Operating System

Linux

### Type

Cli

### Service

Funimation

### Command used

node index.js --skipUpdate --service funi -s 944359 -q 0 --dubLang eng -e 0-3 --debug

### Show ID

944359 

### Episode

1-3

### Console Output

fuxxy@showrunner:~/multi-downloader-nx/lib$ node index.js --skipUpdate --service funi -s 944359 -q 0 --dubLang eng -e 0-3 --debug

=== Multi Downloader NX 3.0.6 ===

[DEBUG] GOT OPTIONS:
{
  method: 'GET',
  retry: {
    limit: 2,
    methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
    statusCodes: [
      408, 413, 429, 500,
      502, 503, 504, 521,
      522, 524
    ],
    errorCodes: [
      'ETIMEDOUT',
      'ECONNRESET',
      'EADDRINUSE',
      'ECONNREFUSED',
      'EPIPE',
      'ENOTFOUND',
      'ENETUNREACH',
      'EAI_AGAIN'
    ],
    maxRetryAfter: Infinity,
    calculateDelay: [Function: calculateDelay]
  },
  timeout: {},
  headers: {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:70.0) Gecko/20100101 Firefox/70.0',
    'accept-encoding': 'gzip',
    authorization: 'Token <REDACTED>'
  },
  hooks: {
    beforeRequest: [ [Function (anonymous)] ],
    init: [],
    beforeRedirect: [],
    beforeError: [],
    beforeRetry: [],
    afterResponse: []
  },
  cache: undefined,
  dnsCache: undefined,
  decompress: true,
  throwHttpErrors: true,
  followRedirect: true,
  isStream: false,
  responseType: 'text',
  resolveBodyOnly: false,
  maxRedirects: 10,
  prefixUrl: [Getter/Setter],
  methodRewriting: true,
  ignoreInvalidCookies: false,
  http2: true,
  allowGetBody: false,
  https: undefined,
  pagination: {
    transform: [Function: transform],
    paginate: [Function: paginate],
    filter: [Function: filter],
    shouldContinue: [Function: shouldContinue],
    countLimit: Infinity,
    backoff: 0,
    requestLimit: 10000,
    stackAllItems: true
  },
  parseJson: [Function: parseJson],
  stringifyJson: [Function: stringifyJson],
  cacheOptions: {},
  url: URL {
    href: 'https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/944359',
    origin: 'https://prod-api-funimationnow.dadcdigital.com',
    protocol: 'https:',
    username: '',
    password: '',
    host: 'prod-api-funimationnow.dadcdigital.com',
    hostname: 'prod-api-funimationnow.dadcdigital.com',
    port: '',
    pathname: '/api/source/catalog/title/944359',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },
  username: '',
  password: '',
  [Symbol(isNormalizedAlready)]: true
}
[DEBUG] GOT OPTIONS:
{
  method: 'GET',
  retry: {
    limit: 2,
    methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
    statusCodes: [
      408, 413, 429, 500,
      502, 503, 504, 521,
      522, 524
    ],
    errorCodes: [
      'ETIMEDOUT',
      'ECONNRESET',
      'EADDRINUSE',
      'ECONNREFUSED',
      'EPIPE',
      'ENOTFOUND',
      'ENETUNREACH',
      'EAI_AGAIN'
    ],
    maxRetryAfter: Infinity,
    calculateDelay: [Function: calculateDelay]
  },
  headers: {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:70.0) Gecko/20100101 Firefox/70.0',
    'accept-encoding': 'gzip',
    authorization: 'Token <REDACTED>'
  },
  hooks: {
    beforeRequest: [ [Function (anonymous)] ],
    init: [],
    beforeRedirect: [],
    beforeError: [],
    beforeRetry: [],
    afterResponse: []
  },
  cache: undefined,
  dnsCache: undefined,
  decompress: true,
  throwHttpErrors: true,
  followRedirect: true,
  isStream: false,
  responseType: 'text',
  resolveBodyOnly: false,
  maxRedirects: 10,
  prefixUrl: [Getter/Setter],
  methodRewriting: true,
  ignoreInvalidCookies: false,
  http2: true,
  allowGetBody: false,
  https: undefined,
  pagination: {
    transform: [Function: transform],
    paginate: [Function: paginate],
    filter: [Function: filter],
    shouldContinue: [Function: shouldContinue],
    countLimit: Infinity,
    backoff: 0,
    requestLimit: 10000,
    stackAllItems: true
  },
  parseJson: [Function: parseJson],
  stringifyJson: [Function: stringifyJson],
  cacheOptions: {},
  url: URL {
    href: 'https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/944359/',
    origin: 'https://prod-api-funimationnow.dadcdigital.com',
    protocol: 'https:',
    username: '',
    password: '',
    host: 'prod-api-funimationnow.dadcdigital.com',
    hostname: 'prod-api-funimationnow.dadcdigital.com',
    port: '',
    pathname: '/api/source/catalog/title/944359/',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },
  username: '',
  password: '',
  shared: undefined,
  cacheHeuristic: undefined,
  immutableMinTimeToLive: undefined,
  ignoreCargoCult: undefined,
  request: undefined,
  timeout: {},
  agent: undefined,
  [Symbol(isNormalizedAlready)]: true,
  [Symbol(request)]: [AsyncFunction (anonymous)] {
    protocolCache: QuickLRU {
      maxSize: 100,
      onEviction: undefined,
      cache: [Map],
      oldCache: Map(0) {},
      _size: 1
    }
  }
}
[#944359] Ghost In The Shell (1995)
[DEBUG] GOT OPTIONS:
{
  method: 'GET',
  retry: {
    limit: 2,
    methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
    statusCodes: [
      408, 413, 429, 500,
      502, 503, 504, 521,
      522, 524
    ],
    errorCodes: [
      'ETIMEDOUT',
      'ECONNRESET',
      'EADDRINUSE',
      'ECONNREFUSED',
      'EPIPE',
      'ENOTFOUND',
      'ENETUNREACH',
      'EAI_AGAIN'
    ],
    maxRetryAfter: Infinity,
    calculateDelay: [Function: calculateDelay]
  },
  timeout: {},
  headers: {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:70.0) Gecko/20100101 Firefox/70.0',
    'accept-encoding': 'gzip',
    authorization: 'Token <REDACTED>'
  },
  hooks: {
    beforeRequest: [ [Function (anonymous)] ],
    init: [],
    beforeRedirect: [],
    beforeError: [],
    beforeRetry: [],
    afterResponse: []
  },
  cache: undefined,
  dnsCache: undefined,
  decompress: true,
  throwHttpErrors: true,
  followRedirect: true,
  isStream: false,
  responseType: 'text',
  resolveBodyOnly: false,
  maxRedirects: 10,
  prefixUrl: [Getter/Setter],
  methodRewriting: true,
  ignoreInvalidCookies: false,
  http2: true,
  allowGetBody: false,
  https: undefined,
  pagination: {
    transform: [Function: transform],
    paginate: [Function: paginate],
    filter: [Function: filter],
    shouldContinue: [Function: shouldContinue],
    countLimit: Infinity,
    backoff: 0,
    requestLimit: 10000,
    stackAllItems: true
  },
  parseJson: [Function: parseJson],
  stringifyJson: [Function: stringifyJson],
  cacheOptions: {},
  url: URL {
    href: 'https://prod-api-funimationnow.dadcdigital.com/api/funimation/episodes/?limit=-1&sort=order&sort_direction=ASC&title_id=944359',
    origin: 'https://prod-api-funimationnow.dadcdigital.com',
    protocol: 'https:',
    username: '',
    password: '',
    host: 'prod-api-funimationnow.dadcdigital.com',
    hostname: 'prod-api-funimationnow.dadcdigital.com',
    port: '',
    pathname: '/api/funimation/episodes/',
    search: '?limit=-1&sort=order&sort_direction=ASC&title_id=944359',
    searchParams: URLSearchParams {
      'limit' => '-1',
      'sort' => 'order',
      'sort_direction' => 'ASC',
      'title_id' => '944359' },
    hash: ''
  },
  username: '',
  password: '',
  [Symbol(isNormalizedAlready)]: true
}
[INFO] Episodes not selected!

### Additional Information

```Text
Initially tried downloading with '--all', because I wasn't able to display episodes associated with the movie. After viewing the XML at https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/944359/ , I discovered 3 episodes, so attempted this last time with '-e 0-3'
```

**Comment by izu-co** [comment]
I have holidays in the coming week and will take a look at it during that time.

**Comment by izu-co** [comment]
The movies are only available in other countries (e.g. Australia) or are in need of purchasing first.
