### ISSUE TITLE
does nothing.

### ISSUE THREAD

**Issue by storm134** [anidl/multi-downloader-nx#305]
i have been using cruncy/funi downloaders for years. thought i would update today to newest version. followed install instructions. but when i run the command nothing happens.

C:\multi-downloader-nx-master\lib>node crunchy.js --auth
C:\multi-downloader-nx-master\lib>
C:\multi-downloader-nx-master\lib>node crunchy.js -s 26492 -e 1
C:\multi-downloader-nx-master\lib>

here are the step i used to install. tried on both windows 10 and 11 (same)

- updated to nodejs 16.14.2
- unzipped multi-downloader
- ran npm i
- ran npm run tsc false
- went to lib folder
- ran node crunchy.js --auth (does nothing)
- tried node crunchy.js -s 26492 -e 1 (does nothing)

Have i missed something on setup?

**Comment by storm134** [comment]
found same issue in closed issues

**Comment by izu-co** [comment]
Nice to hear that you have been using the tool for such a long time and that you found your issue :)

Just for everyone stumbling over this issue, you must now use `node index.js`
