### ISSUE TITLE
will not see mkvmerge

### ISSUE THREAD

**Issue by storm134** [anidl/multi-downloader-nx#307]
setting path in path-bin but will not find mkvmerge i put it in the bin folder in side the multi-merge folder

mkvmerge: "./bin/MKVToolNix/mkvmerge.exe"

this works in the old crunchy/funi downloaders

**Comment by izu-co** [comment]
Fixed with the newest commit.

**Comment by izu-co** [comment]
If you don't want to update, try adding `${wdir}` infront like so: `${wdir}/bin/MKVToolNix/mkvmerge.exe`
