### ISSUE TITLE
Funnmation search issue

### ISSUE THREAD

**Issue by XEVON01** [anidl/multi-downloader-nx#308]
I'm facing a issue with funimation search, I have entered full name of the show but then also the show doesn't come up, even copy pasted the show name from funimation but not working

**Comment by izu-co** [comment]
Can you give the version and the name of the show please? Also, I would need your region (e.g USA)

**Comment by XEVON01** [comment]
I'm using the latest release, I searhced for the promised neverland, and my region is USA

**Comment by izu-co** [comment]
![grafik](https://user-images.githubusercontent.com/57068530/163785497-c7b8e6ba-3b86-4187-aea1-4ce081d91444.png)
It works fine for me, so the issue should be on your side.

**Comment by XEVON01** [comment]
thank you so much, I was using --search, used -f and it worked, I really appreciate you people are active here
A suggestion - you people should create a discord server, it would be really good

**Comment by izu-co** [comment]
`discord.gg/qEpbWen5vq`
