### ISSUE TITLE
just asking that all

### ISSUE THREAD

**Issue by DragonVsKira** [anidl/multi-downloader-nx#309]
is the Source code for the GUI free to got i like to play with it and see what i can do with it ps what program u use to make the gui

**Comment by izu-co** [comment]
According to the license (MIT) you can do everything you want except sue us.
I would urge you to share the changes you make tho.

**Comment by DragonVsKira** [comment]
will do how do i going about getting the Source code for the GUI?
 what program u use to make the gui so i can download it

**Comment by izu-co** [comment]
Just clone the source code.

Start the GUI in `gui\\react` with `npm start`
And you start the Windows App with `npm start` in the main directory.
