### ISSUE TITLE
How to customize mkvmerge commands

### ISSUE THREAD

**Issue by LeLuke007** [anidl/multi-downloader-nx#311]
Bro is there any option to customize the mkvmerge commands, like I don't want commands like "--no-date", "--disable-track-statistics-tags", "--engage no_variable_data" and instead I would like to change the track order of the subs and flagging Eng sub to default for crunchyroll-DLs.
These are minor commands I want to customize for myself, rest the cli is working perfectly fine.

**Comment by izu-co** [comment]
See #219. My commands might be about FFmpeg, but also apply to mkvmerge.

**Comment by izu-co** [comment]
If you want I could add an option like `--mkvmergeOptions "--yourStuff"` with "--no-date", "--disable-track-statistics-tags", "--engage no_variable_data" as default.

This way, you could customize it.

**Comment by LeLuke007** [comment]
> If you want I could add an option like `--mkvmergeOptions "--yourStuff"` with "--no-date", "--disable-track-statistics-tags", "--engage no_variable_data" as default.
> 
> This way, you could customize it.

Yeah pls. That would be a great help

**Comment by izu-co** [comment]
The newest commit adds the feature. If it is not working, try to put it in the cli defaults, since escaping `"` from the terminal might not work correctly.

**Comment by izu-co** [comment]
Also, you would need to build it yourself, since it does not qualify for a new release. 
If you need help with that, contact me any time.
