### ISSUE TITLE
Minor Subtitle Issue

### ISSUE THREAD

**Issue by LeLuke007** [anidl/multi-downloader-nx#312]
Service: Crunchyroll

When I download a series with jap and a dub audio (suppose eng), the subs of all the other languages are taken from the jap video but the subtitle of the dubbed lang (eng) is taken from eng video which actually has FORCED subs of the Japanese words/heading used in the episode. So the dialogues are not there.
I just want that the sub of the dubbed language should also be taken from the Jap video or just include it with forced sub just like in funimation.
Like when we download from funimation, the subs of both the files are included. (The Eng CC sub is from eng video with text of dialogue used in eng audio track while the normal eng sub is translation to jap audio along with por and spa ofc.)

**Comment by izu-co** [comment]
Implemented
