### ISSUE TITLE
Can you add a only english dubbed subtitle option in GUI.

### ISSUE THREAD

**Issue by Tridagger** [anidl/multi-downloader-nx#313]
Can you add a only english dubbed subtitle option in GUI.

sometimes, I needn't download videos, I just want to download english dubbed subtitles.

THX!

**Comment by LeLuke007** [comment]
You can do it using "--novids" and -"-noaudio" at the same time in the CLI

**Comment by izu-co** [comment]
I see what you want and I might add the options if I find the time

**Comment by izu-co** [comment]
Added with the newest commit and published in the newest release.
