### ISSUE TITLE
This is Not Working heroku

### ISSUE THREAD

**Issue by KuroProjects** [anidl/multi-downloader-nx#320]
### Program version

3.0.7

### Operating System

Linux

### Type

Cli

### Service

Both

### Command used

/r node index --service crunchy --auth

### Show ID

0000

### Episode

0

### Console Output

·  
=== Multi Downloader NX 3.0.7 ===
[Q] LOGIN/EMAIL:
xxxxxxxxxxxxxx
[Q] PASSWORD   :
xxxxxxxxxxxxx

[ERROR] HTTPError 503: Service Temporarily Unavailable
[ERROR] Just a moment...
[ERROR] Body: <!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Just a moment...</title>
  <style>
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; color: #000000; font-family:-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, "Helvetica Neue",Arial, sans-serif; font-size: 16px; line-height: 1.7em;-webkit-font-smoothing: antialiased;}
    h1 { text-align: center; font-weight:700; margin: 16px 0; font-size: 32px; color:#000000; line-height: 1.25;}
    p {font-size: 20px; font-weight: 400; margin: 8px 0;}
    p, .attribution, {text-align: center;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 32px;}
    @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
    #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
    #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
    .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
    a { color: #2c7cb0; text-decoration: none; -moz-transition: color 0.15s ease; -o-transition: color 0.15s ease; -webkit-transition: color 0.15s ease; transition: color 0.15s ease; }
    a:hover{color: #f4a15d}
    .attribution{font-size: 16px; line-height: 1.5;}
    .ray_id{display: block; margin-top: 8px;}
    #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
    #cf-hcaptcha-container { text-align:center;}
    #cf-hcaptcha-container iframe { display: inline-block;}
</style>

      <meta http-equiv="refresh" content="35">
  <script>
    //<![CDATA[
    (function(){
      window._cf_chl_opt={
        cvId: "2",
        cType: "non-interactive",
        cNounce: "69475",
        cRay: "71de5ca32db79b7d",
        cHash: "c2783d2d0f4e97b",
        cUPMDTk: "\/auth\/v1\/token?__cf_chl_tk=CxaQVIf4PCQU3J4wwEg0F4XtJEOetuFeNZwc_zXf2f4-1655663698-0-gaNycGzNCKU",
        cFPWv: "g",
        cTTimeMs: "1000",
        cRq: {
          ru: "aHR0cHM6Ly9iZXRhLWFwaS5jcnVuY2h5cm9sbC5jb20vYXV0aC92MS90b2tlbg==",
          ra: "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV09XNjQ7IHJ2OjkwLjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvOTAuMA==",
          rm: "UE9TVA==",
          d: "SvLX6H+Pir7fcSnqxe9emPQRu0f+jsBPwaOV0zzOVqDaz7YQk4j+FRuHStqLzb9T89RXDxtKt5D5zhZp6/CkTp8A7nlAGDhCYAdEsbFG3lQYFNGEb8qZ3nOZPdmn4tUraT2ef+9Mx5rf+VschMUJmuDIDAFORxHD9OgWsN3CDPtwIeiKipUuO9wMVDZoxnhbQaPXg48O0aVFs0oJ0Vvn4TPDx2nOLjz0weDPmYiTZOz4NxB3oIlRRTcjv3CATNi9wALeKkEvBCab3sP9l5BQspEDUgEzjLgB68tVbF1DSdDBHW+OmGTicT/CV5ihYsMQumtqQWOG1vw1d6pw8TKxRjAB8tB7QRvqp5hCJeCOHYh3WYRdASNIc0sdYZ1XBQEIHQjHqnstwewnhxcfnnu9H6LsvfWh09eMLYbJoqz8vhBBQXV9LjUJlzGKx3YTSVn6Gx7lMAzsQtZUEmGg0daDd9cb15fxXOzgov99+cKLcb24274SJ6PqEXbrQSm1dQnbiKptZHa2G59yl6d58ZLIo88UzQHfFK12yj/bxNq90iw=",
          t: "MTY1NTY2MzY5OC40MjcwMDA=",
          m: "l2dEuO25/tXHI2i2fm8zGVBCodULzoW/D4df5j1MFjw=",
          i1: "L0jeAhwUZJbhzLmIOgcRTA==",
          i2: "S+NeYQngfgB8H0aSd69p0Q==",
          zh: "qQz4tblgEgtOKuLwUaA7NrEUXyzFHvjAH4jkpQCn35I=",
          uh: "oGJh0DgZPfD5LpLi4E0P4rnC0mTjhlqa0wZZSg17pow=",
          hh: "G/9Eyg8MLMji4eRhv0DU/+643Vf1HG99pQipmYXUnLg=",
        }
      }
      window._cf_chl_enter = function(){window._cf_chl_opt.p=1};
·   })();
    //]]>
  </script>
  

</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript>
    <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
  <div id="cf-content" style="display:none">
    
    <div id="cf-bubbles">
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> beta-api.crunchyroll.com.</h1>
    
    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs" id="cf-spinner-allow-5-secs" >Please allow up to 5 seconds&hellip;</p>
    <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting&hellip;</p>
  </div>

**Comment by izu-co** [comment]
Can you try logging in on the website?

**Comment by KuroProjects** [comment]
yeah it is logging in browser in ubuntu but when i try in the terminal it says this

**Comment by thehenil** [comment]
Same erroor

**Comment by izu-co** [comment]
Duplicate with #321.

(I know this was first, but I already answered some questions over there)
