### ISSUE TITLE
Getting error on Linux Ubuntu

### ISSUE THREAD

**Issue by thehenil** [anidl/multi-downloader-nx#321]
[ERROR] HTTPError 503: Service Temporarily Unavailable
[ERROR] Just a moment...
[ERROR] Body: <!DOCTYPE HTML>

Full error:- https://bin.theindex.moe/?f228b7d8baccf8e4#Eu83onTahabRwiFby6C7YjJpXgbetXCKXNN3tTsyD4sA

**Comment by thehenil** [comment]
@izu-co can you help sir?

**Comment by izu-co** [comment]
It seems like the login page is being blocked by CloudFront. This will require more work, and I am currently pretty tied up.

**Comment by thehenil** [comment]
Sir is there any quick fix @izu-co

**Comment by izu-co** [comment]
None I can think of

**Comment by thehenil** [comment]
How much it will take sir for the fix? @izu-co

**Comment by izu-co** [comment]
In terms of time its hard to say without investigation. Since I have no time atm, maybe 5 weeks?

**Comment by izu-co** [comment]
Can one of you (@thehenil or @KuroProjects) confirm whether this issue is Linux specific or if it also happens on Windows?

**Comment by thehenil** [comment]
Sir, I tried on windows server it's giving same error @izu-co

**Comment by izu-co** [comment]
Thank you

**Comment by AnimeDL** [comment]
I'm going to close this issue since it doesn't seem to be a problem anymore. If it is however, feel free to re-open
