### ISSUE TITLE
Feature request: avoid unnecessary bandwidth usage when downloading multiple dubs

### ISSUE THREAD

**Issue by acc029** [anidl/multi-downloader-nx#322]
This program currently downloads the 1080p videos for all dubs from Crunchyroll when you choose all dubs. It should only download the 1080p video for one of the dubs (with the main video that will be used for the .mkv output) and the 720p videos for the dubs that you will only take the audio from, since 720p already gives you the highest audio quality.

So if you choose "jpn, eng, spa, por" for the dubs, it should download "jpn" at 1080p and "eng, spa, por" at 720p.

**Comment by izu-co** [comment]
While your are correct, it’s currently not an option due to my limited time.

**Comment by AnimeDL** [comment]
Closing because this was implemented with the --dlVideoOnce flag and this wasn't closed when it was merged
