### ISSUE TITLE
Funimation movie downloading not working

### ISSUE THREAD

**Issue by LeLuke007** [anidl/multi-downloader-nx#323]
I was trying to download a movie from Funimation with movie ID "136928" but looks like neither --flm nor -s command with --all works for single funimation movie titles.
Though I was able to download some movie collections with -s command

Movie name : [#136928] The Girl Who Leapt Through Time
Commands used:
aniDL --service "funi" -s "136928" --all --dlsubs "all"
aniDL --service "funi" --flm "136928" --dlsubs "all"

**Comment by drknss89** [comment]
@LeLuke007 at least from what I can see when looking on funimation, the movie isn't actually available, it's all clips or trailers

**Comment by izu-co** [comment]
I've just confirmed that the movie is indeed not available on funimation
