### ISSUE TITLE
Feature Request: Download to sub folders

### ISSUE THREAD

**Issue by drknss89** [anidl/multi-downloader-nx#327]
I don't know if this is an option or not already but i would like to have different shows download into sub folders with the shows title.

Example:
anidl.exe --service "funi" -s 1174282 -e "all" --nosubs
anidl.exe --service "funi" -s 119587 -e "all" --nosubs

1174282 would download to ./videos/Yashahime: Princess Half-Demon/
119587 would download to ./videos/Yu Yu Hakusho/

Instead of all episodes of both shows downloading to ./videos/

Thank You in advance whether this is possible or not.
I appreciate all the work everyone has put into this program

**Comment by drknss89** [comment]
nvm, i read the cli functions a little closer and figured it out

**Comment by izu-co** [comment]
For anyone who's searching for this feature: Look at `--fileName`. By adding a path separator (`/` or `\\`) you can create subfolders
