### ISSUE TITLE
Change default audio when downloading multiple audios

### ISSUE THREAD

**Issue by f4rf1x** [anidl/multi-downloader-nx#330]
Hi.

When I select the audios and subs to be downloaded

`> aniDL.exe --service "funi" -s 1326227 -e 4 -q 0 --dubLang spa jpn --dlsubs es-419 --mks
`
It performs the download with the parameters given:

```
> [INFO] Selected Episodes: 0004

[INFO] Saint Seiya: The Lost Canvas - S1E4 - The Prayer Wreaths
[INFO] Available streams (Non-Encrypted):
[#1326465] Japanese [Uncut] (selected) (using 'Spanish' for subtitles)
[#2430596] Portuguese (Brazil) [Uncut]
[#2431475] Spanish (Latin Am) [Uncut] (selected)
```

But when the mux process starts, it puts the japanese+subs as primary elements... How could I solve or workaround this in order to get spanish only as default audio option?

Below the log of the mkvmerge process:

`"mkvmerge" -o "F:\MD\videos\[Funimation] Saint Seiya_ The Lost Canvas - S01E04 [1080p].mkv" --no-date --disable-track-statistics-tags --engage no_variable_data --video-tracks 0 --no-audio --track-name 0:"Japanese [Uncut]" --language 0:jpn "F:\MD\videos\[Funimation] Saint Seiya_ The Lost Canvas - S01E04 [1080p].video.ts" --track-name 0:"Japanese" --language 0:jpn --no-video --audio-tracks 0 "F:\MD\videos\[Funimation] Saint Seiya_ The Lost Canvas - S01E04 [1080p].audio.jpn.ts" --track-name 0:"Spanish" --language 0:spa --no-video --audio-tracks 0 "F:\MD\videos\[Funimation] Saint Seiya_ The Lost Canvas - S01E04 [1080p].audio.spa.ts" --track-name 0:"Latin American Spanish" --language 0:"spa" "F:\MD\videos\[Funimation] Saint Seiya_ The Lost Canvas - S01E04 [1080p].subtitle.spa.ass" --no-attachments`

**Comment by izu-co** [comment]
Short answer: You cant
Long answer: I have holidays in two weeks and will work on this request then. If I have time earlier, I will work on it sooner.

**Comment by izu-co** [comment]
Implemented with the newest commit
