### ISSUE TITLE
BUG: No amd64 build available for Ubuntu GUI download (only arm64)

### ISSUE THREAD

**Issue by shinji257** [anidl/multi-downloader-nx#332]
### Program version

3.0.7

### Operating System

Linux

### Type

Gui

### Service

Irrelevant

### Command used

N/A

### Show ID

N/A

### Episode

N/A

### Console Output

N/A

### Additional Information

```Text
There is no amd64 build available for the Ubuntu gui option download.  It's an arm64 build that is included and can't be installed on an amd64 version of Linux.  This seems to have changed starting 3.0.1 when you switched to electron builder.  I'm not sure if it was intentional or not.
```

**Comment by izu-co** [comment]
I actually only have the most basic knowledge of Ubuntu. 
Is it enough for you if I add the `x64` architecture?

**Comment by shinji257** [comment]
Yes.

**Comment by izu-co** [comment]
The new default for ubuntu is now x64 (602d39e97b3695e00d33b5b6a12bd6b09418e7a1).
Arm can be built by cloning the repo and running the commands manually.
