### ISSUE TITLE
BUG: --all may result in recaps overwriting the previous episode

### ISSUE THREAD

**Issue by shinji257** [anidl/multi-downloader-nx#335]
### Program version

3.0.7

### Operating System

Linux

### Type

Cli

### Service

Crunchyroll

### Command used

./aniDL --s GREX1K2GY --all

### Show ID

GRE5K3NQ6

### Episode

GRZJ2DNG6

### Console Output

=== Multi Downloader NX 3.0.7 ===

[INFO] USER: jurobei0 (jurobei@elite-systems.org)
[INFO] Your Country: US

[INFO] Requested object ID: GRZJ2DNG6
 ✓[S:GREX1K2GY|E:GRZJ2DNG6|EPI.778618] 91 Days (English Dub) - 7.5 - Brief Candle [24m33s, DUB, STREAM]
    - Subtitles: en

[INFO] Requesting: [E:GRZJ2DNG6] 91 Days (English Dub) - 7.5 - Brief Candle
[INFO] Selecting raw stream
[INFO] Full stream found! (✓1: adaptive_hls/eng/- )
[INFO] Full stream found! ( 2: download_hls/eng/- )
[INFO] Full stream found! ( 3: vo_adaptive_hls/eng/- )
[INFO] Downloading video...
[INFO] Playlists URL: https://pl.crunchyroll.com/evs3/0589955771563e14017c8e61ad9094ae/assets/abafa33f3c9e2368878d1ed81f82004b_,3573577.mp4,3573578.mp4,3573576.mp4,3573574.mp4,3573575.mp4,3573573.mp4,.urlset/master.m3u8?Expires=1656771879&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy8wNTg5OTU1NzcxNTYzZTE0MDE3YzhlNjFhZDkwOTRhZS9hc3NldHMvYWJhZmEzM2YzYzllMjM2ODg3OGQxZWQ4MWY4MjAwNGJfLDM1NzM1NzcubXA0LDM1NzM1NzgubXA0LDM1NzM1NzYubXA0LDM1NzM1NzQubXA0LDM1NzM1NzUubXA0LDM1NzM1NzMubXA0LC51cmxzZXQvbWFzdGVyLm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NTY3NzE4Nzl9fX1dfQ__&Signature=gQB79w24eLrZ-GykNKNSf2B0GzseQpROiNcIdO6fCyYttQbM5UK0tHyKQdNeUnbD36qo5s~o~sn3kJ5OLhpqVCg979C5faSioZcbc8ErpDnAqtXZsx5Ucks6CeuctgbusySIJdvuVHxosd5PWdslC6RDIydPBc7krrQl20KckaDO~P-TrAc9n3STg~rzZsH5FFJOLZ9fZXRv-FDBBxIt-gn6FvCpoLaqP-OxT~b-EAg0IZYfUD8D974fEc8wcfkKPvDoZ3jdgs~n8yLD2~Y2FmDS-gj~ESsDrZKuYeEyR9NjtT4mMtLLkdf9szw7lecQLMwcquBYN74KQ-FQezNTcQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA (adaptive_hls/eng/-)
[INFO] Servers available:
        pl.crunchyroll.com (ll-prod)
        pl.crunchyroll.com (akamai-prod)
[INFO] Available qualities:
        [1] 144x80 (83KiB/s)
        [2] 428x240 (333KiB/s)
        [3] 640x360 (480KiB/s)
        [4] 848x480 (773KiB/s)
        [5] 1280x720 (2274KiB/s)
        [6] 1920x1080 (5990KiB/s)
[INFO] Selected quality: 1920x1080 @ pl.crunchyroll.com (ll-prod)
[INFO] Stream URL: https://pl.crunchyroll.com/evs3/0589955771563e14017c8e61ad9094ae/assets/abafa33f3c9e2368878d1ed81f82004b_3573578.mp4/index-v1-a1.m3u8?Expires=1656771880&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy8wNTg5OTU1NzcxNTYzZTE0MDE3YzhlNjFhZDkwOTRhZS9hc3NldHMvYWJhZmEzM2YzYzllMjM2ODg3OGQxZWQ4MWY4MjAwNGJfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NTY3NzE4ODB9fX1dfQ__&Signature=FsV2N2v-Y8V27Z7y98OADloUBXAx2Y9zB7OXH3bnOYqzujWu0NiR1BAxYXp4QjdmR6GMhDJB5Elh22B5okkgld8o3NXYhMQK-5lIjdNDZ7u9dLWGifOlyDOaIPM3hRrChXQDGS9ynU~g4sa26RC2TGvEwvpr~KBFRQSUcJVr5bijZLyccuLQ5~MTxzwZakr19hWmEXeteG4CMiZrMuyZ01CRmqJTva00sacnGRnZqvcqv5mlpOsNTlku0-UpbDpDESezfSDI3jCz-PZnkxK9O7CF3bAStGGmrta7ThUdYx4MZ1FN-6o6nxyy06y2NPFGwjlv9d7juOog5sYp3jSGww__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=ll-prod
[INFO] Output filename: 91 Days (English Dub) [1080p]/E07.English
[INFO] Total parts in stream: 369 (37*10)
[INFO] Saving stream to «/home/shinji/multi-downloader-nx/videos/91 Days (English Dub) [1080p]/E07.English.ts»...
[INFO] 10 of 369 parts downloaded [3%] (26s | 33Mb/s)
[INFO] 20 of 369 parts downloaded [5%] (21s | 42Mb/s)
[INFO] 30 of 369 parts downloaded [8%] (19s | 46Mb/s)
[INFO] 40 of 369 parts downloaded [11%] (17s | 47Mb/s)
[INFO] 50 of 369 parts downloaded [14%] (16s | 48Mb/s)
[INFO] 60 of 369 parts downloaded [16%] (15s | 49Mb/s)
[INFO] 70 of 369 parts downloaded [19%] (15s | 49Mb/s)
(snip remaining)

### Additional Information

```Text
Special episodes usually are listed on the website as Episode 7.5 or as SP.  In the case of the latter it seems to name them properly but in this instance it is marked as 7.5 and the output of --srz just mentioned it as S01.  I'm not tagging in season number normally but I did try once and it said undefined for it.  I guess in that case it would have ended up unique.  Is there any way we can somehow catch that?

In most cases it seems to overwrite without prompting at all.
```

**Comment by shinji257** [comment]
I just realized that I believe this is the same as #324

**Comment by izu-co** [comment]
It might be, but until I investigate further, it's not clear. Therefor, I will leave this issue open until further notice.
