### ISSUE TITLE
BUG - Install Fails with apt

### ISSUE THREAD

**Issue by senpaizeroani** [anidl/multi-downloader-nx#341]
### Program version

3.0.7

### Operating System

Linux

### Type

Gui

### Service

Irrelevant

### Command used

sudo apt-get install ./multi-downloader-nx_3.0.7_arm64.deb

### Show ID

none

### Episode

none

### Console Output

The following packages have unmet dependencies:
   multi-downloader-nx:arm64 : Depends on: libgtk-3-0:arm64 but is not installable
                               Depends on: libnotify4:arm64 but is not installable
                               Depends on: libnss3:arm64 but is not installable
                               Depends on: libxss1:arm64 but is not installable
                               Depends on: libxtst6:arm64 but is not installable
                               Depends on: libatspi2.0-0:arm64 but is not installable
                               Depends on: libuuid1:arm64 but is not installable
                               Depends on: libsecret-1-0:arm64 but is not installable
                               Recommended: libappindicator3-1:arm64 is not installable
E: Unable to correct problems, you have held defective packages.

### Additional Information

```Text
Original German Output:

user@user-pc:~/Downloads$ sudo apt-get install ./multi-downloader-nx_3.0.7_arm64.deb 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Hinweis: »multi-downloader-nx:arm64« wird an Stelle von »./multi-downloader-nx_3.0.7_arm64.deb« gewählt.
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 multi-downloader-nx:arm64 : Hängt ab von: libgtk-3-0:arm64 ist aber nicht installierbar
                             Hängt ab von: libnotify4:arm64 ist aber nicht installierbar
                             Hängt ab von: libnss3:arm64 ist aber nicht installierbar
                             Hängt ab von: libxss1:arm64 ist aber nicht installierbar
                             Hängt ab von: libxtst6:arm64 ist aber nicht installierbar
                             Hängt ab von: libatspi2.0-0:arm64 ist aber nicht installierbar
                             Hängt ab von: libuuid1:arm64 ist aber nicht installierbar
                             Hängt ab von: libsecret-1-0:arm64 ist aber nicht installierbar
                             Empfiehlt: libappindicator3-1:arm64 ist aber nicht installierbar
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
```

**Comment by senpaizeroani** [comment]
Why downloading the project by myself and buildung it too the debian package worked

I guess you have to build it yourself.

**Comment by izu-co** [comment]
What command did you use to build the version that worked?

**Comment by shinji257** [comment]
Are you running on an ARM based system?  It won't work on an X86_64 based system.  It works when you built manually likely because the X86_64 version is now the default build target in git due to a prior ticket of mine.

**Comment by izu-co** [comment]
Closed due to inactivity. Feel free to reopen with new information at any time.
