### ISSUE TITLE
Better support for the new dub languages

### ISSUE THREAD

**Issue by acc029** [anidl/multi-downloader-nx#342]
The first Hindi, European Spanish, Arabic and Italian dubs were added to Crunchyroll today. Current issues:
- There's no way to download a Hindi dub with the GUI.
- There's no name for the new Hindi subtitle track.
- When downloading, the European Spanish dub replaces the English dub
- Audio tracks don't have names like the subtitle tracks, so you can't tell the difference between the two "Spanish" dubs on a video player.

**Comment by izu-co** [comment]
With the changes you made, which problems still remain?

**Comment by acc029** [comment]
Audio tracks not having names to distinguish between the two "Spanish" dubs.
Now, since the program uses the "spa" ISO 639-2 code for both dubs, "spa" can download both or only one. I didn't change that because I don't really understand how the language codes are used internally, but if IETF BCP 47 codes can be used (or if there isn't a specific standard), you could change Latin American Spanish to spa-419 or es-419 (if you switch to 2 letter codes).

**Comment by izu-co** [comment]
We are using ISO 639-3 codes. If there is no difference between the Spanish version, it can unfortunately not be helped.
