### ISSUE TITLE
Use MediaID to download

### ISSUE THREAD

**Issue by BraveSail** [anidl/multi-downloader-nx#345]
I'm making auto downloader tool and get rss from https://www.crunchyroll.com/rss/anime, this rss only give urls like http://www.crunchyroll.com/smile-of-the-arsnotoria-the-animation/episode-3-sniff-852595 and http://www.crunchyroll.com/media-852595 or just MediaID like `<crunchyroll:mediaId>852595</crunchyroll:mediaId>`, the point is how can i use ID like `852595` to download that episode directly?

I tried `node /root/multi-downloader-nx/lib/index.js --service crunchy -e 852595` it shows
```
=== Multi Downloader NX 3.0.7 ===

[INFO] USER: 
[INFO] Your Country: 

[INFO] Requested object ID: 852595
[ERROR] HTTPError 404: Not Found
[ERROR] Objects Request FAILED!
[INFO] Body: {
        "__class__": "error",
        "__href__": "",
        "__links__": {},
        "__actions__": {},
        "type": "Not Found",
        "code": "404",
        "message": "Invalid object identifier",
        "context": {}
}
/root/multi-downloader-nx/lib/crunchy.js:81
    throw new TypeError(s ? "Object is not iterable." : "Symbol.iterator is not defined.");
          ^

TypeError: Object is not iterable.
    at __values (/root/multi-downloader-nx/lib/crunchy.js:81:11)
    at Crunchy.<anonymous> (/root/multi-downloader-nx/lib/crunchy.js:354:30)
    at step (/root/multi-downloader-nx/lib/crunchy.js:67:23)
    at Object.next (/root/multi-downloader-nx/lib/crunchy.js:48:53)
    at fulfilled (/root/multi-downloader-nx/lib/crunchy.js:39:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by BraveSail** [comment]
I noticed that url like http://www.crunchyroll.com/smile-of-the-arsnotoria-the-animation/episode-3-sniff-852595 redirect to https://beta.crunchyroll.com/watch/GJWU2G78P/sniff, this shows the episode id `GJWU2G78P` which can use `node /root/multi-downloader-nx/lib/index.js --service crunchy -e GJWU2G78P` to download it directly, but problem is if use program like `curl` to access it will popup cloudflare's captcha, that's hard to process. It will be nice if `multi-downloader-nx` process it.

**Comment by izu-co** [comment]
No support for this will be added.
The tool can already search and download shows by showing the correct MediaID.

If you want this feature, please feel free to add it yourself.
