### ISSUE TITLE
Incorrect release for Ubuntu CLI

### ISSUE THREAD

**Issue by redalpha333** [anidl/multi-downloader-nx#354]
Though I'm not using Ubuntu, I am using a terminal emulator on Android which in the past has worked on every single CLI however, yours provides a batch file which I would have to use a Windows emulator to run as it is not supported on Linux or Android without a compatibility layer
![Screenshot_20220727-211331~2](https://user-images.githubusercontent.com/43896325/181400582-0d4d2686-d2bf-41d2-b21b-32d5d7b121e3.png)

**Comment by izu-co** [comment]
That batch file is for demonstration purposes only. 
The executable is the aniDL file. You may need to give it executable permission first.

**Comment by izu-co** [comment]
Closed due to inactivity. Feel free to reopen with new information at any time.
