### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ItsRainingHP** [anidl/multi-downloader-nx#357]
### Program version

3.1.0

### Operating System

Windows

### Type

Cli

### Service

Crunchyroll

### Command used

node index.js --service "crunchy" -s GY75CDWGJ -e 1-12 --mp4

### Show ID

GRDQE71GY

### Episode

1-12

### Console Output

![Untitled](https://user-images.githubusercontent.com/79205731/183057970-a0a46bda-608e-4184-8808-bc24fb1a76be.png)

### Additional Information

```Text
Anything marked MATURE fails to select episodes.
```

**Comment by ItsRainingHP** [comment]
Yes sir.

![image](https://user-images.githubusercontent.com/79205731/183067707-d4eccf5c-82b8-4a47-9172-636a4ce42878.png)

**Comment by RichardArc** [comment]
I'm having the same issue where it returns with "episode not selected" even with non mature shows.

**Comment by izu-co** [comment]
> I'm having the same issue where it returns with "episode not selected" even with non mature shows.
> 
> `aniDL.exe --service crunchy -s GYQ4CZE2K -e 11 `
> 
> `aniDL.exe --service crunchy -s G6P8CX0D5 -e 1` `aniDL.exe --service crunchy --srz GXJHM39MP -e 1`
> 
> when using `--srz` it doesn't say `[INFO] Episodes not selected!` but I'm not sure if it did that in the first place Program version 3.1.0 and 3.0.7

For me, the given command works just fine with the selection. Please open up a new issue and attach your configuration files, please.
