### ISSUE TITLE
Subtitle Font Change [FUNI]

### ISSUE THREAD

**Issue by KnownMax316** [anidl/multi-downloader-nx#359]
### Program version

2.0.18

### Operating System

Windows

### Type

Cli

### Service

Funimation

### Command used

anidl.exe --service funi -s 1036022 -q 0 -e 1 --dlsubs en ja --dubLang eng jpn --fontName Trebuchet MS Bold

### Show ID

1036022

### Episode

1

### Console Output

> anidl.exe --service funi --search blue exorcist

=== Multi Downloader NX 2.0.18 ===

[INFO] Search Results:
[#1036022] Blue Exorcist
[#952253] Sweet Blue Flowers
[#1399997] Blue Reflection Ray
[#40763] Project Blue Earth SOS
[#567789] AOKANA: Four Rhythm Across the Blue
[INFO] Total shows found: 5

@ C:\Users\KnownMaxer\Desktop\multi-downloader-nx-2.0.18-win64

> anidl.exe --service funi -s 1036022 -q 0 -e 1 --dlsubs en ja --dubLang eng jpn --fontName Trebuchet MS Bold

=== Multi Downloader NX 2.0.18 ===

[#1036022] Blue Exorcist (2012)
[0001] Blue Exorcist - #01 The Devil Resides in Human Souls (00:23:27) [HD1080, Japanese, English] (selected)
[0002] Blue Exorcist - #02 Gehenna Gate (00:23:27) [HD1080, English, Japanese]
[0003] Blue Exorcist - #03 Brothers (00:23:27) [HD1080, Japanese, English]
[0004] Blue Exorcist - #04 The Garden of Amahara (00:23:27) [HD1080, English, Japanese]
[0005] Blue Exorcist - #05 A Boy From the Cursed Temple (00:23:27) [HD1080, Japanese, English]
[0006] Blue Exorcist - #06 The Phantom Chef (00:23:27) [HD1080, Japanese, English]
[0007] Blue Exorcist - #07 A Flock of Plovers (00:23:27) [HD1080, Japanese, English]
[0008] Blue Exorcist - #08 Now A Certain Man Was Sick... (00:23:27) [HD1080, Japanese, English]
[0009] Blue Exorcist - #09 Memories (00:23:27) [HD1080, Japanese, English]
[0010] Blue Exorcist - #10 Black Cat (00:23:27) [HD1080, Japanese, English]
[0011] Blue Exorcist - #11 Demon of the Deep (00:23:27) [HD1080, English, Japanese]
[0012] Blue Exorcist - #12 A Game of Tag (00:23:27) [HD1080, English, Japanese]
[0013] Blue Exorcist - #13 Proof (00:23:27) [HD1080, English, Japanese]
[0014] Blue Exorcist - #14 A Fun Camping Trip (00:23:27) [HD1080, English, Japanese]
[0015] Blue Exorcist - #15 Act of Kindness (00:23:27) [HD1080, English, Japanese]
[0016] Blue Exorcist - #16 The Wager (00:23:27) [HD1080, English, Japanese]
[0017] Blue Exorcist - #17 Temptation (00:23:27) [HD1080, Japanese, English]
[0018] Blue Exorcist - #18 Friends (00:23:27) [HD1080, Japanese, English]
[0019] Blue Exorcist - #19 An Ordinary Day (00:23:27) [HD1080, English, Japanese]
[0020] Blue Exorcist - #20 Mask (00:23:27) [HD1080, Japanese, English]
[0021] Blue Exorcist - #21 The Secret Garden (00:23:27) [HD1080, English, Japanese]
[0022] Blue Exorcist - #22 Demon Hunting (00:23:27) [HD1080, English, Japanese]
[0023] Blue Exorcist - #23 Truth (00:23:27) [HD1080, Japanese, English]
[0024] Blue Exorcist - #24 Satan's Spawn (00:23:27) [HD1080, Japanese, English]
[0025] Blue Exorcist - #25 Time, Stop (00:23:27) [HD1080, English, Japanese]
[0026] Blue Exorcist S2 - #01 Small Beginnings (00:23:27) [HD1080, English, Japanese]
[0027] Blue Exorcist S2 - #02 Strange Bedfellows (00:23:27) [HD1080, English, Japanese]
[0028] Blue Exorcist S2 - #03 Suspicion Will Raise Bogies (00:23:27) [HD1080, Japanese, English]
[0029] Blue Exorcist S2 - #04 Act of Treachery (00:23:27) [HD1080, English, Japanese]
[0030] Blue Exorcist S2 - #05 Mysterious Connections (00:23:27) [HD1080, English, Japanese]
[0031] Blue Exorcist S2 - #06 A Wolf in Sheep's Clothing (00:23:27) [HD1080, Japanese, English]
[0032] Blue Exorcist S2 - #07 Like a Fire Burning Bright (00:23:27) [HD1080, English, Japanese]
[0033] Blue Exorcist S2 - #08 From Father to Son (00:23:27) [HD1080, Japanese, English]
[0034] Blue Exorcist S2 - #09 Through Thick and Thin (00:23:27) [HD1080, Japanese, English]
[0035] Blue Exorcist S2 - #10 Unbowed and Unbroken (00:23:27) [HD1080, Japanese, English]
[0036] Blue Exorcist S2 - #11 Shine Bright as the Sun (00:23:27) [HD1080, English, Japanese]
[0037] Blue Exorcist S2 - #12 Candid and Open (00:23:27) [HD1080, English, Japanese]

[INFO] Selected Episodes: 0001

[INFO] Blue Exorcist - S1E1 - The Devil Resides in Human Souls
[INFO] Available streams (Non-Encrypted):
[#1036098] English [Uncut] (selected)
[#1036067] Japanese [Uncut] (selected) (using 'English' for subtitles)
[INFO] Servers available:
        vmfst-api.prd.funimationsvc.com
[INFO] Available qualities:
         1: 416x234 (452KiB/s)
         2: 640x360 (677KiB/s)
         3: 768x432 (1043KiB/s)
         4: 768x432 (1432KiB/s)
         5: 960x540 (2333KiB/s)
         6: 1280x720 (3419KiB/s)
         7: 1280x720 (5184KiB/s)
         8: 1920x1080 (7232KiB/s)
         9: 1920x1080 (10050KiB/s)
[INFO] Selected layer: 9 (1920x1080) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/V1689374/b0129199-a1f3-4536-be85-b0732e77bbe6strnv-hl154_streaming_video_1920_1080_7800000_index.m3u8?t=exp%3D1659884085%7Eacl%3Dhttps%3A%2F%2Fvideo.prd.funimation.com%2FFunimationStoreFront%2FV1689374%2F*%7Ehmac%3Dac72af26260c8d12666a9eb2a7056c6ef354f5439d773e34d0f8ea0e91aa0c3d
[INFO] Output filename: [Funimation] Blue Exorcist - S01E01 [1080p].ts
[INFO] Saving stream to «C:\Users\KnownMaxer\Desktop\multi-downloader-nx-2.0.18-win64\videos\[Funimation] Blue Exorcist - S01E01 [1080p].video.ts»...
[INFO] 10 of 770 parts downloaded [1%] (39s | 29Mb/s)
[INFO] 20 of 770 parts downloaded [3%] (32s | 38Mb/s)
[INFO] 30 of 770 parts downloaded [4%] (28s | 41Mb/s)
[INFO] 40 of 770 parts downloaded [5%] (25s | 48Mb/s)
[INFO] 50 of 770 parts downloaded [6%] (24s | 48Mb/s)
[INFO] 60 of 770 parts downloaded [8%] (22s | 50Mb/s)
[INFO] 70 of 770 parts downloaded [9%] (21s | 53Mb/s)
[INFO] 80 of 770 parts downloaded [10%] (20s | 55Mb/s)
[INFO] 90 of 770 parts downloaded [12%] (19s | 56Mb/s)
[INFO] 100 of 770 parts downloaded [13%] (19s | 57Mb/s)
[INFO] 110 of 770 parts downloaded [14%] (18s | 59Mb/s)
[INFO] 120 of 770 parts downloaded [16%] (17s | 60Mb/s)
[INFO] 130 of 770 parts downloaded [17%] (17s | 60Mb/s)
[INFO] 140 of 770 parts downloaded [18%] (17s | 59Mb/s)
[INFO] 150 of 770 parts downloaded [19%] (16s | 60Mb/s)
[INFO] 160 of 770 parts downloaded [21%] (16s | 61Mb/s)
[INFO] 170 of 770 parts downloaded [22%] (15s | 62Mb/s)
[INFO] 180 of 770 parts downloaded [23%] (15s | 63Mb/s)
[INFO] 190 of 770 parts downloaded [25%] (15s | 63Mb/s)
[INFO] 200 of 770 parts downloaded [26%] (14s | 64Mb/s)
[INFO] 210 of 770 parts downloaded [27%] (15s | 61Mb/s)
[INFO] 220 of 770 parts downloaded [29%] (14s | 61Mb/s)
[INFO] 230 of 770 parts downloaded [30%] (14s | 62Mb/s)
[INFO] 240 of 770 parts downloaded [31%] (13s | 62Mb/s)
[INFO] 250 of 770 parts downloaded [32%] (13s | 62Mb/s)
[INFO] 260 of 770 parts downloaded [34%] (13s | 61Mb/s)
[INFO] 270 of 770 parts downloaded [35%] (13s | 61Mb/s)
[INFO] 280 of 770 parts downloaded [36%] (13s | 61Mb/s)
[INFO] 290 of 770 parts downloaded [38%] (12s | 61Mb/s)
[INFO] 300 of 770 parts downloaded [39%] (12s | 61Mb/s)
[INFO] 310 of 770 parts downloaded [40%] (12s | 59Mb/s)
[INFO] 320 of 770 parts downloaded [42%] (12s | 59Mb/s)
[INFO] 330 of 770 parts downloaded [43%] (12s | 60Mb/s)
[INFO] 340 of 770 parts downloaded [44%] (11s | 60Mb/s)
[INFO] 350 of 770 parts downloaded [45%] (11s | 61Mb/s)
[INFO] 360 of 770 parts downloaded [47%] (11s | 61Mb/s)
[INFO] 370 of 770 parts downloaded [48%] (11s | 56Mb/s)
[INFO] 380 of 770 parts downloaded [49%] (11s | 56Mb/s)
[INFO] 390 of 770 parts downloaded [51%] (11s | 55Mb/s)
[INFO] 400 of 770 parts downloaded [52%] (11s | 54Mb/s)
[INFO] 410 of 770 parts downloaded [53%] (10s | 54Mb/s)
[INFO] 420 of 770 parts downloaded [55%] (11s | 51Mb/s)
[INFO] 430 of 770 parts downloaded [56%] (10s | 51Mb/s)
[INFO] 440 of 770 parts downloaded [57%] (10s | 51Mb/s)
[INFO] 450 of 770 parts downloaded [58%] (10s | 51Mb/s)
[INFO] 460 of 770 parts downloaded [60%] (10s | 51Mb/s)
[INFO] 470 of 770 parts downloaded [61%] (9s | 51Mb/s)
[INFO] 480 of 770 parts downloaded [62%] (9s | 52Mb/s)
[INFO] 490 of 770 parts downloaded [64%] (9s | 50Mb/s)
[INFO] 500 of 770 parts downloaded [65%] (9s | 50Mb/s)
[INFO] 510 of 770 parts downloaded [66%] (8s | 50Mb/s)
[INFO] 520 of 770 parts downloaded [68%] (8s | 50Mb/s)
[INFO] 530 of 770 parts downloaded [69%] (8s | 50Mb/s)
[INFO] 540 of 770 parts downloaded [70%] (7s | 51Mb/s)
[INFO] 550 of 770 parts downloaded [71%] (7s | 51Mb/s)
[INFO] 560 of 770 parts downloaded [73%] (6s | 51Mb/s)
[INFO] 570 of 770 parts downloaded [74%] (6s | 50Mb/s)
[INFO] 580 of 770 parts downloaded [75%] (6s | 50Mb/s)
[INFO] 590 of 770 parts downloaded [77%] (6s | 50Mb/s)
[INFO] 600 of 770 parts downloaded [78%] (5s | 50Mb/s)
[INFO] 610 of 770 parts downloaded [79%] (5s | 50Mb/s)
[INFO] 620 of 770 parts downloaded [81%] (5s | 50Mb/s)
[INFO] 630 of 770 parts downloaded [82%] (4s | 50Mb/s)
[INFO] 640 of 770 parts downloaded [83%] (4s | 51Mb/s)
[INFO] 650 of 770 parts downloaded [84%] (4s | 50Mb/s)
[INFO] 660 of 770 parts downloaded [86%] (3s | 50Mb/s)
[INFO] 670 of 770 parts downloaded [87%] (3s | 50Mb/s)
[INFO] 680 of 770 parts downloaded [88%] (3s | 50Mb/s)
[INFO] 690 of 770 parts downloaded [90%] (3s | 50Mb/s)
[INFO] 700 of 770 parts downloaded [91%] (2s | 50Mb/s)
[INFO] 710 of 770 parts downloaded [92%] (2s | 50Mb/s)
[INFO] 720 of 770 parts downloaded [94%] (2s | 50Mb/s)
[INFO] 730 of 770 parts downloaded [95%] (1s | 50Mb/s)
[INFO] 740 of 770 parts downloaded [96%] (1s | 50Mb/s)
[INFO] 750 of 770 parts downloaded [97%] (1s | 50Mb/s)
[INFO] 760 of 770 parts downloaded [99%] (0s | 50Mb/s)
[INFO] 770 of 770 parts downloaded [100%] (0s | 50Mb/s)
[INFO] Saving stream to «C:\Users\KnownMaxer\Desktop\multi-downloader-nx-2.0.18-win64\videos\[Funimation] Blue Exorcist - S01E01 [1080p].audio.eng.ts»...
[INFO] 10 of 771 parts downloaded [1%] (12s | 4.0Mb/s)
[INFO] 20 of 771 parts downloaded [3%] (9s | 5.4Mb/s)
[INFO] 30 of 771 parts downloaded [4%] (8s | 6.2Mb/s)
[INFO] 40 of 771 parts downloaded [5%] (7s | 6.6Mb/s)
[INFO] 50 of 771 parts downloaded [6%] (7s | 6.4Mb/s)
[INFO] 60 of 771 parts downloaded [8%] (8s | 6.1Mb/s)
[INFO] 70 of 771 parts downloaded [9%] (7s | 6.4Mb/s)
[INFO] 80 of 771 parts downloaded [10%] (7s | 6.6Mb/s)
[INFO] 90 of 771 parts downloaded [12%] (7s | 6.7Mb/s)
[INFO] 100 of 771 parts downloaded [13%] (6s | 6.8Mb/s)
[INFO] 110 of 771 parts downloaded [14%] (6s | 6.9Mb/s)
[INFO] 120 of 771 parts downloaded [16%] (6s | 6.8Mb/s)
[INFO] 130 of 771 parts downloaded [17%] (6s | 6.9Mb/s)
[INFO] 140 of 771 parts downloaded [18%] (6s | 7.0Mb/s)
[INFO] 150 of 771 parts downloaded [19%] (6s | 7.1Mb/s)
[INFO] 160 of 771 parts downloaded [21%] (6s | 7.1Mb/s)
[INFO] 170 of 771 parts downloaded [22%] (5s | 7.1Mb/s)
[INFO] 180 of 771 parts downloaded [23%] (5s | 7.1Mb/s)
[INFO] 190 of 771 parts downloaded [25%] (5s | 7.2Mb/s)
[INFO] 200 of 771 parts downloaded [26%] (5s | 7.1Mb/s)
[INFO] 210 of 771 parts downloaded [27%] (5s | 7.1Mb/s)
[INFO] 220 of 771 parts downloaded [29%] (5s | 7.1Mb/s)
[INFO] 230 of 771 parts downloaded [30%] (5s | 7.1Mb/s)
[INFO] 240 of 771 parts downloaded [31%] (5s | 7.1Mb/s)
[INFO] 250 of 771 parts downloaded [32%] (5s | 7.0Mb/s)
[INFO] 260 of 771 parts downloaded [34%] (5s | 7.1Mb/s)
[INFO] 270 of 771 parts downloaded [35%] (5s | 7.1Mb/s)
[INFO] 280 of 771 parts downloaded [36%] (4s | 7.2Mb/s)
[INFO] 290 of 771 parts downloaded [38%] (8s | 3.7Mb/s)
[INFO] 300 of 771 parts downloaded [39%] (10s | 3.1Mb/s)
[INFO] 310 of 771 parts downloaded [40%] (10s | 3.1Mb/s)
[INFO] 320 of 771 parts downloaded [42%] (9s | 3.2Mb/s)
[INFO] 330 of 771 parts downloaded [43%] (10s | 3.0Mb/s)
[INFO] 340 of 771 parts downloaded [44%] (9s | 3.0Mb/s)
[INFO] 350 of 771 parts downloaded [45%] (9s | 3.1Mb/s)
[INFO] 360 of 771 parts downloaded [47%] (8s | 3.1Mb/s)
[INFO] 370 of 771 parts downloaded [48%] (8s | 3.2Mb/s)
[INFO] 380 of 771 parts downloaded [49%] (8s | 3.0Mb/s)
[INFO] 390 of 771 parts downloaded [51%] (8s | 3.0Mb/s)
[INFO] 400 of 771 parts downloaded [52%] (9s | 2.7Mb/s)
[INFO] 410 of 771 parts downloaded [53%] (9s | 2.5Mb/s)
[INFO] 420 of 771 parts downloaded [54%] (10s | 2.3Mb/s)
[INFO] 430 of 771 parts downloaded [56%] (9s | 2.3Mb/s)
[INFO] 440 of 771 parts downloaded [57%] (10s | 2.2Mb/s)
[INFO] 450 of 771 parts downloaded [58%] (10s | 2.1Mb/s)
[INFO] 460 of 771 parts downloaded [60%] (10s | 2.1Mb/s)
[INFO] 470 of 771 parts downloaded [61%] (9s | 2.1Mb/s)
[INFO] 480 of 771 parts downloaded [62%] (9s | 2.0Mb/s)
[INFO] 490 of 771 parts downloaded [64%] (9s | 2.0Mb/s)
[INFO] 500 of 771 parts downloaded [65%] (9s | 1.9Mb/s)
[INFO] 510 of 771 parts downloaded [66%] (9s | 1.8Mb/s)
[INFO] 520 of 771 parts downloaded [67%] (9s | 1.8Mb/s)
[INFO] 530 of 771 parts downloaded [69%] (10s | 1.6Mb/s)
[INFO] 540 of 771 parts downloaded [70%] (10s | 1.5Mb/s)
[INFO] 550 of 771 parts downloaded [71%] (10s | 1.5Mb/s)
[INFO] 560 of 771 parts downloaded [73%] (9s | 1.4Mb/s)
[INFO] 570 of 771 parts downloaded [74%] (9s | 1.4Mb/s)
[INFO] 580 of 771 parts downloaded [75%] (10s | 1.3Mb/s)
[INFO] 590 of 771 parts downloaded [77%] (10s | 1.1Mb/s)
[INFO] 600 of 771 parts downloaded [78%] (10s | 1.1Mb/s)
[INFO] 610 of 771 parts downloaded [79%] (10s | 1.0Mb/s)
[INFO] 620 of 771 parts downloaded [80%] (11s | 0.89Mb/s)
[INFO] 630 of 771 parts downloaded [82%] (12s | 0.78Mb/s)
[INFO] 640 of 771 parts downloaded [83%] (14s | 0.61Mb/s)
[WARN] Part 647: 2 attempt to retrieve data
        ERROR: connect ETIMEDOUT 68.142.107.7:443
[WARN] Part 648: 2 attempt to retrieve data
        ERROR: connect ETIMEDOUT 68.142.107.7:443
[WARN] Part 650: 2 attempt to retrieve data
        ERROR: connect ETIMEDOUT 68.142.107.7:443
[WARN] Part 647: 3 attempt to retrieve data
        ERROR: connect ETIMEDOUT 68.142.107.7:443
[WARN] Part 648: 3 attempt to retrieve data
        ERROR: connect ETIMEDOUT 68.142.107.7:443
[WARN] Part 650: 3 attempt to retrieve data
        ERROR: connect ETIMEDOUT 68.142.107.7:443
[WARN] Part 647: 4 attempt to retrieve data
        ERROR: connect ETIMEDOUT 68.142.107.7:443
[WARN] Part 648: 4 attempt to retrieve data
        ERROR: connect ETIMEDOUT 68.142.107.7:443
[WARN] Part 650: 4 attempt to retrieve data
        ERROR: connect ETIMEDOUT 68.142.107.7:443
[WARN] Part 647: 5 attempt to retrieve data
        ERROR: connect ETIMEDOUT 68.142.107.7:443
[WARN] Part 648: 5 attempt to retrieve data
        ERROR: connect ETIMEDOUT 68.142.107.7:443
[WARN] Part 650: 5 attempt to retrieve data
        ERROR: connect ETIMEDOUT 68.142.107.7:443
[ERROR] Part 647 download error:
        connect ETIMEDOUT 68.142.107.7:443
[ERROR] Part 648 download error:
        connect ETIMEDOUT 68.142.107.7:443
[ERROR] Part 650 download error:
        connect ETIMEDOUT 68.142.107.7:443
[ERROR] 3 parts not downloaded
[INFO] Servers available:
        vmfst-api.prd.funimationsvc.com
[INFO] Available qualities:
         1: 416x234 (454KiB/s)
         2: 640x360 (694KiB/s)
         3: 768x432 (1173KiB/s)
         4: 768x432 (1629KiB/s)
         5: 960x540 (2392KiB/s)
         6: 1280x720 (3444KiB/s)
         7: 1280x720 (5194KiB/s)
         8: 1920x1080 (6974KiB/s)
         9: 1920x1080 (9489KiB/s)
[INFO] Selected layer: 9 (1920x1080) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/V1689374/e8d060cd-2206-4bb2-85a4-8b26520c0968strnv-hl154_streaming_video_1920_1080_7800000_index.m3u8?t=exp%3D1659884085%7Eacl%3Dhttps%3A%2F%2Fvideo.prd.funimation.com%2FFunimationStoreFront%2FV1689374%2F*%7Ehmac%3Dac72af26260c8d12666a9eb2a7056c6ef354f5439d773e34d0f8ea0e91aa0c3d
[INFO] Output filename: [Funimation] Blue Exorcist - S01E01 [1080p].ts
[INFO] Saving stream to «C:\Users\KnownMaxer\Desktop\multi-downloader-nx-2.0.18-win64\videos\[Funimation] Blue Exorcist - S01E01 [1080p].audio.jpn.ts»...
[WARN] Key 1: 2 attempt to retrieve data
        ERROR: connect ETIMEDOUT 68.142.107.7:443
[WARN] Key 1: 3 attempt to retrieve data
        ERROR: connect ETIMEDOUT 68.142.107.7:443
[INFO] 10 of 771 parts downloaded [1%] (57m44s | 0.014Mb/s)
[INFO] 20 of 771 parts downloaded [3%] (28m33s | 0.028Mb/s)
[INFO] 30 of 771 parts downloaded [4%] (18m49s | 0.043Mb/s)
[INFO] 40 of 771 parts downloaded [5%] (13m57s | 0.057Mb/s)
[INFO] 50 of 771 parts downloaded [6%] (11m01s | 0.071Mb/s)
[INFO] 60 of 771 parts downloaded [8%] (9m04s | 0.085Mb/s)
[INFO] 70 of 771 parts downloaded [9%] (7m41s | 0.098Mb/s)
[INFO] 80 of 771 parts downloaded [10%] (6m38s | 0.11Mb/s)
[INFO] 90 of 771 parts downloaded [12%] (5m50s | 0.13Mb/s)
[INFO] 100 of 771 parts downloaded [13%] (5m10s | 0.14Mb/s)
[INFO] 110 of 771 parts downloaded [14%] (4m39s | 0.15Mb/s)
[INFO] 120 of 771 parts downloaded [16%] (4m12s | 0.17Mb/s)
[INFO] 130 of 771 parts downloaded [17%] (3m49s | 0.18Mb/s)
[INFO] 140 of 771 parts downloaded [18%] (3m30s | 0.19Mb/s)
[INFO] 150 of 771 parts downloaded [19%] (3m14s | 0.21Mb/s)
[INFO] 160 of 771 parts downloaded [21%] (2m59s | 0.22Mb/s)
[INFO] 170 of 771 parts downloaded [22%] (2m46s | 0.23Mb/s)
[INFO] 180 of 771 parts downloaded [23%] (2m35s | 0.25Mb/s)
[INFO] 190 of 771 parts downloaded [25%] (2m25s | 0.26Mb/s)
[INFO] 200 of 771 parts downloaded [26%] (2m15s | 0.27Mb/s)
[INFO] 210 of 771 parts downloaded [27%] (2m07s | 0.29Mb/s)
[INFO] 220 of 771 parts downloaded [29%] (1m59s | 0.30Mb/s)
[INFO] 230 of 771 parts downloaded [30%] (1m52s | 0.31Mb/s)
[INFO] 240 of 771 parts downloaded [31%] (1m46s | 0.32Mb/s)
[INFO] 250 of 771 parts downloaded [32%] (1m40s | 0.34Mb/s)
[INFO] 260 of 771 parts downloaded [34%] (1m34s | 0.35Mb/s)
[INFO] 270 of 771 parts downloaded [35%] (1m29s | 0.36Mb/s)
[INFO] 280 of 771 parts downloaded [36%] (1m26s | 0.37Mb/s)
[INFO] 290 of 771 parts downloaded [38%] (1m22s | 0.38Mb/s)
[INFO] 300 of 771 parts downloaded [39%] (1m18s | 0.39Mb/s)
[INFO] 310 of 771 parts downloaded [40%] (1m14s | 0.41Mb/s)
[INFO] 320 of 771 parts downloaded [42%] (1m10s | 0.42Mb/s)
[INFO] 330 of 771 parts downloaded [43%] (1m09s | 0.41Mb/s)
[INFO] 340 of 771 parts downloaded [44%] (1m06s | 0.42Mb/s)
[INFO] 350 of 771 parts downloaded [45%] (1m03s | 0.43Mb/s)
[INFO] 360 of 771 parts downloaded [47%] (1m00s | 0.45Mb/s)
[INFO] 370 of 771 parts downloaded [48%] (57s | 0.46Mb/s)
[INFO] 380 of 771 parts downloaded [49%] (54s | 0.47Mb/s)
[INFO] 390 of 771 parts downloaded [51%] (51s | 0.48Mb/s)
[INFO] 400 of 771 parts downloaded [52%] (49s | 0.49Mb/s)
[INFO] 410 of 771 parts downloaded [53%] (46s | 0.50Mb/s)
[INFO] 420 of 771 parts downloaded [54%] (44s | 0.52Mb/s)
[INFO] 430 of 771 parts downloaded [56%] (42s | 0.53Mb/s)
[INFO] 440 of 771 parts downloaded [57%] (40s | 0.54Mb/s)
[INFO] 450 of 771 parts downloaded [58%] (39s | 0.54Mb/s)
[INFO] 460 of 771 parts downloaded [60%] (37s | 0.55Mb/s)
[INFO] 470 of 771 parts downloaded [61%] (35s | 0.56Mb/s)
[INFO] 480 of 771 parts downloaded [62%] (33s | 0.57Mb/s)
[INFO] 490 of 771 parts downloaded [64%] (31s | 0.58Mb/s)
[INFO] 500 of 771 parts downloaded [65%] (30s | 0.59Mb/s)
[INFO] 510 of 771 parts downloaded [66%] (28s | 0.60Mb/s)
[INFO] 520 of 771 parts downloaded [67%] (26s | 0.61Mb/s)
[INFO] 530 of 771 parts downloaded [69%] (25s | 0.63Mb/s)
[INFO] 540 of 771 parts downloaded [70%] (23s | 0.64Mb/s)
[INFO] 550 of 771 parts downloaded [71%] (22s | 0.65Mb/s)
[INFO] 560 of 771 parts downloaded [73%] (21s | 0.66Mb/s)
[INFO] 570 of 771 parts downloaded [74%] (19s | 0.67Mb/s)
[INFO] 580 of 771 parts downloaded [75%] (18s | 0.68Mb/s)
[INFO] 590 of 771 parts downloaded [77%] (17s | 0.68Mb/s)
[INFO] 600 of 771 parts downloaded [78%] (16s | 0.69Mb/s)
[INFO] 610 of 771 parts downloaded [79%] (15s | 0.70Mb/s)
[INFO] 620 of 771 parts downloaded [80%] (14s | 0.71Mb/s)
[INFO] 630 of 771 parts downloaded [82%] (13s | 0.71Mb/s)
[INFO] 640 of 771 parts downloaded [83%] (12s | 0.72Mb/s)
[INFO] 650 of 771 parts downloaded [84%] (11s | 0.73Mb/s)
[INFO] 660 of 771 parts downloaded [86%] (10s | 0.74Mb/s)
[INFO] 670 of 771 parts downloaded [87%] (9s | 0.75Mb/s)
[INFO] 680 of 771 parts downloaded [88%] (8s | 0.76Mb/s)
[INFO] 690 of 771 parts downloaded [89%] (7s | 0.77Mb/s)
[INFO] 700 of 771 parts downloaded [91%] (6s | 0.78Mb/s)
[INFO] 710 of 771 parts downloaded [92%] (5s | 0.79Mb/s)
[INFO] 720 of 771 parts downloaded [93%] (4s | 0.80Mb/s)
[INFO] 730 of 771 parts downloaded [95%] (3s | 0.81Mb/s)
[INFO] 740 of 771 parts downloaded [96%] (2s | 0.81Mb/s)
[INFO] 750 of 771 parts downloaded [97%] (2s | 0.82Mb/s)
[INFO] 760 of 771 parts downloaded [99%] (1s | 0.83Mb/s)
[INFO] 770 of 771 parts downloaded [99%] (0s | 0.84Mb/s)
[INFO] 771 of 771 parts downloaded [100%] (0s | 0.84Mb/s)
[INFO] Downloading subtitles...
[INFO] Subtitles downloaded!

> "mkvmerge" -o "C:\Users\KnownMaxer\Desktop\multi-downloader-nx-2.0.18-win64\videos\[Funimation] Blue Exorcist - S01E01 [1080p].mkv" --no-date --disable-track-statistics-tags --engage no_variable_data --video-tracks 0 --no-audio --track-name 0:"English [Uncut]" --language 0:eng "C:\Users\KnownMaxer\Desktop\multi-downloader-nx-2.0.18-win64\videos\[Funimation] Blue Exorcist - S01E01 [1080p].video.ts" --track-name 0:"Japanese" --language 0:jpn --no-video --audio-tracks 0 "C:\Users\KnownMaxer\Desktop\multi-downloader-nx-2.0.18-win64\videos\[Funimation] Blue Exorcist - S01E01 [1080p].audio.jpn.ts" --track-name 0:"English" --language 0:"eng" "C:\Users\KnownMaxer\Desktop\multi-downloader-nx-2.0.18-win64\videos\[Funimation] Blue Exorcist - S01E01 [1080p].subtitle.eng.ass" --no-attachments
mkvmerge v69.0.0 ('Day And Age') 64-bit
'C:\Users\KnownMaxer\Desktop\multi-downloader-nx-2.0.18-win64\videos\[Funimation] Blue Exorcist - S01E01 [1080p].video.ts': Using the demultiplexer for the format 'MPEG transport stream'.
'C:\Users\KnownMaxer\Desktop\multi-downloader-nx-2.0.18-win64\videos\[Funimation] Blue Exorcist - S01E01 [1080p].audio.jpn.ts': Using the demultiplexer for the format 'AAC'.
'C:\Users\KnownMaxer\Desktop\multi-downloader-nx-2.0.18-win64\videos\[Funimation] Blue Exorcist - S01E01 [1080p].subtitle.eng.ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'C:\Users\KnownMaxer\Desktop\multi-downloader-nx-2.0.18-win64\videos\[Funimation] Blue Exorcist - S01E01 [1080p].video.ts' track 0: Using the output module for the format 'AVC/H.264 (unframed)'.
'C:\Users\KnownMaxer\Desktop\multi-downloader-nx-2.0.18-win64\videos\[Funimation] Blue Exorcist - S01E01 [1080p].audio.jpn.ts' track 0: Using the output module for the format 'AAC'.
'C:\Users\KnownMaxer\Desktop\multi-downloader-nx-2.0.18-win64\videos\[Funimation] Blue Exorcist - S01E01 [1080p].subtitle.eng.ass' track 0: Using the output module for the format 'SSA/ASS text subtitles'.
The file 'C:\Users\KnownMaxer\Desktop\multi-downloader-nx-2.0.18-win64\videos\[Funimation] Blue Exorcist - S01E01 [1080p].mkv' has been opened for writing.
'C:\Users\KnownMaxer\Desktop\multi-downloader-nx-2.0.18-win64\videos\[Funimation] Blue Exorcist - S01E01 [1080p].video.ts' track 0: Extracted the aspect ratio information from the video bitstream and set the display dimensions to 1920/1080.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 15 seconds.

[INFO] Done!

### Additional Information

```Text
The output still is in NotoSans font even though I added the Trebuchet MS Bold true typeface font by making a "fonts" folder. The output : imgur.com/a/S3z8bHb
```

**Comment by izu-co** [comment]
The fonts folder is only for Crunchyroll. The font should be located on the system, however I may be able to add it into the mkv file

**Comment by KnownMax316** [comment]
> The fonts folder is only for Crunchyroll. The font should be located on the system, however I may be able to add it into the mkv file

Can you add the feature to Funimation too?

**Comment by AnimeDL** [comment]
Going to close this sin Funimation is no more
