### ISSUE TITLE
Episodes not being selected

### ISSUE THREAD

**Issue by RichardArc** [anidl/multi-downloader-nx#360]
### Program version

3.1.0

### Operating System

Windows

### Type

Cli

### Service

Crunchyroll

### Command used

aniDL.exe --service crunchy --srz GXJHM39MP -e 1

### Show ID

GXJHM39MP

### Episode

1

### Console Output

> aniDL.exe --service crunchy --srz GXJHM39MP -e 1

=== Multi Downloader NX 3.1.0 ===

[INFO] USER: username (email@gmail.com)
[INFO] Your Country: US

[Z:GXJHM39MP] A Couple of Cuckoos (Seasons: 6, EPs: 77) [SIMULCAST, SUB]
  [S:G6P8CX0D5] A Couple of Cuckoos (Season: 1) [SIMULCAST, SUB]
  [S:GR49C7MVN] A Couple of Cuckoos (French Dub) (Season: 1) [SIMULCAST, DUB]
    - Subtitles: fr
  [S:GRJQC1J0E] A Couple of Cuckoos (English Dub) (Season: 1) [SIMULCAST, DUB]
    - Subtitles: en
  [S:G6X0C4KWX] A Couple of Cuckoos (Portuguese Dub) (Season: 1) [SIMULCAST, DUB]
    - Subtitles: pt
  [S:GR9PC2DMQ] A Couple of Cuckoos (Spanish Dub) (Season: 1) [SIMULCAST, DUB]
    - Subtitles: es-419, es-ES
  [S:GY19CPX1M] A Couple of Cuckoos (German Dub) (Season: 1) [SIMULCAST, DUB]
    - Subtitles: de
[INFO] USER: username (email@gmail.com)
[INFO] Your Country: US

[E1] A Couple of Cuckoos - Season 1 - You're going to be my boyfriend. [☆ Japanese, ☆ French, ☆ English, ☆ Portuguese, ☆ Spanish, ☆ German]
[E2] A Couple of Cuckoos - Season 1 - I'm not going to marry you. [☆ Japanese, ☆ French, ☆ English, ☆ Portuguese, ☆ Spanish, ☆ German]
[E3] A Couple of Cuckoos - Season 1 - You aren't going to beat me!!!! [☆ Japanese, ☆ French, ☆ English, ☆ Portuguese, ☆ Spanish, ☆ German]
[E4] A Couple of Cuckoos - Season 1 - Would you please go out with me...? [☆ Japanese, ☆ French, ☆ English, ☆ Portuguese, ☆ Spanish, ☆ German]
[E5] A Couple of Cuckoos - Season 1 - Can we do our morning study sessions together...? [☆ Japanese, ☆ French, ☆ English, ☆ Portuguese, ☆ Spanish, ☆ German]
[E6] A Couple of Cuckoos - Season 1 - I thought you live by yourself. [☆ Japanese, ☆ French, ☆ English, ☆ Portuguese, ☆ Spanish, ☆ German]
[E7] A Couple of Cuckoos - Season 1 - Is my fate going to change? [☆ Japanese, ☆ French, ☆ English, ☆ Portuguese, ☆ Spanish, ☆ German]
[E8] A Couple of Cuckoos - Season 1 - Are you going to marry him? [☆ Japanese, ☆ French, ☆ English, ☆ Portuguese, ☆ Spanish, ☆ German]
[E9] A Couple of Cuckoos - Season 1 - The Kuroshio currents beckon to me. [☆ Japanese, ☆ French, ☆ English, ☆ Portuguese, ☆ Spanish, ☆ German]
[E10] A Couple of Cuckoos - Season 1 - Don't treat me like your kid sister. [☆ Japanese, ☆ French, ☆ English, ☆ Portuguese, ☆ Spanish, ☆ German]
[E11] A Couple of Cuckoos - Season 1 - I can't forget that just happened. [☆ Japanese, ☆ French, ☆ English, ☆ Portuguese, ☆ Spanish, ☆ German]
[E12] A Couple of Cuckoos - Season 1 - It's not that I like you, yet. [☆ Japanese, ☆ French, ☆ English, ☆ Portuguese, ☆ Spanish, ☆ German]
[E13] A Couple of Cuckoos - Season 1 - Untitled [☆ Japanese, ☆ French, ☆ English]
[E14] A Couple of Cuckoos - Season 1 - Untitled [☆ Japanese]
[E15] A Couple of Cuckoos - Season 1 - Untitled [☆ Japanese]

------------------------------

@ C:\Users\user\Downloads\multi-downloader-nx-windows64-cli
[config.zip](https://github.com/anidl/multi-downloader-nx/files/9277582/config.zip)

### Additional Information

```Text
I have tried other ids, tried on v3.0.7 which has been used with success before.
I have reauthenticated successfully
I have tried with a fresh config
Something that did occur to me is that I share this account with a friend, wondering if that could cause issues?
```

**Comment by RichardArc** [comment]
So sharing an account was the issue. Just found out the premium subscription was cancelled. Got my own and it works. A pretty basic thing to miss, my bad

**Comment by izu-co** [comment]
No worry’s. I was wondering if maybe they cancelled your premium subscription, since premium episodes without premium can’t be selected
