### ISSUE TITLE
Doesn't detect SPanish (Latam) audio in Funi

### ISSUE THREAD

**Issue by f4rf1x** [anidl/multi-downloader-nx#361]
When I'm trying to download 2 audios from Funi, using the given command (also tryied withou the "")

`aniDL.exe --service "funi" -s 124389 -e 4 -q 0 -dubLang "spa-419" "jpn" --dlSubs es-419 --defaultAudio spa-419 --mks`

It shows the available languages

`[ 0004] My Hero Academia - #04 Start Line (24:36) [HD1080, Japanese, Spanish] (selected)`

But when the download starts, it only detects the jap audio, skipping the detection of spanish (latam) audio

[INFO] Selected Episodes: 0004

```
[INFO] My Hero Academia - S1E4 - Start Line
[INFO] Available streams (Non-Encrypted):
[#1254182] Japanese [Uncut] (selected) (using 'Spanish' for subtitles)
[#1616739] Spanish (Latin Am) [Uncut]
```

And the final result muxing is a video only with japanese with spanish subs:

[INFO] Subtitles downloaded!
[INFO][mkvmerge] Started merging

`> "mkvmerge" -o "D:\AnyStream\multi-downloader-nx\videos\[Funimation] My Hero Academia - S01E04 [1080p].mkv" --no-date --disable-track-statistics-tags --engage no_variable_data --video-tracks 0 --audio-tracks 1 --track-name 0:"Japanese [Uncut]" --language 1:jpn --default-track 1:0 "D:\AnyStream\multi-downloader-nx\videos\[Funimation] My Hero Academia - S01E04 [1080p].video.jpn.ts" --track-name 0:"Latin American Spanish" --language 0:"spa-419" --default-track 0:0 "D:\AnyStream\multi-downloader-nx\videos\[Funimation] My Hero Academia - S01E04 [1080p].subtitle.spa-419.ass" --no-attachments`

Is there anything that I could be ommiting when using the command in Funi videos?

**Comment by AnidlSupport** [comment]
You should try to use `--dubLang`

**Comment by AnimeDL** [comment]
Closing because it works if using the proper flag `--dubLang`
