### ISSUE TITLE
I have a problem with multiple downloadsBUG

### ISSUE THREAD

**Issue by kokoboko5** [anidl/multi-downloader-nx#384]
### Program version

3.1.0 and all Verisons

### Operating System

Windows

### Type

Cli

### Service

Crunchyroll

### Command used

aniDL --service "crunchy" -s GYQ4CZ9D9 -e 1-12 --novids --noaudio --dlsubs ar

### Show ID

GYQ4CZ9D9

### Episode

1-12

### Console Output

[INFO] Requesting: [GK9U30381] Cinderella Chef (Season 3) - 1 - An Unexpected Turn of Events
[INFO] Selecting raw stream
[INFO] Full stream found! (✓1: adaptive_hls/jpn/- )
[INFO] Full stream found! ( 2: download_hls/jpn/- )
[INFO] Full stream found! ( 3: vo_adaptive_hls/jpn/- )
[INFO] Downloading video...
[INFO] Playlists URL: https://pl.crunchyroll.com/evs3/be51b66a1ae1ba6d3f75a242eff0736f/assets/19f529159dca0345dfacaacef1a5cc96_,4573051.mp4,4573052.mp4,4573050.mp4,4573048.mp4,4573049.mp4,4573047.mp4,.urlset/master.m3u8?Expires=1663229636&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy9iZTUxYjY2YTFhZTFiYTZkM2Y3NWEyNDJlZmYwNzM2Zi9hc3NldHMvMTlmNTI5MTU5ZGNhMDM0NWRmYWNhYWNlZjFhNWNjOTZfLDQ1NzMwNTEubXA0LDQ1NzMwNTIubXA0LDQ1NzMwNTAubXA0LDQ1NzMwNDgubXA0LDQ1NzMwNDkubXA0LDQ1NzMwNDcubXA0LC51cmxzZXQvbWFzdGVyLm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NjMyMjk2MzZ9fX1dfQ__&Signature=sXglQlXAcqFhScV8ZjjfxCVVOinB-zcF1~ShZsxwECAHnv-Hmr51JZXfb5C4YvNovKUHyTtjuCSU3TDPmBeoYBIxsyCIUEvKShlFk8w8Up8PkJrLqApEf70RA~7uqrgcaN-x8TqJPcP429UWnC1ni5tSf5nwz2Wjgwjzc9pB7eVUA5F5QUmNTKqaO9WWWx542mr9XHbLHGp8hOeBxI4k~hbhAYpq1NumtB7wRFVgfn2KxYYqeoHeyIe2Ijg72fiKZd0Rad9hgYoLZgt6-IWpRO1NZ94vN1JxxJchj4h9tDKEVQCyBUNs2ZOwiEEZ~alCgoIolG-vXFxpUeZuGwCvGA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA (adaptive_hls/jpn/-)
[ERROR] Found variable '${height}' in fileName but no values was internally found!
[INFO] Downloading skipped!
[INFO] Subtitle downloaded: [CR] Cinderella Chef (Season 3) - S01E01 [${height}p].07.ara.Arabic.ass
[INFO] Skip muxing since no vids are downloaded
undefined:1

SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at loadData (C:\snapshot\multi-downloader-nx\lib\modules\module.downloadArchive.js)
    at downloaded (C:\snapshot\multi-downloader-nx\lib\modules\module.downloadArchive.js)
    at Crunchy.<anonymous> (C:\snapshot\multi-downloader-nx\lib\crunchy.js)
    at step (C:\snapshot\multi-downloader-nx\lib\crunchy.js)
    at Object.next (C:\snapshot\multi-downloader-nx\lib\crunchy.js)
    at fulfilled (C:\snapshot\multi-downloader-nx\lib\crunchy.js)

**Comment by AnidlSupport** [comment]
Can you try do delete the archive.json file in the config folder?

**Comment by kokoboko5** [comment]
> Can you try do delete the archive.json file in the config folder?

Thank you very much

**It's working now**
