### ISSUE TITLE
BUG - how to make portuguese audio first.

### ISSUE THREAD

**Issue by levaculik2** [anidl/multi-downloader-nx#395]
### Program version

3.1.0

### Operating System

Linux

### Type

Cli

### Service

Funimation

### Command used

node index.js --service funi -s 103522 -e 0027 -q 0 --dubLang por jpn --dlsubs "all" --defaultAudio "por" 

### Show ID

103522

### Episode

27

### Console Output

I would like to know how I can make the Portuguese audio first and the Japanese audio second.
As you can see, I'm putting the Portuguese audio first, but in the end, the Japanese audio is first, as you can see in the mediainfo image.
![toolfunimationerror](https://user-images.githubusercontent.com/57818248/193472700-4cbd474b-a95e-4720-b6f1-911a37b226d3.png)

**Comment by AnidlSupport** [comment]
I see no need to change the order?
Maybe you can change my mind be explaining why you need the audio changes, but I don't think it's worth the effort.

Feel free to reopen this issue with your explanation.
