### ISSUE TITLE
Not an actual issue; just an "About" typo :P - replace: Download videos from Funimation a nd Crunchyroll via cli. w/ Download videos from Funimation and Crunchyroll via cli.

### ISSUE THREAD

**Issue by San3-Cod3** [anidl/multi-downloader-nx#433]
Not an actual issue; just an "About" typo :P - replace: Download videos from Funimation a nd Crunchyroll via cli. w/ Download videos from Funimation and Crunchyroll via cli.

OCD - it was bugging me and I can't submit pull requests for an "About" section edit xD

**Comment by AnidlSupport** [comment]
Done and thanks for the tip.
