### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by kokoboko5** [anidl/multi-downloader-nx#445]
### Program version

3.1.0

### Operating System

Windows

### Type

Cli

### Service

Crunchyroll

### Command used

aniDL --service "crunchy" -s %N% -e %E% --skipdl --novids --noaudio --dlsubs ar

### Show ID

GRGGCV3PJ

### Episode

2

### Console Output

=== Multi Downloader NX 3.1.0 ===

[INFO] USER: ******** (********@*****.***)
[ERROR] HTTPError 503: Service Unavailable
[ERROR] Body: no healthy upstream
[ERROR] Authentication CMS token failed!
[ERROR] Authentication required!
Press any key to continue . . .

**Comment by Han98** [comment]
I think there is problem with crunchyroll itself, on twitter People are writing that the app also doesnt work

**Comment by XxUnkn0wnxX** [comment]
ya i think their API is down, you can still watch videos if you click on the links from the simulcastcalendar directly however navigating to other seasons etc is down atm..
