### ISSUE TITLE
CR Dub changes

### ISSUE THREAD

**Issue by mangohugo** [anidl/multi-downloader-nx#448]
Crunchyroll added the option to change the audio.
Download no longer works.

![213499420-4a441aa9-9d38-41fa-a0f4-a8d23f5cdb91 1](https://user-images.githubusercontent.com/72863602/213544474-b8db2d6c-cfe0-4186-ae06-e5b77bb9f111.png)

**Comment by AnimeDL** [comment]
Could you give me your download logs? I'm oddly still able to download despite the Crunchyroll update (seems the v1 API still works, I'm currently looking into implementing the v2 API though)

**Comment by mangohugo** [comment]
It has settled, was a cache problem

**Comment by mangohugo** [comment]
![Unbenannt](https://user-images.githubusercontent.com/72863602/213774511-794362db-aeea-40a5-917a-91aa366a1ca7.png)

**Comment by AnimeDL** [comment]
It should be working again, Crunchyroll is having a hard time deciding if they want to disable the v1 API or not, either way, we are working on porting it to the v2 API

**Comment by StrPlayer** [comment]
> It should be working again, Crunchyroll is having a hard time deciding if they want to disable the v1 API or not, either way, we are working on porting it to the v2 API

Is there an ETA on then this update will roll out?

**Comment by AnimeDL** [comment]
> > It should be working again, Crunchyroll is having a hard time deciding if they want to disable the v1 API or not, either way, we are working on porting it to the v2 API
> 
> Is there an ETA on then this update will roll out?

We just released a temporary fix as a pre-release of 3.2, you can go ahead and use that in the meantime

**Comment by StrPlayer** [comment]
> > > It should be working again, Crunchyroll is having a hard time deciding if they want to disable the v1 API or not, either way, we are working on porting it to the v2 API
> > 
> > 
> > Is there an ETA on then this update will roll out?
> 
> We just released a temporary fix as a pre-release of 3.2, you can go ahead and use that in the meantime

Great, thank you

**Comment by AnimeDL** [comment]
We just released a complete fix with version 3.3, things should be back to normal, and in some areas better than ever
