### ISSUE TITLE
HTTPError 502: Bad Gateway

### ISSUE THREAD

**Issue by Kazuma98** [anidl/multi-downloader-nx#449]
### Program version

3.1.0

### Operating System

Windows

### Type

Gui

### Service

Crunchyroll

### Command used

Download

### Show ID

G0XHWM5Q4

### Episode

3

### Console Output

[ERROR] HTTPError 502: Bad Gateway
[ERROR] Body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>502 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The Lambda function returned invalid JSON: The JSON output must be an object type.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: W-MjFvO0buEVtS8bwbOR25klK2RJ7z9PKA-tyUktzYyVLZMZQH03yg==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
[ERROR] Request Stream URLs FAILED!

### Additional Information

```Text
This error also exist on cli version
```

**Comment by kokoboko5** [comment]
I have the same problem

**Comment by AnidlSupport** [comment]
Crunchyroll changed their API. We are working on a fix.

**Comment by Kazuma98** [comment]
Download works again on my end

**Comment by AnimeDL** [comment]
Oddly looks like they reinstated the v1 API again, either way, we are still working on porting it to the v2 API

**Comment by Mytic-Slander** [comment]
> Estranhamente, parece que eles restabeleceram a API v1 novamente, de qualquer forma, ainda estamos trabalhando para transferi-la para a API v2

i have this error:

[ERROR] HTTPError 502: Bad Gateway
[ERROR] Body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>502 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The Lambda function returned invalid JSON: The JSON output must be an object type.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: C1OWnPLJl_AiGbNv17ZbtBjOmSQ6Y7WQlhnxHmKSclU7mEKE5boSFg==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
[ERROR] Request Stream URLs FAILED!
[ERROR] Unable to download selected episode 129

**Comment by AnimeDL** [comment]
We just released a temporary fix as a pre-release of 3.2, you can go ahead and use that in the meantime

**Comment by kokoboko5** [comment]
> Contributor

**Thank you!** ❤

**Comment by kokoboko5** [comment]
> We just released a temporary fix as a pre-release of 3.2, you can go ahead and use that in the meantime

**Thank you!** ❤

**Comment by AnimeDL** [comment]
We just released a complete fix with version 3.3, things should be back to normal, and in some areas better than ever
