### ISSUE TITLE
Video not available 3.2.0

### ISSUE THREAD

**Issue by TheRhop** [anidl/multi-downloader-nx#450]
### Program version

3.2.0

### Operating System

Windows

### Type

Cli

### Service

Crunchyroll

### Command used

.\aniDL --service crunchy -e GG1U2GDVN -q 0 

### Show ID

GYNV9DP2R

### Episode

GG1U2GDVN

### Console Output

=== Multi Downloader NX 3.2.0 ===

[INFO] USER: <redacted>
[INFO] Your Country: CA

[INFO] Requested object ID: GG1U2GDVN
 ✓[S:GYNQCJG7X|E:GG1U2GDVN|EPI.888688] My Hero Academia Season 6 (Dub) - 127 - Hellish Hell [23m50s, DUB, STREAM]

[WARN] Video not available!
[ERROR] Unable to download selected episode 127

**Comment by AnimeDL** [comment]
Just tested and this is fixed in the upcoming release, I'll update here when we release it. In the meantime, I believe the following command should work:
```
.\aniDL --service crunchy -s GYNQCJG7X -e 127
```

**Comment by AnimeDL** [comment]
We just released version 3.3, things should be back to normal, and in some areas better than ever
