### ISSUE TITLE
BUG (Anime title + episode number on the command page)

### ISSUE THREAD

**Issue by kokoboko5** [anidl/multi-downloader-nx#452]
### Program version

3.3.0

### Operating System

Windows

### Type

Cli

### Service

Crunchyroll

### Command used

aniDL --service "crunchy" -s %N% -e %E% --skipdl --novids --noaudio --dlsubs ar

### Show ID

G649C7EGD

### Episode

1

### Console Output

🛑The anime title does not appear in the new version, as well as the episode number

Enter the ID of the Anime:G649C7EGD
Enter the episode number:1

=== Multi Downloader NX 3.2.0 ===

[S:G649C7EGD] The Misfit of Demon King Academy Ⅱ (Season: 2) [SIMULCAST, SUB]
  - Subtitles: en, es-419, es-ES, pt, fr, de, ar, it, ru
 ✓[01|E:GD9UVX0VW] ☆ 1 - A Lesson by God [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es-ES, pt, fr, de, ar, it, ru

=== Multi Downloader NX 3.3.0 ===

[Z:undefined]
 ✓[01|E:GD9UVX0VW] ☆ A Lesson by God [23m40s, SUB, STREAM]
    - Versions: ja
    - Subtitles: en, es-419, es-ES, pt, fr, de, ar, it, ru

🔽🔽🔽🔽
Previously
[S:G649C7EGD] The Misfit of Demon King Academy Ⅱ (Season: 2) [SIMULCAST, SUB]
 ✓[01|E:GD9UVX0VW] ☆ 1 - A Lesson by God [23m40s, SUB, STREAM]

Now
[Z:undefined]
 ✓[01|E:GD9UVX0VW] ☆ A Lesson by God [23m40s, SUB, STREAM]

**Comment by AnimeDL** [comment]
I can confirm the bug, and it is fixed with the next release

**Comment by kokoboko5** [comment]
> I can confirm the bug, and it is fixed with the next release

Thank you ^^

**Comment by AnimeDL** [comment]
As the previous 2 things say, I've gone ahead and released version 3.3.1 which addresses this issue
