### ISSUE TITLE
nosubs flag not working

### ISSUE THREAD

**Issue by RichardArc** [anidl/multi-downloader-nx#457]
### Program version

3.3.2

### Operating System

Windows

### Type

Cli

### Service

Crunchyroll

### Command used

aniDL.exe --service crunchy --srz GMEHME849 -q 1 -e 1 --dubLang jpn --noSubs

### Show ID

GMEHME849

### Episode

1

### Console Output

=== Multi Downloader NX 3.3.2 ===

[INFO] USER: RichardArc (email@email.com)
[INFO] Your Country: US

[Z:GMEHME849] Handyman Saitou in another world (Seasons: 2, EPs: 4) [SIMULCAST, DUB]
  - Subtitles: en, es-419, es-ES, pt, fr, de, ar, it, ru
  [S:GYNQCJP85] Handyman Saitou in another world (Season: 1) [SIMULCAST, DUB]
    - Versions: un
    - Subtitles: en, es-419, es-ES, pt, fr, de, ar, it, ru
  [S:G6ZXCM0XW] Handyman Saitou in another world (English Dub) (Season: 1) [SIMULCAST, DUB]
    - Subtitles: en
[INFO] Your Country: US

[E1] Handyman Saitou in another world - Season 1 - Handyman, Saitou [Japanese, ☆ English]
[E2] Handyman Saitou in another world - Season 1 - What Saitou Can Do [Japanese]
[E3] Handyman Saitou in another world - Season 1 - Adventures in the Great Labyrinth [☆ Japanese]
[WARN] Couldn't find versions on some episodes, fell back to old method.

------------------------------

[S1E1] - Handyman, Saitou [✓ Japanese]
[INFO] Requesting: [GK9U3XP91] Handyman Saitou in another world - 1 - Handyman, Saitou
[INFO] Your Country: US

[INFO] Selecting raw stream
[INFO] Full stream found! (✓1: adaptive_hls/jpn/- )
[INFO] Full stream found! ( 2: download_hls/jpn/- )
[INFO] Full stream found! ( 3: multitrack_adaptive_hls_v2/jpn/- )
[INFO] Full stream found! ( 4: vo_adaptive_hls/jpn/- )
[INFO] Downloading video...
[INFO] Playlists URL: https://pl.crunchyroll.com/evs3/c107c9e5e389fe22ef140101acf6b5f6/assets/209191eca7a84c68bf72c44a3dbe6dfc_,4907899.mp4,4907900.mp4,4907898.mp4,4907896.mp4,4907897.mp4,.urlset/master.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy9jMTA3YzllNWUzODlmZTIyZWYxNDAxMDFhY2Y2YjVmNi9hc3NldHMvMjA5MTkxZWNhN2E4NGM2OGJmNzJjNDRhM2RiZTZkZmNfLDQ5MDc4OTkubXA0LDQ5MDc5MDAubXA0LDQ5MDc4OTgubXA0LDQ5MDc4OTYubXA0LDQ5MDc4OTcubXA0LC51cmxzZXQvbWFzdGVyLm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NzQ3Njk5MjN9fX1dfQ__&Signature=YFoPLaXL~sDMyks87AJU42mprZvaY~iuO6BbSJJopRK2GlPKrBUe2PrRiTCL7207p9eJbX3S2AFPffWvYDTnBtU0arACs~pcGMyF~OY5tjOKiW44GpSqB76MBFnqtsyV1Qs4LuFaRzDI5O7VsYL8yrNKIy6wVCvIkaWH9sXay2Zrr~u~zQ7TerzurKxlYZtUAsrjlwpZ9X~pe54yMBWMB1BqKCKFauGC4m4JBvhxqQf1qTweG~kUYX01K1WDzdev5znwAvNAKuNaMKU~K1IYTdJBS9oMD9JEv4ev8dwBckJbJpFATmFQQOvUxbdijZMhdTbUJHk7mpoEcb-M6gBf5A__&Key-Pair-Id=APKAJMWSQ5S7ZB3ME5VA (adaptive_hls/jpn/-)
[INFO] Servers available:
        pl.crunchyroll.com
[INFO] Available qualities:
        [1] 428x240 (549KiB/s)
        [2] 640x360 (1067KiB/s)
        [3] 848x480 (2036KiB/s)
        [4] 1280x720 (4017KiB/s)
        [5] 1920x1080 (7909KiB/s)
[INFO] Selected quality: 428x240 @ pl.crunchyroll.com
[INFO] Stream URL: https://pl.crunchyroll.com/evs3/c107c9e5e389fe22ef140101acf6b5f6/assets/209191eca7a84c68bf72c44a3dbe6dfc_4907897.mp4/index-v1-a1.m3u8?res=428x240&Expires=1674780777&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy9jMTA3YzllNWUzODlmZTIyZWYxNDAxMDFhY2Y2YjVmNi9hc3NldHMvMjA5MTkxZWNhN2E4NGM2OGJmNzJjNDRhM2RiZTZkZmNfNDkwNzg5Ny5tcDQvaW5kZXgtdjEtYTEubTN1OD9yZXM9NDI4eDI0MCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY3NDc4MDc3N319fV19&Signature=FQaarg6PEQ9mDETyqV0us5Sd5M9WwE-hqnUCeL3vWvmzPZeY8UBrVQfRZMPDz20zxW57rWXIhqC2e-iOY2ARRNhBFSPO7ssbdI8F4SG4hu~wpuZSa5rK0WB7i9Km5A0yygHigJQO6moehaTVCd-9NDn7lW4FgLR75HOok3hWstV7w2TNDYjx3Db9Vkh5YsahDZ94BT1k4CmylgqzFofe3WYcim~BNeNYqj5yNSg2i7qK0k3Wu1pH5m4tPl1b4chu10yHHI~mNXryL3EWMAosNQfFrqgoI0USOBvndITNTc15rkFSi20KD1smS1mcMkid7KZTEqQ7BYwfyHCL2ygBSQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3ME5VA
[INFO] Output filename: [CR] Handyman Saitou in another world - S01E01 [240p].Japanese
[INFO] Total parts in stream: 355 (36*10)
[INFO] Saving stream to «C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].Japanese.ts»...
[INFO] 10 of 355 parts downloaded [3%] (35s | 2.6Mb/s)
[INFO] 20 of 355 parts downloaded [6%] (28s | 3.8Mb/s)
[INFO] 30 of 355 parts downloaded [8%] (25s | 4.0Mb/s)
[INFO] 40 of 355 parts downloaded [11%] (23s | 3.7Mb/s)
[INFO] 50 of 355 parts downloaded [14%] (22s | 3.9Mb/s)
[INFO] 60 of 355 parts downloaded [17%] (21s | 4.0Mb/s)
[INFO] 70 of 355 parts downloaded [20%] (20s | 4.1Mb/s)
[INFO] 80 of 355 parts downloaded [23%] (19s | 4.1Mb/s)
[INFO] 90 of 355 parts downloaded [25%] (18s | 4.1Mb/s)
[INFO] 100 of 355 parts downloaded [28%] (18s | 4.0Mb/s)
[INFO] 110 of 355 parts downloaded [31%] (17s | 4.1Mb/s)
[INFO] 120 of 355 parts downloaded [34%] (16s | 4.1Mb/s)
[INFO] 130 of 355 parts downloaded [37%] (16s | 4.1Mb/s)
[INFO] 140 of 355 parts downloaded [39%] (15s | 4.2Mb/s)
[INFO] 150 of 355 parts downloaded [42%] (14s | 4.3Mb/s)
[INFO] 160 of 355 parts downloaded [45%] (14s | 4.3Mb/s)
[INFO] 170 of 355 parts downloaded [48%] (13s | 4.4Mb/s)
[INFO] 180 of 355 parts downloaded [51%] (12s | 4.3Mb/s)
[INFO] 190 of 355 parts downloaded [54%] (12s | 4.4Mb/s)
[INFO] 200 of 355 parts downloaded [56%] (11s | 4.3Mb/s)
[INFO] 210 of 355 parts downloaded [59%] (10s | 4.3Mb/s)
[INFO] 220 of 355 parts downloaded [62%] (9s | 4.3Mb/s)
[INFO] 230 of 355 parts downloaded [65%] (9s | 4.2Mb/s)
[INFO] 240 of 355 parts downloaded [68%] (8s | 4.3Mb/s)
[INFO] 250 of 355 parts downloaded [70%] (8s | 4.2Mb/s)
[INFO] 260 of 355 parts downloaded [73%] (7s | 4.3Mb/s)
[INFO] 270 of 355 parts downloaded [76%] (6s | 4.4Mb/s)
[INFO] 280 of 355 parts downloaded [79%] (5s | 4.3Mb/s)
[INFO] 290 of 355 parts downloaded [82%] (5s | 4.4Mb/s)
[INFO] 300 of 355 parts downloaded [85%] (4s | 4.4Mb/s)
[INFO] 310 of 355 parts downloaded [87%] (3s | 4.4Mb/s)
[INFO] 320 of 355 parts downloaded [90%] (2s | 4.4Mb/s)
[INFO] 330 of 355 parts downloaded [93%] (2s | 4.4Mb/s)
[INFO] 340 of 355 parts downloaded [96%] (1s | 4.4Mb/s)
[INFO] 350 of 355 parts downloaded [99%] (0s | 4.4Mb/s)
[INFO] 355 of 355 parts downloaded [100%] (0s | 4.4Mb/s)
[INFO] Subtitle downloaded: [CR] Handyman Saitou in another world - S01E01 [240p].01.eng.English.ass
[INFO] Subtitle downloaded: [CR] Handyman Saitou in another world - S01E01 [240p].02.spa-419.Latin American Spanish.ass
[INFO] Subtitle downloaded: [CR] Handyman Saitou in another world - S01E01 [240p].03.spa-ES.European Spanish.ass
[INFO] Subtitle downloaded: [CR] Handyman Saitou in another world - S01E01 [240p].04.por.Brazilian Portuguese.ass
[INFO] Subtitle downloaded: [CR] Handyman Saitou in another world - S01E01 [240p].05.fra.French.ass
[INFO] Subtitle downloaded: [CR] Handyman Saitou in another world - S01E01 [240p].06.deu.German.ass
[INFO] Subtitle downloaded: [CR] Handyman Saitou in another world - S01E01 [240p].07.ara.Arabic.ass
[INFO] Subtitle downloaded: [CR] Handyman Saitou in another world - S01E01 [240p].08.ita.Italian.ass
[INFO] Subtitle downloaded: [CR] Handyman Saitou in another world - S01E01 [240p].09.rus.Russian.ass

[INFO] Subtitles: en, es-419, es-ES, pt, fr, de, ar, it, ru (Total: 9)
[INFO] Required fonts: Trebuchet MS, Verdana, Times New Roman, Georgia, Arial, Tahoma, Impact, Rubik, Adobe Arabic, Comic Sans MS (Total: 10)
[INFO][mkvmerge] Started merging

> "mkvmerge" -o "C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].mkv" --no-date --disable-track-statistics-tags --engage no_variable_data --video-tracks 0 --audio-tracks 1 --track-name 0:"Japanese [Uncut]" --language 1:jpn --default-track 1:0 "C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].Japanese.ts" --track-name 0:"English" --language 0:"eng" --default-track 0 "C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].01.eng.English.ass" --track-name 0:"Latin American Spanish" --language 0:"spa-419" --default-track 0:0 "C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].02.spa-419.Latin American Spanish.ass" --track-name 0:"European Spanish" --language 0:"spa-ES" --default-track 0:0 "C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].03.spa-ES.European Spanish.ass" --track-name 0:"Brazilian Portuguese" --language 0:"por" --default-track 0:0 "C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].04.por.Brazilian Portuguese.ass" --track-name 0:"French" --language 0:"fra" --default-track 0:0 "C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].05.fra.French.ass" --track-name 0:"German" --language 0:"deu" --default-track 0:0 "C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].06.deu.German.ass" --track-name 0:"Arabic" --language 0:"ara" --default-track 0:0 "C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].07.ara.Arabic.ass" --track-name 0:"Italian" --language 0:"ita" --default-track 0:0 "C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].08.ita.Italian.ass" --track-name 0:"Russian" --language 0:"rus" --default-track 0:0 "C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].09.rus.Russian.ass" --no-attachments
mkvmerge v68.0.0 ('The Curtain') 64-bit
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].Japanese.ts': Using the demultiplexer for the format 'MPEG transport stream'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].01.eng.English.ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].02.spa-419.Latin American Spanish.ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].03.spa-ES.European Spanish.ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].04.por.Brazilian Portuguese.ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].05.fra.French.ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].06.deu.German.ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].07.ara.Arabic.ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].08.ita.Italian.ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].09.rus.Russian.ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].Japanese.ts' track 0: Using the output module for the format 'AVC/H.264 (unframed)'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].Japanese.ts' track 1: Using the output module for the format 'AAC'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].01.eng.English.ass' track 0: Using the output module for the format 'SSA/ASS text subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].02.spa-419.Latin American Spanish.ass' track 0: Using the output module for the format 'SSA/ASS text subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].03.spa-ES.European Spanish.ass' track 0: Using the output module for the format 'SSA/ASS text subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].04.por.Brazilian Portuguese.ass' track 0: Using the output module for the format 'SSA/ASS text subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].05.fra.French.ass' track 0: Using the output module for the format 'SSA/ASS text subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].06.deu.German.ass' track 0: Using the output module for the format 'SSA/ASS text subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].07.ara.Arabic.ass' track 0: Using the output module for the format 'SSA/ASS text subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].08.ita.Italian.ass' track 0: Using the output module for the format 'SSA/ASS text subtitles'.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].09.rus.Russian.ass' track 0: Using the output module for the format 'SSA/ASS text subtitles'.
The file 'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].mkv' has been opened for writing.
'C:\Users\zephk\Downloads\332multinx\multi-downloader-nx-windows64-cli\videos\[CR] Handyman Saitou in another world - S01E01 [240p].Japanese.ts' track 0: Extracted the aspect ratio information from the video bitstream and set the display dimensions to 428/241.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 1 second.
[INFO][mkvmerge Done]

### Additional Information

```Text
Also if I have fonts downloaded mkvmerge errors out with
`The command line is too long.
[INFO][mkvmerge] Mkvmerge finished with at least one warning`
and no final mkv
Havent had this particular issue with other shows, but maybe this one just uses a lot of fonts so it makes the command really long? Was trying to --nosubs to make command a bit shorter (had fonts for a while, forgot they are optional) but noticed it still downloaded and muxed them
```

**Comment by AnimeDL** [comment]
It does not look like noSubs is even implemented in the Crunchyroll downloader, only Funimation... Not sure why the documentation says it is for both. I probably can add it, but `--skipSubMux` exists and can be used for your purpose. Would you like that feature added to the Crunchyroll downloader?

**Comment by RichardArc** [comment]
Yeah I saw `--skipSubMux` and used that.
I can't say I'd really particularly care if it was added or not since there is `--skipSubMux` I just didn't know it was an option.
Pretty minor thing, but figured I'd someone aware, even if its just to edit the doc
