### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by kokoboko5** [anidl/multi-downloader-nx#459]
### Program version

3.3.2

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

aniDL --service "crunchy" -s %N% -e %E% --skipdl --novids --noaudio --dlsubs ar

### Show ID

GR3VC2PJ5

### Episode

61

### Console Output

```Shell
=== Multi Downloader NX 3.3.2 ===

[INFO] USER: ********** (**********@******.***)
[INFO] Your Country: **

[S:GR3VC2PJ5] Digimon Ghost Game (Season: 1) [SIMULCAST, SUB]
  - Versions: ja
  - Subtitles: en, es-419, es-ES, pt, fr, de, ar, it, ru
 ✓[61|E:G9DUE3WVW] ☆ 61 - Resurrection [23m17s, SUB, STREAM]
    - Versions: ja
    - Subtitles: en, es-419, es-ES, pt, fr, de, ar, it, ru

[INFO] Requesting: [G9DUE3WVW] Digimon Ghost Game - 61 - Resurrection
[INFO] Your Country: **

[ERROR] HTTPError 503: Service Unavailable
[ERROR] Body: {"code":"content.get_video_streams_v2.cms_service_error","context":[]}
[ERROR] Request Stream URLs FAILED! Attempting fallback
[ERROR] HTTPError 503: Service Unavailable
[ERROR] Body: {"code":"content.get_video_streams_v2.cms_service_error","context":[]}
[ERROR] Fallback Request Stream URLs FAILED!
[ERROR] Unable to download selected episode 61
```

### Additional Information

🔴**This problem appears to me from time to time**🔴

_No response_

**Comment by AnimeDL** [comment]
503 means service temporarily unavailable, which means Crunchy was likely down temporarily for that request. The command also appears to work for me

**Comment by kokoboko5** [comment]
> 503 means service temporarily unavailable, which means Crunchy was likely down temporarily for that request. The command also appears to work for me

I check every 6 minutes on untranslated episodes to see if subtitles are available or not

like
______________
Del ".\config\archive.json"
:loop

aniDL --service "crunchy" -s GYGGCV3M0 -e 2 --skipdl --novids --noaudio --dlsubs ar
aniDL --service "crunchy" -s G649C7EGD -e 4 --skipdl --novids --noaudio --dlsubs ar
aniDL --service "crunchy" -s GYGGCV3KJ -e 4 --skipdl --novids --noaudio --dlsubs ar
aniDL --service "crunchy" -s GRWEC3GX8 -e 16 --skipdl --novids --noaudio --dlsubs ar

 timeout /t 360
 goto loop
______________

Do you think this is the cause of this problem?

**Comment by AnimeDL** [comment]
I haven't done something like that to know for sure, but I would imagine they might prevent you from sending requests if you send too many requests, in which case, maybe add a delay in between the commands and see if that resolves your issue?

**Comment by kokoboko5** [comment]
> I haven't done something like that to know for sure, but I would imagine they might prevent you from sending requests if you send too many requests, in which case, maybe add a delay in between the commands and see if that resolves your issue?

I did what you said

Until this time, no problem appeared

Thank you ^^
