### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by StrPlayer** [anidl/multi-downloader-nx#480]
### Program version

3.4.0

### Operating System

Windows

### Type

GUI

### Service

Crunchyroll

### Command used

NON

### Show ID

NON

### Episode

NON

### Console Output

```Shell
GUI server started on port 3000
[WS] Connection to public ws from '::1'
[WS] Connection from '::1'
[WS] Connection from '::1'
[INFO] Token not set!

[ERROR] HTTPError 404: Not Found
```

### Additional Information

Not sure what this issue is, but never happened until now

**Comment by StrPlayer** [comment]
Kaspersky detects it has malware and blocks all connections to the program

**Comment by AnimeDL** [comment]
Not sure why it would detect the software as malware. Especially since electron is no longer in the program which is what caused the false positive with Windows Defender. Either way, it's a false positive. Does it still block it if you compile and run it from source yourself?
