### ISSUE TITLE
[Bug] : Issue downloading movies fro crunch 

### ISSUE THREAD

**Issue by storm134** [anidl/multi-downloader-nx#482]
### Program version

3.4.0

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

node index.js --service crunchy --flm G64PV1Z3R

### Show ID

G64PV1Z3R

### Episode

1

### Console Output

```Shell
Found movie lists:
  [F:G64PV1Z3R|FLM.275947] Dragon Age: Dawn of the Seeker [1h31m29s, DUB]
    [M:GJKF2ZVVW] ☆ Dragon Age: Dawn of the Seeker [1h31m29s, DUB]
    [M:GXMFQ8MNV] ☆ Dragon Age: Dawn of the Seeker [1h29m12s, DUB]
```

### Additional Information

trying to figure out how to download a movie it is dragon age dawn of the seeker. can find the id no problem but can't get the proper string. first time trying a movie and help would be great

**Comment by AnimeDL** [comment]
Technically there is a `--flm/--movie-listing`, but there is oddly no download logic in the code for it, I should probably fix that, especially since I was under the impression you could download movies with -e... I'll work on a fix

**Comment by AnimeDL** [comment]
Alright, I've gone ahead and pushed a few commits that should allow for downloading using `-e`, since I haven't added download logic to `--flm/--movie-listing` just yet, you can use that to get the ID of the movie itself, (in this case GJKF2ZVVW/GXMFQ8MNV depending on the language), then use that ID with `-e` in order to download the movie itself. 
example: 
```
node index.js --service crunchy --e GJKF2ZVVW
```

**Comment by storm134** [comment]
thanks for the fast reponose but still having an issue. see below. not sure if t is because this on is an odd entry in the database tried both GJKF2ZVVW/GXMFQ8MNV same error.


C:\multi-downloader-nx-master\lib>node index.js --service crunchy --nocleanup -e GJKF2ZVVW

=== Multi Downloader NX 3.4.0 ===

USER: storm134 (storm134@xxxx)
Your Country: CA

Requested object ID: GJKF2ZVVW
C:\multi-downloader-nx-master\lib\crunchy.js:1408
                            epMeta.data[0].playback = item.streams_link;
                                                    ^

TypeError: Cannot set properties of undefined (setting 'playback')
    at Crunchy.<anonymous> (C:\multi-downloader-nx-master\lib\crunchy.js:1408:53)
    at step (C:\multi-downloader-nx-master\lib\crunchy.js:67:23)
    at Object.next (C:\multi-downloader-nx-master\lib\crunchy.js:48:53)
    at fulfilled (C:\multi-downloader-nx-master\lib\crunchy.js:39:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.7.0

C:\multi-downloader-nx-master\lib>

**Comment by AnimeDL** [comment]
You need to update to the latest commit currently to get past the issue (version 3.4.3), I have not created a new release yet, since I haven't implemented downloading capability with --flm just yet.

**Comment by AnimeDL** [comment]
Closing because this was resolved in the recent releases
