### ISSUE TITLE
Unable to download show

### ISSUE THREAD

**Issue by CBecker100** [anidl/multi-downloader-nx#486]
Hi there,
I'm unable to download the show "[You're being summoned Azazel](https://www.funimation.com/shows/youre-being-summoned-azazel/)" from Funimation because it has "english" (and only "english", no other language) instead of "eng" as language tag and I can not force the downloader, be it CLI or GUI to use the "english" tag.
Is there a way to fix this? Or am I missing something?

**Comment by AnimeDL** [comment]
I started to look into this, and I noticed that this series actually has no available streams on either crunchy or Funimation. I'm not sure if that was the issue at the time of you posting this issue, but it is now. Feel free to re-open if you have another example of this
