### ISSUE TITLE
[BUG]: Defaulting to Ethernet as a sort of lan bridge rather than wifi

### ISSUE THREAD

**Issue by TenyamaGain** [anidl/multi-downloader-nx#488]
### Program version

3.4.0

### Operating System

Windows

### Type

GUI

### Service

Crunchyroll

### Command used

N/A

### Show ID

All Shows

### Episode

Download All

### Console Output

```Shell
N/A
```

### Additional Information

I previous wrote a bug, but closed it -- it was that it was defaulting to a CH IP address, which was odd to me -- only for me to realize it was passing through my switch, and exiting out my other pc that had a VPN on -- rather than using onboard wifi, for some reason. I have to disable ethernet in ordered for it to function properly, or else it's slow, wrong region, etc.

**Comment by AnidlSupport** [comment]
This tool will use the default connection on your device. There is no way for us (as far as I know) to change that. You might need to change the default connection settings for this application/node.js.
