### ISSUE TITLE
[BUG]: --skipmux doest not working

### ISSUE THREAD

**Issue by adrianpruneda** [anidl/multi-downloader-nx#490]
### Program version

3.4.4

### Operating System

Linux

### Type

CLI

### Service

Crunchyroll

### Command used

aniDL --skipmux --service crunchy --dubLang jpn --dlsubs es-419 -q 1 --fileName ...

### Show ID

G9VHN9P43

### Episode

1

### Console Output

```Shell
...
```

### Additional Information

I want keep .ts and .ass, but without make a .mkv file, but --skipmux not work ):

**Comment by adrianpruneda** [comment]
Ah, there is no option in the code for crunchy, only for funi.

**Comment by adrianpruneda** [comment]
Fixed making custom binary, thanks.

**Comment by AnimeDL** [comment]
If you're making the changes, feel free to open a PR with them

**Comment by AnimeDL** [comment]
In an upcoming version I have added support for `--skipmux`
