### ISSUE TITLE
[BUG]: EACCES on download

### ISSUE THREAD

**Issue by Kapppa** [anidl/multi-downloader-nx#505]
### Program version

4.3.0

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

aniDL --service crunchy --srz GVDHX8504 -e 1

### Show ID

All

### Episode

1

### Console Output

```Shell
[ERROR] RequestError: EACCES
[ERROR] CAN'T FETCH VIDEO PLAYLISTS!
Subtitle downloaded: undefined.01.eng.English.ass
Subtitle downloaded: undefined.02.spa-419.Latin American Spanish.ass
Subtitle downloaded: undefined.03.spa-ES.European Spanish.ass
Subtitle downloaded: undefined.04.por.Brazilian Portuguese.ass
Subtitle downloaded: undefined.05.fra.French.ass
Subtitle downloaded: undefined.06.deu.German.ass
Subtitle downloaded: undefined.07.ara.Arabic (Saudi Arabia).ass
Subtitle downloaded: undefined.08.ita.Italian.ass
Subtitle downloaded: undefined.09.rus.Russian.ass
Subtitle downloaded: undefined.10.hin.Hindi.ass
[ERROR] Unable to download selected episode 1
```

### Additional Information

All downloads fail with this error. I have tried all kstreams, they are all failing but server 4 for this error.

**Comment by AnimeDL** [comment]
EACCES in a node.js error that usually involves filesystem permissions being wrong. I find it super weird that a specific server would work but other don't considering this fact. Do you have any additional ideas/information?

**Comment by Kapppa** [comment]
I have tried working with the node directly that works, but once I use the exe it fails. I have tried older versions that works and it still doesn't work. I have moved to another drive and still fails. Could you compile an exe that console logs the error for EACCES

**Comment by AnimeDL** [comment]
I will look into it and see if I can make more verbose logging there. In the meantime, `--debug` should give me more insight on where I need to make that logging more verbose if you can run the command again with that added

**Comment by Kapppa** [comment]
If you could add a console log here of the error that would show the failure. 

I tried running via node and I worked, so this is bit odd. 

https://github.com/anidl/multi-downloader-nx/blob/8b6c488396d6280f5cb86397ee43ba29839df585/modules/module.curl-req.ts#L82

**Comment by Kapppa** [comment]
Okay, I figured it out, it is my VPN, it looks be PIA.

**Comment by AnimeDL** [comment]
Super weird, not sure how a VPN would cause it, I should test this at some point since I also use PIA. Closing as resolved for now though
