### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by dluna1150** [anidl/multi-downloader-nx#511]
### Program version

4.3.0

### Operating System

MacOS

### Type

GUI

### Service

Crunchyroll

### Command used

GUI

### Show ID

GVDHX8504

### Episode

1

### Console Output

```Shell
[ERROR] Part 8 download error:
	Timeout awaiting 'request' for 15000ms
[ERROR] Part 7 download error:
	Timeout awaiting 'request' for 15000ms
[ERROR] Part 5 download error:
	Timeout awaiting 'request' for 15000ms
[ERROR] Part 1 download error:
	Timeout awaiting 'request' for 15000ms
[ERROR] Part 3 download error:
	Timeout awaiting 'request' for 15000ms
[ERROR] Part 6 download error:
	Timeout awaiting 'request' for 15000ms
[ERROR] 10 parts not downloaded
[ERROR] DL Stats: {"first":1,"total":355,"completed":0}

Subtitles downloading skipped!
[ERROR] Download error: Unable to download episode 1 from GVDHX8504
```

### Additional Information

Hi!

I'm experiencing an issue with Multi Downloader NX. When I try to download something, I receive the following error:
1Timeout awaiting 'request' for 15000ms
2[ERROR] Part 9 download error:
3    Timeout awaiting 'request' for 15000ms
4...
5[ERROR] Download error: Unable to download episode 1 from GVDHX8504
I'm using the GUI version of the tool and the error persists even when I use a VPN. My internet connection is functioning correctly and I'm not having issues with other programs.

Could you help me troubleshoot this issue?

Thank you.

**Comment by Abu3safeer** [comment]
I think this issue from server side, because I have the same issue and an issue with SSL certificate:
`write EPROTO B02A0000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:C:\Users\runneradmin\AppData\Local\Temp\pkg.24e0b2b2d51e47b9dba34c30\node\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1584:SSL alert number 40`
