### ISSUE TITLE
[Enhancement Request]: Possibility to define a default file name

### ISSUE THREAD

**Issue by rmagnussao** [anidl/multi-downloader-nx#566]
### Type

GUI

### Suggestion

If we want a personalized file name, we need to change it whenever a new item is added to the queue. It would be interesting to have this option within the settings so we can use a pre-defined pattern.
In my case, for example, I always remove the provider name. So if I'm going to download the new episodes of 10 items, I need to adjust the name one by one.

**Comment by Jaynator495** [comment]
Set the fileName property in cli-default.yml https://github.com/anidl/multi-downloader-nx/blob/master/docs/DOCUMENTATION.md#--filename
