### ISSUE TITLE
language select always set to english default

### ISSUE THREAD

**Issue by Aiyomi-Irirako** [anidl/multi-downloader-nx#568]
hello,

I have a small problem. 
i am using the windows version with gui

when i download an episode or series from crunchyroll and add several audio tracks or subtitles, english is always set to default.
is there a way that i can set other languages to default so that they are played first?

**Comment by Jaynator495** [comment]
You can set defaultAudio is cli-defaults.yml, and that will change the default audio option

**Comment by Aiyomi-Irirako** [comment]
q: 0
nServer: 1
mp4mux: false
noCleanUp: false
dlVideoOnce: false

is present in the cli-defaults.yml.
which of these is audio and subtitles?

> You can set defaultAudio is cli-defaults.yml, and that will change the default audio option

**Comment by Aiyomi-Irirako** [comment]
ah i see
and for subtitle: is there a way to select forced subtitle not full subtile? or is this not possible?

I think that defaultsub only supports full subtitle, right?

**Comment by Jaynator495** [comment]
The answer to that is a little complex. Currently the code can't tell the difference between CC/Sign subtitles and Full subtitles if they are the same language... That may change soon, and when that happens I may add a way to identify them and set them as default.

**Comment by Aiyomi-Irirako** [comment]
I see
one last quick question, which is not in the doc.

what exactly is meant by "quality level"? 

at this point i would like to thank you for your work. most of it is really well explained and it is very easy to understand
thank you very much for the great downloader

**Comment by Jaynator495** [comment]
Quality level is up to the individual service, but it refers to all the quality's available to download from the service provider, for example CR usually looks like this: 
![image](https://github.com/anidl/multi-downloader-nx/assets/13039635/58975644-47f7-444a-8721-244b3151926d)

**Comment by Aiyomi-Irirako** [comment]
many thanks again x3333
