### ISSUE TITLE
Change GUI Defaults, YML

### ISSUE THREAD

**Issue by petenun** [anidl/multi-downloader-nx#570]
### Type

GUI

### Suggestion

I'm a new user and really like the GUI version (running under Windows). Kudos to the dev!

That said, is there any way to change the defaults such as the output directory, file naming, dub and sub languages, etc.? I find that I need to change these from the default values every time I add a new show. I've looked through the config YML files and don't see any options along these lines to change. The CLI Options doc is very detailed, but it's not clear how those options translate to GUI settings.

Any help would be appreciated.

**Comment by Jaynator495** [comment]
Output directory can be changed using `dir-path.yml` file, the rest can be changed using the `cli-defaults.yml` file, both of which can be found in the config directory. You can find the documentation with the list of values for the cli-defaults file here: https://github.com/anidl/multi-downloader-nx/blob/master/docs/DOCUMENTATION.md

**Comment by petenun** [comment]
Thanks for that information; it's very helpful. I do have a question about the cli-defaults.yml file though. The default cli-defaults.yml file reads:

q: 0
nServer: 1
mp4mux: false
noCleanUp: false
dlVideoOnce: false

Cross-referencing with the documentation, neither "mp4-mux" nor "nServer" arguments are listed in the CLI doc (although similar arguments can be found). Where do these variables come from, and are there other discrepancies or syntax differences between command line arguments and the cli-defaults.yml file?

Sorry to get picky, but I would truly like to understand the difference.

**Comment by Jaynator495** [comment]
Now that you mention it, nServer and mp4mux is a completely invalid argument, I'm not sure why that's there... Probably old versions of the arguments that were never updated in the defaults file if I had to guess. The options in the documentation are up to date and accurate, you'll notice a column for cli-defaults usage in the docs

**Comment by petenun** [comment]
LOL; Well, that explains my confusion and why things didn't click. I'll treat the current CLI document as the bible in trying to customize the GUI. Seriously, I appreciate the help.
