### ISSUE TITLE
[BUG]: Downloading Simulcast from Funimation uses Uncut Audio instead of Simulcast Audio

### ISSUE THREAD

**Issue by HumanGamer** [anidl/multi-downloader-nx#571]
### Program version

31867e216f0a2949dd704e0277c86a3d719a56e1

### Operating System

Windows

### Type

GUI

### Service

Funimation

### Command used

N/A

### Show ID

https://www.funimation.com/shows/zombie-land-saga

### Episode

2

### Console Output

```Shell
N/A
```

### Additional Information

When you download the Simulcast version of a show from Funimation, it uses the Uncut Audio. This prevents downloading the version of Zombieland Saga where the music was not dubbed. I tested with Zombieland Saga episode 2. and I set the advanced options json to use the ``simul: true`` command. The video track ends up being called Simulcast which means it is downloading the right video, just the wrong audio.

**Comment by AnimeDL** [comment]
Since Funimation no longer exists, I'm going to close this
