### ISSUE TITLE
[BUG]: Crunchyroll error 401 Unauthorized : invalid client

### ISSUE THREAD

**Issue by Thonolanj** [anidl/multi-downloader-nx#573]
### Program version

4.4.1

### Operating System

Linux

### Type

CLI

### Service

Crunchyroll

### Command used

node index.js --service 'crunchy' --numbers 2 --fileName '${showTitle}/${showTitle} - S${season}E${episode} - ${title}' -s GYE5CQMQ5 -e 14

### Show ID

GYE5CQMQ5

### Episode

14

### Console Output

```Shell
=== Multi Downloader NX 4.4.1 ===

[ERROR] HTTPError 401: Unauthorized
[ERROR] Body: {"code":"auth.obtain_access_token.client_inactive","context":[],"error":"invalid_client"}
[ERROR] Authentication failed!
[ERROR] Authentication required!
```

### Additional Information

Looks like Sony is trying to lock down again.

**Comment by Vamoelysian** [comment]
Same issue/error for me. Last worked fine on Sunday.

**Comment by AnimeDL** [comment]
Going to reopen this until I create the release

**Comment by AnimeDL** [comment]
Alright, pushed the release 4.4.3, should fix the issue.
