### ISSUE TITLE
Add Examples Of How To Write Commands 

### ISSUE THREAD

**Issue by GarouTheDevil** [anidl/multi-downloader-nx#574]
### Type

Both

### Suggestion

It would be better if you wrote down the how to use commands section in ReadMe, i mean how to write a cammand for login or DL or etc. Just some basic examples so to have an idea of how to and how Actually aniDL works
i seen that you explained the options grateful for that but also add the examples please
so Just like some people will be helpful

**Comment by AnimeDL** [comment]
That's fair, I really should write some up. In the meantime, you'll find a list of all the flags here: https://github.com/anidl/multi-downloader-nx/blob/master/docs/DOCUMENTATION.md

An example of the usage is like this (in the following examples I'll be using crunchy):
```shell
anidl --service crunchy --auth
```
^The above will ask for your username/password in order to login. 

An example for downloading could look like this:
```shell
anidl  --service crunchy --srz SERIESIDHERE -e EPISODENUMBERHERE
```
^The above will download the series with the series ID provided, and the episode number provided. You can get a better idea for these flags in the documentation.

**Comment by GarouTheDevil** [comment]
> That's fair, I really should write some up. In the meantime, you'll find a list of all the flags here: https://github.com/anidl/multi-downloader-nx/blob/master/docs/DOCUMENTATION.md
> 
> An example of the usage is like this (in the following examples I'll be using crunchy):
> 
> ```shell
> anidl --service crunchy --auth
> ```
> 
> ^The above will ask for your username/password in order to login.
> 
> An example for downloading could look like this:
> 
> ```shell
> anidl  --service crunchy --srz SERIESIDHERE -e EPISODENUMBERHERE
> ```
> 
> ^The above will download the series with the series ID provided, and the episode number provided. You can get a better idea for these flags in the documentation.

Thank you for the explanation

**Comment by Sipherdrakon** [comment]
So I know this is a bit old and not sure anyone will look at it, but I was trying to figure out how to add --dlsubs and --dubLang into the GUI as trying to put them in the cli-defaults creates function errors when trying to add to queue.

**Comment by Jaynator495** [comment]
> So I know this is a bit old and not sure anyone will look at it, but I was trying to figure out how to add --dlsubs and --dubLang into the GUI as trying to put them in the cli-defaults creates function errors when trying to add to queue.

I actually added some examples to the readme in the mpd-support branch, it just hasn't been merged yet so you actually have to switch to the mpd-support branch to see it. 
dlsubs and dubLang looks like this in cli-defaults.yml:
```yaml
dubLang: ["jpn"]
dlsubs: ["all"]
```

**Comment by AnimeDL** [comment]
Now that this is merged and there are examples, I'm going to close this.
