### ISSUE TITLE
[Feedback]: saving gui settings

### ISSUE THREAD

**Issue by StrPlayer** [anidl/multi-downloader-nx#584]
### Type

GUI

### Suggestion

Saving GUI settings for file name dub languages and sub languages I don't know if it's possible right now, if it is, please reply with how to do it

**Comment by DAREK0N** [comment]
You can already, it's a bit hidden tho. You have to go to "./config" and add the settings you want manually. Open the "cli-defaults.yml" and add your desired settings there, look at the [documentation](https://github.com/anidl/multi-downloader-nx/blob/master/docs/DOCUMENTATION.md), there is a "cli-default entry" there, simply add that + your options to the file and save it.

Example:
`dlsubs: ["de", "fr", "en", "es-ES"]` would always download the German, English, French and Spanish subtitles till I overwrite it manually.
`fileName: "${showTitle}/S${season}/${showTitle} - S${season}E${episode}"` would create a folder with the show name, a subfolder with the season number and the video file with the in the corresponding season folder. like: `AOT/S01/AOT - S01E01` (Good for Plex)
`dubLang: ["deu", "eng", "jpn"]` would always download the German, English and the Japanese dub

Hope this helps ^^

**Comment by StrPlayer** [comment]
Oh, I see my bad, thank you for showing me this
