### ISSUE TITLE
[Feedback]: Is HiDive DRM only now?

### ISSUE THREAD

**Issue by pratyushpati11** [anidl/multi-downloader-nx#585]
### Type

Both

### Suggestion

Is HiDive DRM only now? Anyone can check?

**Comment by Jaynator495** [comment]
I don't believe that it is, I haven't had a second to check but my understanding is the only thing that doesn't work is subtitles

**Comment by pratyushpati11** [comment]
> I don't believe that it is, I haven't had a second to check but my understanding is the only thing that doesn't work is subtitles

It is using Widevine in browser now.

**Comment by pratyushpati11** [comment]
Maybe there is some work around.Erai released the latest HiDive release.So maybe some APIs still non DRM?

**Comment by Jaynator495** [comment]
Yea, looks like they added Widevine to the new website, but the old API still works (for now) albeit - subtitles are broken. I'll look into fixing the old API and somehow adding the new API. 

Could you give me the specific errors you are getting when downloading so I can see if anything else has changed since the only error I'm getting is the subtitles?

**Comment by Jaynator495** [comment]
> > Yea, looks like they added Widevine to the new website, but the old API still works (for now) albeit - subtitles are broken. I'll look into fixing the old API and somehow adding the new API.
> > 
> > Could you give me the specific errors you are getting when downloading so I can see if anything else has changed since the only error I'm getting is the subtitles?
> 
> I am sorry.I can't help with that as I currently don't have HiDive.Found about this news so decided to share here.
> Btw HiDive DRM is Widevine L3 DRM.So adding L3 CDM Decryption should work.

The good news is we already did it for crunchy (just haven't released it yet), so it shouldn't be too bad to implement it for hidive if necessary

**Comment by pratyushpati11** [comment]
> > > Yea, looks like they added Widevine to the new website, but the old API still works (for now) albeit - subtitles are broken. I'll look into fixing the old API and somehow adding the new API.
> > > Could you give me the specific errors you are getting when downloading so I can see if anything else has changed since the only error I'm getting is the subtitles?
> > 
> > 
> > I am sorry.I can't help with that as I currently don't have HiDive.Found about this news so decided to share here.
> > Btw HiDive DRM is Widevine L3 DRM.So adding L3 CDM Decryption should work.
> 
> The good news is we already did it for crunchy (just haven't released it yet), so it shouldn't be too bad to implement it for hidive if necessary

Yeah seems like it will be necessary in future soon .

**Comment by pratyushpati11** [comment]
> > > Yea, looks like they added Widevine to the new website, but the old API still works (for now) albeit - subtitles are broken. I'll look into fixing the old API and somehow adding the new API.
> > > Could you give me the specific errors you are getting when downloading so I can see if anything else has changed since the only error I'm getting is the subtitles?
> > 
> > 
> > I am sorry.I can't help with that as I currently don't have HiDive.Found about this news so decided to share here.
> > Btw HiDive DRM is Widevine L3 DRM.So adding L3 CDM Decryption should work.
> 
> The good news is we already did it for crunchy (just haven't released it yet), so it shouldn't be too bad to implement it for hidive if necessary. The hardest part is going to be implenting everything else since just about everything changed in the new API, lol

Is there any way to get just Audio from HiDive?

**Comment by pratyushpati11** [comment]
> > > Yea, looks like they added Widevine to the new website, but the old API still works (for now) albeit - subtitles are broken. I'll look into fixing the old API and somehow adding the new API.
> > > Could you give me the specific errors you are getting when downloading so I can see if anything else has changed since the only error I'm getting is the subtitles?
> > 
> > 
> > I am sorry.I can't help with that as I currently don't have HiDive.Found about this news so decided to share here.
> > Btw HiDive DRM is Widevine L3 DRM.So adding L3 CDM Decryption should work.
> 
> The good news is we already did it for crunchy (just haven't released it yet), so it shouldn't be too bad to implement it for hidive if necessary. The hardest part is going to be implenting everything else since just about everything changed in the new API, lol

@Jaynator495 I brought a new HiDive account but can't open it on the GUI.Keep saying wrong password.But it works on my Browser.

**Comment by hazy-kun** [comment]
see here to know why it dowsn't work
 HiDive Extractor broken after site update #9385 [https://github.com/yt-dlp/yt-dlp/issues/9385]

**Comment by Sipherdrakon** [comment]
Glad I found this so thanks for commenting on yt-dlp. Looks like old api is still working and I can grab subs from the site itself so noice. I was worried I wouldn't be able to grab the new dubs coming out but you saved me some headaches. :-)

**Comment by Jaynator495** [comment]
> Glad I found this so thanks for commenting on yt-dlp. Looks like old api is still working and I can grab subs from the site itself so noice. I was worried I wouldn't be able to grab the new dubs coming out but you saved me some headaches. :-)
> 
> Now if only they'd bring back the release schedule so I can see what all new dubs are coming and when they drop. :-P

Glad I could help... the latest commit offers fixed subtitles if you want to compile, but I don't want to create a release until I finish adding the new API as a flag. As for the release calendar, sadly I don't think I captured that from the old API so I can't add that to the app, but, `--new` at least shows what's new :)

**Comment by pratyushpati11** [comment]
> Glad I found this so thanks for commenting on yt-dlp. Looks like old api is still working and I can grab subs from the site itself so noice. I was worried I wouldn't be able to grab the new dubs coming out but you saved me some headaches. :-)
> 
> Now if only they'd bring back the release schedule so I can see what all new dubs are coming and when they drop. :-P

How you able to login with the GUI? Unfortunately I am not able to login after I created a account .

**Comment by AnimeDL** [comment]
Released version 4.5.1 which adds support for Hidive's new API, you can use it with `--hdapi new` (or by adding `hdapi: "new"` to the cli-defaults.yml file).
