### ISSUE TITLE
[Feedback]: (CLI) specify download location

### ISSUE THREAD

**Issue by skwurw** [anidl/multi-downloader-nx#589]
### Type

CLI

### Suggestion

As the title suggests, having the ability to set a download location (like —output z:/output/folder) would be nice to have outside of what might be set in the config file

**Comment by Jaynator495** [comment]
This is already a feature, you can set an absolute path for the `fileName` option and it will output to that location

**Comment by skwurw** [comment]
oh alright then wasn’t 100% about that
