### ISSUE TITLE
no longer works after auto update

### ISSUE THREAD

**Issue by storm134** [anidl/multi-downloader-nx#593]
### Program version

Newest

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

node index.js --service crunchy -s G6Q4CZJ1X --nocleanup -e 9

### Show ID

G6Q4CZJ1X

### Episode

9

### Console Output

```Shell
C:\multi-downloader-nx-master\lib>node index.js --service crunchy -s G6Q4CZJ1X --nocleanup -e 9
Checking for updates...
Found 30 release tags and 1 that are new.
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (C:\multi-downloader-nx-master\lib\node_modules\.pnpm\got@11.8.6\node_modules\got\dist\source\as-promise\index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1710696246923,
    socket: 1710696246923,
    lookup: 1710696246923,
    connect: 1710696246923,
    secureConnect: 1710696246923,
    upload: 1710696246923,
    response: 1710696246953,
    end: 1710696246955,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 0,
      tcp: 0,
      tls: 0,
      request: 0,
      firstByte: 30,
      download: 2,
      total: 32
    }
  }
}

Node.js v20.11.1
```

### Additional Information

have reinstalled from scratch same issue

**Comment by Jaynator495** [comment]
This is because our selection logic for checking for updates breaks ATM because the latest release isn't based on master. Compile the code from the `mpd-support` branch and it should work. Alternatively if you want to stay on the same version, change the `updates.json` to timestamps in the future

**Comment by storm134** [comment]
thans for the quick reponse but not can not dowload says no playlist

node index.js --service crunchy -s GR09CXP10 --dubLang eng --noclearup -e 8

 ✓[08|E:G7PU418G9] ☆ 8 - All for Blessings and Faith [23m40s, SUB, DUB, STREAM]
    - Versions: en, ja
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [09|E:G9DUEM4KG] ☆ 9 - Take Out the Fairy in Love and the Greedy Cardinal [23m40s, SUB, STREAM]
    - Versions: ja
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [10|E:GX9UQW2VJ] ☆ 10 - The Hero and the Guide [23m40s, SUB, STREAM]
    - Versions: ja
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [11|E:G4VUQVDGV] ☆ 11 - The Hero's Challenge [23m40s, SUB, STREAM]
    - Versions: ja
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru

Requesting: [G7PU418G9] Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside Season2 - 8 - All for Blessings and Faith
[WARN] Decryption not enabled!
Selecting raw stream
Full stream found! ( 1: adaptive_dash/eng/- )
Full stream found! ( 2: adaptive_hls/eng/- )
Full stream found! ( 3: download_dash/eng/- )
Full stream found! (✓4: download_hls/eng/- )
Full stream found! ( 5: multitrack_adaptive_hls_v2/eng/- )
Downloading video...
Playlists URL: https://pl.crunchyroll.com/evs3/a6befb760d999506b580622f627ea7be/assets/527841f710d44e2b274a0b955061084d_,5460439.mp4,5460440.mp4,5460437.mp4,5460438.mp4,.urlset/master.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy9hNmJlZmI3NjBkOTk5NTA2YjU4MDYyMmY2MjdlYTdiZS9hc3NldHMvNTI3ODQxZjcxMGQ0NGUyYjI3NGEwYjk1NTA2MTA4NGRfLDU0NjA0MzkubXA0LDU0NjA0NDAubXA0LDU0NjA0MzcubXA0LDU0NjA0MzgubXA0LC51cmxzZXQvbWFzdGVyLm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3MTA4NzQ1ODF9fX1dfQ__&Signature=Gz9VdTsPa70ap4vQBT-jFklyzvZJU9yUN7D-0FA4ucO6gLE9n~p8NQLW4M9x~Rxxu735aIu42DRPLG66C3KFYj~wGO~ZxoUm~BdI8LM~AFfM~EgkawzYAIW6jLr2RjmgkUc7wEkCfyRAbKxvhd52JI7FHtex8o8U919D8evqLZkm9mR7NT7stgte20~goHW-0ZNBN4a-NjswFCajqRPbYyW-t6hc-QVOPkfgXOL42le7Rthv62E~7HPBHH~0fBHCZkLwS6MFCYPcYbmciUtxx3iywK2BWKkBwK9k26bNZR3IZHVG8k30J7mREiLSXPqohPgup0ZDTvK7gN39jk2QHA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA (download_hls/eng/-)
[ERROR] HTTPError 403: Forbidden
[ERROR] CAN'T FETCH VIDEO PLAYLISTS!
Subtitle downloaded: undefined.01.eng.English.signs.ass
[ERROR] Unable to download selected episode 8

C:\multi-downloader-nx-mpd-support\lib>

**Comment by AnimeDL** [comment]
Sadly there is no longer any non-DRM streams, and the ones that still show up actually return a 403 error when requested. You'll have to get a CDM and place it in the widevine directory, and download mp4decrypt. Read the readme.md file on the mpd-support branch
