### ISSUE TITLE
[Feedback]: add crunchyroll cookie login

### ISSUE THREAD

**Issue by garouthe** [anidl/multi-downloader-nx#597]
### Type

CLI

### Suggestion

Please add crunchyroll login via cookie / refresh token / etp_rt

check here for more info 
https://github.com/crunchy-labs/crunchy-cli

**Comment by AnimeDL** [comment]
I'll look into adding this as a flag. Currently you can do this in a bit of a roundabout way, if you use the crunchy api so it generates a session file, replace the refresh token in the file with your refresh token and I believe it will refresh the account to your account

**Comment by AnimeDL** [comment]
Pushed a commit that adds a `--token` flag which takes the refresh token as an argument. This will allow you login using the refresh token

**Comment by garouthe** [comment]
thanks but please release it if possible.
I cant build

**Comment by AnimeDL** [comment]
Made a new release that has this in it
