### ISSUE TITLE
[EXTID]: HiDive 

### ISSUE THREAD

**Issue by Sipherdrakon** [anidl/multi-downloader-nx#598]
### Type

CLI

### Suggestion

So I was wondering if there was a way to use the `--extid` within hidive as well. They are using website templates such as `https://www.hidive.com/video/575793?seasonId=20441`

Since the 575793 id seems to lead directly to the video if it would be possible to get the `extid` set up for that?

**Comment by Jaynator495** [comment]
You can already use -e for this. When e is by itself, it indicates a single episode by id
```
anidl --service hidive -e 575793 
```
You can also use the season id it gives like this:
```
anidl --service hidive -s 20441 -e 1
```

**Comment by Sipherdrakon** [comment]
`aniDL --service hidive -e 575793 --hdapi "new" --dlsubs "en" --dubLang "eng" --fileName "${showTitle} - S${season}E${episode} - ${title} [WEBDL-${height}p]" --force c

=== Multi Downloader NX 4.5.1 ===

[ERROR] Failed to download episode: You do not have access to this

D:\multi-downloader-nx-cli>aniDL --service hidive -e 575793 --dlsubs "en" --dubLang "eng" --fileName "${showTitle} - S${season}E${episode} - ${title} [WEBDL-${height}p]" --force c

=== Multi Downloader NX 4.5.1 ===

[ERROR] -e is not supported in the old API`

This is what i'm getting with old api and new api

**Comment by Jaynator495** [comment]
Are you sure you signed in and have a premium account?

**Comment by Sipherdrakon** [comment]
do i have to call out the new api when using auth? Logged in on old api, and have had premium for what seems like forever. :-P
