### ISSUE TITLE
Toekn Login Error

### ISSUE THREAD

**Issue by garouthe** [anidl/multi-downloader-nx#605]
### Program version

4.5.2

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

AniDL --service crunchy --token {TOKEN}

### Show ID

1

### Episode

1

### Console Output

```Shell
=== Multi Downloader NX 4.5.2 ===

[ERROR] HTTPError 400: Bad Request
[ERROR] Body: {"code":"auth.obtain_access_token.oauth2_error","context":[],"error":"invalid_grant"}
[ERROR] Token Authentication failed!
```

### Additional Information

I am putting etp_rt cookie and it gives error

am i doing something wrong?

**Comment by AnimeDL** [comment]
It currently for some reason seems to only work for refresh tokens from the mobile app, it seems like refresh tokens from the website don't work. I'll look into why and if I can fix it

**Comment by simoneR95** [comment]
A solution is to add in the header 'Cookie': ' etp_rt={token}' and in the body 'grant_type': 'etp_rt_cookie'.
Hope can help you.

**Comment by simoneR95** [comment]
> > A solution is to add in the header 'Cookie': ' etp_rt={token}' and in the body 'grant_type': 'etp_rt_cookie'. Hope can help you.
> 
> Thanks for the reply! That does actually work for authentication, but it looks like then it fails to refresh because that also needs to be changed, which means everyone would need to login again. Yikes. Guess I'll make a poll about this

Thank you for your work

**Comment by AnimeDL** [comment]
The situation here has changed a bit, since this is no longer possible while keeping support for Non-DRM streams. If the situation eventually changes, I'll switch to the web version for --token. Currently it requires a token from a switch which isn't really helpful - but I'm keeping it as is for now. I'm going to close this, but revisit it if the situation ever changes

**Comment by garouthe** [comment]
still it does not work

[ERROR] 400: Bad Request
[ERROR] {"code":"auth.obtain_access_token.oauth2_error","context":[],"error":"invalid_grant"}
[ERROR] Token Authentication failed!
[WARN] Token is likely wrong (Or invalid for given API), please login again!
