### ISSUE TITLE
[BUG]: HiDive Giving Error Code using 4.5.2 GUI

### ISSUE THREAD

**Issue by Sipherdrakon** [anidl/multi-downloader-nx#606]
### Program version

4.5.2

### Operating System

Windows

### Type

GUI

### Service

Hidive

### Command used

Just Hit HiDive Button

### Show ID

None Yet

### Episode

None

### Console Output

```Shell
[ERROR] Code 69 (UpdateApp): Please update your Android app.
```

**Comment by Jaynator495** [comment]
Put `hdapi: "new"` in your cli-defaults, Hidive disabled their old API

**Comment by Sipherdrakon** [comment]
awesome, that worked. Didn't realize they disabled the old api. 😃👍
