### ISSUE TITLE
[BUG]: the command does not work

### ISSUE THREAD

**Issue by kukamarusama** [anidl/multi-downloader-nx#607]
### Program version

v4.5.2

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

anidl.exe --service crunchy -s GR3VWXP96 -e 1

### Show ID

GR3VWXP96

### Episode

1

### Console Output

```Shell
anidl.exe --service crunchy -s GR3VWXP96 -e 1

=== Multi Downloader NX 4.5.2 ===

USER: xxxx (xxxx@gmail.com)
Your Country: MX

[ERROR] HTTPError 503: Service Unavailable
[ERROR] Body: {"code":"content.get_season_v2.cms_service_error","context":[]}
[ERROR] Show Request FAILED!
```

**Comment by Jaynator495** [comment]
This is an Episode ID (Specifically for One Piece episode 1), not a season ID, use `-e` with it, or use the series ID (GRMG8ZQZR) with `--srz` for all of it

**Comment by kukamarusama** [comment]
it only downloads at 480p

**Comment by Jaynator495** [comment]
Yes, one piece episode 1 is only available in 480p, at least if you use that. You can get the "HD" versions of the start of one piece (cropped and upscaled) by using their respective season IDs
Season 1) GY3VWX3MR
Season 2) GY19QP57R
Season 3) GYWEM933Y
If memory serves the rest of one piece is in HD

**Comment by Ereh61** [comment]
bro im trying to download frieren but having same issue somebody help. Season ID and stuff are all correct.

![Uploading Capture.PNG…]()

**Comment by Jaynator495** [comment]
> bro im trying to download frieren but having same issue somebody help. Season ID and stuff are all correct.
> 
> https://i.ibb.co/cxgcyvj/Capture.png

The id you used is actually the series id, use it with `--srz`

**Comment by Ereh61** [comment]
> > bro im trying to download frieren but having same issue somebody help. Season ID and stuff are all correct.
> > https://i.ibb.co/cxgcyvj/Capture.png
> 
> The id you used is actually the series id, use it with `--srz`

can you kindly write the command to download first episode of frieren, im getting error everytime.

**Comment by AnimeDL** [comment]
> > > bro im trying to download frieren but having same issue somebody help. Season ID and stuff are all correct.
> > > https://i.ibb.co/cxgcyvj/Capture.png
> > 
> > 
> > The id you used is actually the series id, use it with `--srz`
> 
> I am getting another error saying,
> 
> [ERROR] HTTPError 403: Forbidden [ERROR] CAN'T FETCH VIDEO PLAYLISTS!

You need to dump your CDM and put it in the widevine folder, and have mp4decrypt added to your system path (or bin-path pointing to the exe)

**Comment by Ereh61** [comment]
> > > > bro im trying to download frieren but having same issue somebody help. Season ID and stuff are all correct.
> > > > https://i.ibb.co/cxgcyvj/Capture.png
> > > 
> > > 
> > > The id you used is actually the series id, use it with `--srz`
> > 
> > 
> > I am getting another error saying,
> > [ERROR] HTTPError 403: Forbidden [ERROR] CAN'T FETCH VIDEO PLAYLISTS!
> 
> You need to dump your CDM and put it in the widevine folder, and have mp4decrypt added to your system path (or bin-path pointing to the exe)

Thanks mate, working fine now!

**Comment by AnimeDL** [comment]
Glad to hear it, going to close this now

**Comment by kukamarusama** [comment]
I don't know how to dump a CDM
