### ISSUE TITLE
[Help]: Is there a way to save episode title in filename?

### ISSUE THREAD

**Issue by tormento** [anidl/multi-downloader-nx#613]
Is there a way to save episode title in filename?

I have looked at the help but can't find the expression to add to save it too.

**Comment by Jaynator495** [comment]
Yes, if you look at the documentation, you'll see all available variables for fileName, ${title} allows for episode title.

**Comment by tormento** [comment]
@AnimeDL I can't find where the setting is saved for the GUI version.
