### ISSUE TITLE
[BUG] x.5 recaps wrong numbering

### ISSUE THREAD

**Issue by tormento** [anidl/multi-downloader-nx#615]
If you try to download Shangri-La Frontier recap, i.e. 14.5, you get

[CR] Shangri-La Frontier - S01E14 [1080p]_2

as filename, that seems like a duplicate of the proper 14 episode.

**Comment by AnimeDL** [comment]
Version 4.6.0 has been released and should fix this issue, feel free to re-open if the issue persists.
