### ISSUE TITLE
[Crunchy] need help

### ISSUE THREAD

**Issue by ShadowDragonX** [anidl/multi-downloader-nx#616]
i put my cdm files into the widevine folder but im still getting the following error:

```python
[...]

aniDL.exe --service crunchy -srz GDKHZEJ0K -e 1

Requested object ID: 1
[ERROR] HTTPError 404: Not Found
[ERROR] Objects Request FAILED!
Body: {
        "__class__": "error",
        "__href__": "",
        "__links__": {},
        "__actions__": {},
        "type": "Not Found",
        "code": "404",
        "message": "Invalid object identifier",
        "context": {}
}
node:internal/process/task_queues:95
    runMicrotasks();
    ^

TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
    at Crunchy.<anonymous> (C:\snapshot\multi-downloader-nx\lib\crunchy.js)
    at Generator.next (<anonymous>)
    at fulfilled (C:\snapshot\multi-downloader-nx\lib\crunchy.js)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.18.2
```  
am i doing smth wrong? 

im using cli version 4.5.2 (prebuilt binaries)

**Comment by Jaynator495** [comment]
--srz, not -srz. Right now it's trying to download an episode id of 1 because of the lack of --srz or -s

**Comment by ShadowDragonX** [comment]
> --srz, not -srz. Right now it's trying to download an episode id of 1 because of the lack of --srz or -s

wow i didnt even notice that XD. Thanks that fixed it. 

btw do you happen to know how i can use the --filename command so my output filename is always like:

{showtitle} {episode} - {title of episode}
