### ISSUE TITLE
[BUG]: Unable to do anything with Hidive

### ISSUE THREAD

**Issue by ChrisCrashX** [anidl/multi-downloader-nx#617]
### Program version

4.5.2

### Operating System

Windows

### Type

CLI

### Service

Hidive

### Command used

anidl.exe --service hidive --auth

### Show ID

27426

### Episode

13

### Console Output

```Shell
[ERROR] Code 69 (UpdateApp): Please update your Android app.

[ERROR] Authentication failed!
```

### Additional Information

I know my hidive account still works because I logged in to watch something earlier.

**Comment by AnimeDL** [comment]
They disabled the old API, the next version will use the new one by default, but you can enable the new api by either using `--hdapi new` or putting in your cli-defaults.yml `hdapi: "new"`

**Comment by ChrisCrashX** [comment]
> They disabled the old API, the next version will use the new one by default, but you can enable the new api by either using `--hdapi new` or putting in your cli-defaults.yml `hdapi: "new"`

> anidl.exe --service hidive -s 27426 -q 0 --dubLang eng --dlSubs en -e 13 --hdapi new

=== Multi Downloader NX 4.5.2 ===

[ERROR] HTTPError 404: Not Found
[ERROR] API Request Failed!
[ERROR] Failed to get Season Data
[ERROR] Failed to list series data: Failed to get season 27426



This is what I'm getting now >~<

**Comment by AnimeDL** [comment]
This doesn't appear to be a valid season or series ID? What were you trying to download?

**Comment by ChrisCrashX** [comment]
> This doesn't appear to be a valid season or series ID? What were you trying to download?

OH... I see, they literally changed how the IDs work, my bad, but now I have this issue???

anidl.exe --service hidive --srz 1801 -q 0 --dubLang eng --dlSubs en -e 13 --hdapi new

=== Multi Downloader NX 4.5.2 ===

[Z.1801] Ragna Crimson (1 Seasons)
  [S.20679] Season 1 (24 Episodes)
    [E.590258] The Day the Reaper Was Born
    [E.590267] The Beginning of the Story
    [E.590262] Agitation
    [E.590279] Action
    [E.590282] Wing
    [E.590277] Reunion
    [E.590280] Act and Guilt
    [E.590278] A Painful Blow
    [E.590259] Negotiation and True Nature
    [E.590276] Stakes and Cooperation
    [E.590266] Tactics and Knowledge
    [E.590268] Determination and Readiness
    [E.590260] Hero of the Battle
    [E.590271] Impatience and Vigilance
    [E.590281] Latent Awakening
    [E.590275] Will of Resistance
    [E.590269] My Comrade
    [E.590272] End of the Battle to the Death
    [E.590270] Reason to Fight
    [E.590263] Just Watch Me
    [E.590256] Words Aren't Needed
    [E.590274] The Winged Monarch
    [E.590264] Lightning God
    [E.590265] Coming 3/30/24 16:00 UTC
[S1E1] The Day the Reaper Was Born
[S1E2] The Beginning of the Story
[S1E3] Agitation
[S1E4] Action
[S1E5] Wing
[S1E6] Reunion
[S1E7] Act and Guilt
[S1E8] A Painful Blow
[S1E9] Negotiation and True Nature
[S1E10] Stakes and Cooperation
[S1E11] Tactics and Knowledge
[S1E12] Determination and Readiness
✓ [S1E13] Hero of the Battle
[S1E14] Impatience and Vigilance
[S1E15] Latent Awakening
[S1E16] Will of Resistance
[S1E17] My Comrade
[S1E18] End of the Battle to the Death
[S1E19] Reason to Fight
[S1E20] Just Watch Me
[S1E21] Words Aren't Needed
[S1E22] The Winged Monarch
[S1E23] Lightning God
[S1E24] Coming 3/30/24 16:00 UTC
[INFO] Ragna Crimson S1 - 13
[INFO] Available dubs and subtitles:
        Audios: Japanese
        Subs  : English
                Spanish
[INFO] Selected dub(s): eng
Servers available:
        dve-streams.akamaized.net
Available Video Qualities:
        [1] 426x240 (166KiB/s)
        [2] 640x360 (359KiB/s)
        [3] 854x480 (842KiB/s)
        [4] 960x540 (1812KiB/s)
        [5] 1280x720 (2776KiB/s)
        [6] 1600x900 (3743KiB/s)
        [7] 1920x1080 (4714KiB/s)
        [8] 1920x1080 (5198KiB/s)
Available Audio Qualities:
        [1] 128kB/s
node:internal/process/task_queues:95
    runMicrotasks();
    ^

TypeError: Cannot read properties of undefined (reading 'resolutionText')
    at Hidive.<anonymous> (C:\snapshot\multi-downloader-nx\lib\hidive.js)
    at Generator.next (<anonymous>)
    at C:\snapshot\multi-downloader-nx\lib\hidive.js
    at new Promise (<anonymous>)
    at C:\snapshot\multi-downloader-nx\lib\hidive.js
    at Hidive.downloadMPD (C:\snapshot\multi-downloader-nx\lib\hidive.js)
    at Hidive.<anonymous> (C:\snapshot\multi-downloader-nx\lib\hidive.js)
    at Generator.next (<anonymous>)
    at fulfilled (C:\snapshot\multi-downloader-nx\lib\hidive.js)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.18.2

**Comment by AnimeDL** [comment]
You ran into a bug, the English audio doesn't actually exist (yet). The episode hasn't been dubbed (yet). Normally, this should fail gracefully with a warning, and that's the bug.

**Comment by ChrisCrashX** [comment]
> You ran into a bug, the English audio doesn't actually exist (yet). The episode hasn't been dubbed (yet). Normally, this should fail gracefully with a warning, and that's the bug.

Gotcha, I forget what day it actually gets dubbed, I usually get most of my anime today but I was behind the last couple weeks (Probably because I had to fetch a cdm which took a lot of research and a while) and episode 12 does download as intended, so I guess I did find a bug on accident lol

**Comment by AnimeDL** [comment]
Next release will have that bug fixed

**Comment by AnimeDL** [comment]
Version 4.6.0 has been released and should fix this issue, feel free to re-open if the issue persists.
