### ISSUE TITLE
Decryption not enabled

### ISSUE THREAD

**Issue by JimSul16** [anidl/multi-downloader-nx#620]
### Type

GUI

### Suggestion

![image](https://github.com/anidl/multi-downloader-nx/assets/163605505/acf3b627-87a2-4982-acd0-2bebc250c78a)
Hello, I would like to ask a question when I try to download using the program it does not leave me with the message "Decryption not enabled" I wanted to know if I am doing something wrong or if you could guide me on how to solve the problem, thank you :3

**Comment by Jaynator495** [comment]
You need to dump a CDM and put it in the widevine directory

**Comment by JimSul16** [comment]
> You need to dump a CDM and put it in the widevine directory, and/or install mp4decrypt

Download the "mp4decrypt" and paste it in the "Widevine" folder, nothing more?

**Comment by AnimeDL** [comment]
mp4decrypt doesn't go in the widevine folder, a CDM does.

**Comment by JimSul16** [comment]
> mp4decrypt doesn't go in the widevine folder, a CDM does.

Great, I tried it and it won't let me have the "mp4decrypt" and it won't let me mount it in CDM, is there a tutorial for that? Thank you very much for the explanations in advance <3

**Comment by AnimeDL** [comment]
Basically you need to dump an l3 CDM and put it in the widevine folder, as for mp4decrypt, either add it to your system path, or put it somewhere and put the direct path to it in bin-path.yml

**Comment by Primelikes01** [comment]
![image](https://github.com/anidl/multi-downloader-nx/assets/158451701/36301139-3332-4fb9-87bc-3c706fedab78)
Now I have to copy and paste this in Notepad, but during saving, which format do I have to use?? And which CMD do I have to put on after moving?

**Comment by Jaynator495** [comment]
> how to get "device_client_id_blob and device_private_key"
> 
> private key is missing; what should I do for it?

Read what was above your message, you need a CDM
