### ISSUE TITLE
private key is missing

### ISSUE THREAD

**Issue by Primelikes01** [anidl/multi-downloader-nx#621]
### Type

GUI

### Suggestion

how to get "device_client_id_blob and device_private_key"

**Comment by rcyclope** [comment]
go to videohelp forum to catch L3 cdm files

**Comment by Primelikes01** [comment]
In those files, i have to remove .bin or .pem by name changing or not 
![image](https://github.com/anidl/multi-downloader-nx/assets/158451701/04d0c4e5-69da-4392-b1a6-5d2c1b580261)

**Comment by rcyclope** [comment]
C/p directely inside folder

**Comment by Primelikes01** [comment]
> C/p directely inside folder with out bin/pem

ok

**Comment by Primelikes01** [comment]
![image](https://github.com/anidl/multi-downloader-nx/assets/158451701/96fada16-6c77-4b2b-8518-627e76198ffd)
Why this problem? i already did everything

**Comment by rcyclope** [comment]
Have catch mp4decrypt
Try with pem/bin file

**Comment by Jaynator495** [comment]
> ![image](https://private-user-images.githubusercontent.com/158451701/318513285-96fada16-6c77-4b2b-8518-627e76198ffd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTI1MzcsIm5iZiI6MTcxMTk5MjIzNywicGF0aCI6Ii8xNTg0NTE3MDEvMzE4NTEzMjg1LTk2ZmFkYTE2LTZjNzctNGIyYi04NTE4LTYyN2U3NjE5OGZmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxNzIzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjQ2ODg1Mjk2MjdhZWRjNjQxYTFlYzhmNmUyOTMzNzVlNzE1OTNlYWE0MzI2OGVmZjg2ZTc5MzM4YTMxNWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EsCWxWfR01lsrc4QirfILJk9iTYQ2vmuA8mIwh001yE) Why this problem? i already did everything

You're missing mp4decrypt

**Comment by Primelikes01** [comment]
no i used mp4decrypt
