### ISSUE TITLE
[BUG]: Chapters API changed ?

### ISSUE THREAD

**Issue by Azzuray** [anidl/multi-downloader-nx#625]
### Program version

4.5.1

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

.\aniDL.exe --service crunchy --series G0XHWM1Q0 -e 1 --partsize 50 --chapters --fileName '${showTitle} S${season}E${episode}'

### Show ID

G0XHWM1Q0

### Episode

1

### Console Output

```Shell
It seems since with news titles starting, the api chapter endpoint as changed ?
```

### Additional Information

![image](https://github.com/anidl/multi-downloader-nx/assets/76765834/b3c2fd24-cadc-4cbc-b4b8-eb2648486219)

**Comment by Jaynator495** [comment]
I just checked, the API has not changed, that series/episode just doesn't have chapters yet. For whatever reason, crunchy decided an access denied is the right error for missing chapter data
