### ISSUE TITLE
[GUI] Where to save filename template

### ISSUE THREAD

**Issue by tormento** [anidl/multi-downloader-nx#643]
I have tried to add

`fileName: [${service}] ${showTitle} - S${season}E${episode} ${title} [${height}p]`

in `cli-defaults.yml` but I get a error when I launch `aniDL.exe`.

Where can I save the template I want?

**Comment by Jaynator495** [comment]
This is the correct place, you just need to put it in quotes, like this:
`fileName: "[${service}] ${showTitle} - S${season}E${episode} ${title} [${height}p]"`

**Comment by rcyclope** [comment]
to transcoding i try this but that not working

`ffmpegOptions: "-vcodec libx265 -crf 18" `
