### ISSUE TITLE
[BUG]: how used ffmpegoptions : with gui

### ISSUE THREAD

**Issue by rcyclope** [anidl/multi-downloader-nx#645]
### Program version

v4.6.3

### Operating System

Windows

### Type

GUI

### Service

All

### Command used

ffmpegoptions :

### Show ID

GYZJ43JMR

### Episode

1, 2, .....

### Console Output

```Shell
'[DEBUG] Got download options: {"id":"GRE50KV36","q":0,"e":"1","dubLang":["jpn"],"dlsubs":["fr"],"fileName":"[${service}] ${showTitle} - S${season}E${episode} [${height}p]","dlVideoOnce":false,"all":false,"but":false,"noaudio":false,"novids":false,"simul":false,"ids":["G69P9MD9Y"],"title":"Asta and Yuno","parent":{"title":"Black Clover","season":"1"},"image":"https://www.crunchyroll.com/imgsrv/display/thumbnail/1200x675/catalog/crunchyroll/8a285ca29aadb33852da5f78d661afc9.jpe","episode":"1"}' 
i tried to transcoding but is not recognized

'ffmpegOptions: "-c:v hevc_amf -preset fast -b:v 3000k -c:a copy -bsf:a aac_adtstoasc" '

some one help me :D
```

**Comment by rcyclope** [comment]
manualy it's working to transcod by cmd bash

`ffmpeg.exe -i "I Was Reincarnated as the 7th Prince so I Can Take My Time Perfecting My Magical Ability - S01E01 - I Reincarnated as the Seventh Prince].mkv"-c:v hevc_nvenc -preset fast -b:v 3000k -c:a copy -bsf:a aac_adtstoasc  test.mkv`

how to integrate this command whith gui ?

**Comment by AnimeDL** [comment]
You are using the option wrong,
use it like this:
```
ffmpegOptions: ["-c:v hevc_amf", "-preset fast", "-b:v 3000k", "-c:a copy", "-bsf:a aac_adtstoasc"]
forceMuxer: "ffmpeg"
```

**Comment by rcyclope** [comment]
It's working

Can you add this option inside gui ?
