### ISSUE TITLE
[BUG]: Cannot read file with ’ char in the name [mp4decrypt]

### ISSUE THREAD

**Issue by tamodolo** [anidl/multi-downloader-nx#646]
### Program version

4.6.3

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

aniDL.exe --service crunchy --crapi web -e GD9UVM9N3 --dlsubs pt-BR --fileName "${showTitle} ${episode}"

### Show ID

GEXH3W2PK

### Episode

GD9UVM9N3

### Console Output

```Shell
Nothing really important.
```

### Additional Information

MP4Decrypt just can't open any file with ’ in the name. Tested removing it in separated command with mp4decrypt and worked normaly.

**Comment by AnimeDL** [comment]
This is unfortunately a problem with mp4decrypt.
Some limitations I've found with mp4decrypt are as follows:
* Cannot have longer than 255 characters in the path (Most likely an 8 bit limitation, somewhere.)
* Cannot have unicode symbols (among other things) in the filenames. (This is a result of using char which can only accept 1 byte characters)

I have looked into making a node native version of mp4decrypt which will allow me to fix these issues, though it's not a small amount of refactoring. You can test it on the native-mp4decrypt branch and give feedback, but it's not quite done yet.

**Comment by tamodolo** [comment]
> This is unfortunately a problem with mp4decrypt. Some limitations I've found with mp4decrypt are as follows:
> 
> * Cannot have longer than 255 characters in the path (Most likely an 8 bit limitation, somewhere.)
> * Cannot have unicode symbols (among other things) in the filenames. (This is a result of using char which can only accept 1 byte characters)
> 
> I have looked into making a node native version of mp4decrypt which will allow me to fix these issues, though it's not a small amount of refactoring. You can test it on the native-mp4decrypt branch and give feedback, but it's not quite done yet.

I'll have to prepare the build ambient first. I'll do that as I find the time and give feedback. For now I'll pull without the show name as a workarround.

**Comment by Neutrinome** [comment]
I had the same problem yesterday.

I think that if the subtitles were downloaded first (if that's possible), it would have been less annoying. Because it's always possible to decrypt manually, after changing the file names.

By the way, you can use https://github.com/shaka-project/shaka-packager/releases instead of mp4decrypt.
When I was researching Widevine, I saw this tool come up quite often. And apparently, it's better than mp4decrypt.

**Comment by AnimeDL** [comment]
Closing this as it should be fixed by 4.7.0 because we use temp files now, feel free to re-open if this is still an issue
