### ISSUE TITLE
[BUG]: 403 forbbiden at login

### ISSUE THREAD

**Issue by tamodolo** [anidl/multi-downloader-nx#652]
### Program version

4.6.3

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

aniDL.exe --service crunchy --crapi web --auth

### Show ID

none

### Episode

none

### Console Output

```Shell
[Q] LOGIN/EMAIL: ***************
[Q] PASSWORD   : *********
[ERROR] HTTPError 403: Forbidden
[ERROR] Just a moment...
[ERROR] Authentication failed!
```

### Additional Information

Not sure why this is happening. Site is working.

**Comment by AnimeDL** [comment]
Pushed a commit that should fix it, if you would be willing to build it, test it, and give feedback, that would be nice, otherwise it will be available in the next release which will be after I test it enough

**Comment by tamodolo** [comment]
> Pushed a commit that should fix it, if you would be willing to build it, test it, and give feedback, that would be nice, otherwise it will be available in the next release which will be after I test it enough

Right. I planned to setup the build environ tonight because the ´ problem too. Let's do it.

I'll be back when some testing is done.

**Comment by AnimeDL** [comment]
> > Pushed a commit that should fix it, if you would be willing to build it, test it, and give feedback, that would be nice, otherwise it will be available in the next release which will be after I test it enough
> 
> Right. I planned to setup the build environ tonight because the ´ problem too. Let's do it.
> 
> I'll be back when some testing is done.

Speaking of that issue, I just implemented a temp file system in the latest commit so that it uses a temp file, and then renames it after decrypting

**Comment by llinke** [comment]
> Pushed a commit that should fix it, if you would be willing to build it, test it, and give feedback, that would be nice, otherwise it will be available in the next release which will be after I test it enough

Build and tested, works like a charm, no more 403s, downloading and decrypting works, too.
Thanks a lot!

**Comment by AnimeDL** [comment]
Seems everyone says it works (which somewhat surprises me) - so I've released version 4.7.0 
![image](https://github.com/anidl/multi-downloader-nx/assets/111080062/5ed3f046-8757-4cf0-be90-fc8118caac37)

**Comment by tamodolo** [comment]
After fighting a fearcing battle against windows PATH system that does not work at all I managed to compile anidl.exe.

Now I can log in again!!

![image](https://github.com/anidl/multi-downloader-nx/assets/9446795/dc229ed4-3231-4187-8126-5656e05b1842)

**Comment by tamodolo** [comment]
Update: My build of 4.7.0rc1 was unauthorized (error 401)

Downloaded 4.7.1 and it's working. This may be a patern to keep an eye. I'll report if 4.7.1 get unauthorized tomorrow.

**Comment by AnimeDL** [comment]
Going to close this since it's working, feel free to re-open if it becomes an issue again
