### ISSUE TITLE
Discrepancies between old and new configuration files

### ISSUE THREAD

**Issue by tormento** [anidl/multi-downloader-nx#654]
I saw that you wrote descriptions and examples in `cli-defaults.yml` but I see some discrepancies with the use of `" "`.

I my old config file I had (and worked):
```
dlsubs: [it]
dubLang: [jpn,ita]
```
but in yours, you add `" "`:
```
dubLang: ["jpn"]
dlsubs: ["it"]
```
So, which is which? Are `" "` mandatory with new release or whatever you put it works?

**Comment by Jaynator495** [comment]
Nothing was changed except the contents of the file. I honestly didn't know it was possible to do it without `"`'s

**Comment by AnimeDL** [comment]
Going to close this since it's been answered
