### ISSUE TITLE
[Feedback]: Create Subfolders per Show

### ISSUE THREAD

**Issue by scopion1745** [anidl/multi-downloader-nx#655]
### Type

Both

### Suggestion

I thought it would be cool to have the downloader create a subfolder (if not already existent) per show and drop all the matching content in there.
Keeps big queues a bit more tidy

**Comment by Jaynator495** [comment]
If you mean the actual downloaded files, this is already possible using fileName

**Comment by scopion1745** [comment]
> If you mean the actual downloaded files, this is already possible using fileName

i think I dont get exactly what you mean.. let me explain my idea differently :)

i mean sorting them like this:

[Downloader Target Dir]
 - [Show 1]
    - Show1-S01E01
    -Show1-S01E02
    - ...
  - [Show2]
    - Show2-S01E01
    - Show2-S01E02
    - ...
    
    Is something like that possible already?
    Is that possible in GUI or only in CLI?

**Comment by Jaynator495** [comment]
You can do this currently.
Set this in your cli-defaults.yml:
```
fileName: "${showTitle}\\${showTitle}-S${season}E${episode}"
numbers: 2
```

**Comment by scopion1745** [comment]
> You can do this currently. Set this in your cli-defaults.yml:
> 
> ```
> fileName: "${showTitle}\\${showTitle}-S${season}E${episode}"
> numbers: 2
> ```

does not seem to work for me.
My cli-defaults.yml currently looks like this:
```
q: 0
nServer: 1
mp4mux: true
noCleanUp: false
dlVideoOnce: false
fileName: "${showTitle}\\${showTitle}-S${season}E${episode}"
numbers: 2
```

**Comment by Jaynator495** [comment]
What does it do/how does it not work?

**Comment by scopion1745** [comment]
it just continues as normal. dropping all files into one folder.

```
Total parts in video stream: 355 (36*10)
Saving stream to «F:\Scrapper\Crunchyroll_Output\[CR] I Shall Survive Using Potions! - S01E09 [1080p].Japanese.video.m4s»...
Download and save init part...
```

it does not create specific subfolders for the show.

**Comment by Jaynator495** [comment]
Are you sure you saved the cli-defaults.yml? (and then restarted the GUI after doing so?)

**Comment by scopion1745** [comment]
> Are you sure you saved the cli-defaults.yml? (and then restarted the GUI after doing so?)

yes i did :) tree times, just to be sure ^^

**Comment by Jaynator495** [comment]
Very weird, and to make sure, when adding an episode to the queue, does the fileName appear to be what you set in the cli-defaults.yml? If not, change it to that and it should work, but it would also mean your editing the wrong cli-defaults.yml?

**Comment by scopion1745** [comment]
> Very weird, and to make sure, **when adding an episode** to the queue, does the fileName appear to be what you set in the cli-defaults.yml? If not, change it to that and it should work, but it would also mean your editing the wrong cli-defaults.yml?

re-adding did the trick :)

**Comment by Jaynator495** [comment]
oh - you were using a saved queue... That would do it.

**Comment by rcyclope** [comment]
fileName: "${seriesTitle}\\S${season}\\${showTitle} - S${season}E${episode} - ${title} - [${height}p]"

that work fine
