### ISSUE TITLE
[BUG]: VTT2ASS error when converting subtitle.

### ISSUE THREAD

**Issue by quamt** [anidl/multi-downloader-nx#658]
### Program version

4.7.1

### Operating System

Windows

### Type

GUI

### Service

Hidive

### Command used

NIL

### Show ID

1045

### Episode

1

### Console Output

```Shell
VTT2ASS subtitle conversion displays the error:

Subtitle Downloaded: https://dve-subtitles.imggaming.com/537894/818597/vtt/subtitle-en-US-246613-1712172962745.vtt
[ERROR] VTT2ASS: Unknown style: text-decoration:underline
[ERROR] VTT2ASS: Unknown style: text-decoration:underline

The error message seems to refer to this line in the VTT
::cue(.Q2){font-family:"Swis721 BT" ,Arial; font-size:.84em; color:#FFFFFF; text-decoration:underline;}
```

**Comment by AnimeDL** [comment]
Fixed in the latest commit of the v5 branch, it will make it's way into the next version

**Comment by quamt** [comment]
Thank you for the update. 
I will close this once it's the new version is out so it won't reemerge.
