### ISSUE TITLE
[BUG]: -s to specify season doesn't work

### ISSUE THREAD

**Issue by werewolf004** [anidl/multi-downloader-nx#659]
### Program version

4.7.1

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

.\aniDL.exe --service crunchy --series %series% -s %saison% -e %episode% --partsize 50 --dlsubs "fr" --chapters --defaultAudio "jpn" --defaultSub "fra" --fileName '${showTitle} Season ${season} Episode ${episode}'

### Show ID

G3KHEVDPE

### Episode

2

### Console Output

```Shell
[Z:GP5HJ84QX] A Condition Called Love (Seasons: 1, EPs: 2) [SIMULCAST, SUB]
  - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [S:G6P8CXPXZ] A Condition Called Love (Season: 1) [SIMULCAST, SUB]
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru

------------------------------
```

### Additional Information

If I add -s to specify the season number (1 2 3), download soesnt work and stop at the start after detecting subtitles. Can be reproduced on all show and all episode.

**Comment by Jaynator495** [comment]
It doesn't use a season number, it uses a season ID

**Comment by RazerBlade07** [comment]
How can I download a specific season in the GUI?

**Comment by AnimeDL** [comment]
> How can I download a specific season in the GUI?

Top of the selection page, you can select a season and then select all the episodes from that season

**Comment by RazerBlade07** [comment]
> > How can I download a specific season in the GUI?
> 
> Top of the selection page, you can select a season and then select all the episodes from that season

Which selection page? If I click on episode list and select only season 1, all seasons still appear in the queue

**Comment by AnimeDL** [comment]
> Which selection page? If I click on episode list and select only season 1, all seasons still appear in the queue

![image](https://github.com/anidl/multi-downloader-nx/assets/111080062/fc3d043d-b2c6-4e1f-ae3d-30bd3f133299)
![image](https://github.com/anidl/multi-downloader-nx/assets/111080062/91d614e3-3d1d-4aca-8d09-f94d5faed09e)
Then apparently there is a bug where if you hit the select all button, it selects all episodes, we'll try to fix that in the next release, in the meantime just select what episodes you want manually from that list

**Comment by werewolf004** [comment]
thanks for your help, i don't use -s anymore
