### ISSUE TITLE
Can't figure out how it works

### ISSUE THREAD

**Issue by Camokyu** [anidl/multi-downloader-nx#671]
### Program version

Latest

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

cmd

### Show ID

???

### Episode

???

### Console Output

```Shell
???????????
```

### Additional Information

Hello, I am very sorry to bother but I'll be honest : I cannot figure out how this downloader works. I unzipped the dl'ed version from the main branche, and didn't find anything I could run. No .exe or anything. No sign of this "GUI version" I read the name of in other topics on this repo. Now I'm not completely new to "tech stuff" but here I'am at a complete loss. Did I miss something despite checking things carefully ? I couldn't find install instructions anywhere, and have absolutely no idea how to use this dl'er. Would anyone who has the time and patience be kind and explain this to me step by step ? I searched everything I could to try and get the hang of it by myself, but I must admit I lost this battle ><""

Note : I'm still learning how to use Github and this is the first ever issue I open. My most sincere apologies for any mistakes !

**Comment by AnimeDL** [comment]
Hi, you can download the precompiled binaries under the "releases" tab, here's a direct URL to it: https://github.com/anidl/multi-downloader-nx/releases


Here is also a direct link to v5 of the downloader, windows GUI version: https://github.com/anidl/multi-downloader-nx/releases/download/v5.0.0/multi-downloader-nx-windows-gui.7z

**Comment by abaurens** [comment]
As a general case. You shouldn't download/clone projects directly from a branch except if your goal is to build the project yourself (if that's your objective, ther's instructions on the home page to tell you how to do so).

Most of the time (and it's the case here) you can find a `release` page to the right of the repo preview that will contain pre-built binaries for usually all suported platforms. Our dear maintainer gave you a direct link to it as well.
![image](https://github.com/anidl/multi-downloader-nx/assets/6839425/dcabd3fd-4e39-47ce-8f0c-5cb69ae07970)

Here you can find downloads for the latest gui version of the downloader (which maintainer also gave you).

**Comment by AnimeDL** [comment]
Since you never got back to us, I'm going to close this issue. Feel free to join our discord for further support though
