### ISSUE TITLE
[HiDive]: Can't download movies 

### ISSUE THREAD

**Issue by Sipherdrakon** [anidl/multi-downloader-nx#672]
### Program version

5.0

### Operating System

Windows

### Type

CLI

### Service

Hidive

### Command used

aniDL --service hidive -e 608187 --dubLang "jpn" --fileName "${showTitle} - S${season}E${episode} - ${title} [WEBDL-${height}p]" --force c

### Show ID

NA

### Episode

NA

### Console Output

```Shell
=== Multi Downloader NX 5.0.0 ===

node:internal/process/task_queues:95
    runMicrotasks();
    ^

TypeError: Cannot set properties of undefined (setting 'episodeNumber')
    at Hidive.<anonymous> (C:\snapshot\multi-downloader-nx\lib\hidive.js)
    at Generator.next (<anonymous>)
    at fulfilled (C:\snapshot\multi-downloader-nx\lib\hidive.js)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.18.2
```

### Additional Information

So I tried to grab the new [Ya Boy Kongming!: Road to Summer Sonia](https://www.hidive.com/video/608187?playlistId=22556) and got the above output.

**Comment by Sipherdrakon** [comment]
Also tried in GUI and it can see the movie

[VOD_PLAYLIST #22556] Ya Boy Kongming - Road to Summer Sonia
[E.608187] Ya Boy Kongming - Road to Summer Sonia

but I can't figure out how to grab it.

**Comment by AnimeDL** [comment]
Fixes in the latest commit, it will be in the next release

**Comment by Sipherdrakon** [comment]
Noice, thanks. You guys are always super quick on this stuff. :-)
