### ISSUE TITLE
[BUG]: Can't Download HiDive Movies

### ISSUE THREAD

**Issue by shadeau9** [anidl/multi-downloader-nx#677]
### Program version

5.0.0

### Operating System

Windows

### Type

CLI

### Service

Hidive

### Command used

aniDL.exe --service 'hidive' --username 'XXXXXX' --password 'XXXXXX' --partsize 40 -e 576095

### Show ID

1317

### Episode

1

### Console Output

```Shell
aniDL.exe --service 'hidive' --username 'XXXXXX' --password 'XXXXXX' --search "penguindrum"

=== Multi Downloader NX 4.7.1 ===

Search Results:
[E.576096] RE:cycle of the PENGUINDRUM MOVIE - Part 2 I Love You
[E.576095] RE:cycle of the PENGUINDRUM MOVIE - Part 1 Your Train Is the Survival Tactic
[VOD_PLAYLIST #20452] RE:cycle of the PENGUINDRUM MOVIE - Part 1 Your Train Is the Survival Tactic
[VOD_PLAYLIST #20451] RE:cycle of the PENGUINDRUM MOVIE - Part 2 I Love You
[Z.1317] RE:cycle of the PENGUINDRUM MOVIE - Part 1 Your Train Is the Survival Tactic

aniDL.exe --service 'hidive' --username 'XXXXXX' --password 'XXXXXX' --partsize 40 -e 576095

=== Multi Downloader NX 5.0.0 ===

node:internal/process/task_queues:95
    runMicrotasks();
    ^

TypeError: Cannot set properties of undefined (setting 'episodeNumber')
    at Hidive.<anonymous> (C:\snapshot\multi-downloader-nx\lib\hidive.js)
    at Generator.next (<anonymous>)
    at fulfilled (C:\snapshot\multi-downloader-nx\lib\hidive.js)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.18.2
```

### Additional Information

The GUI and CLI both fail to process HiDive content without actual episode numbers. The search function works and reveals the content (movies) however the downloader fails to download when the listed episode is specified. The error implies that there's an issue when the "episode" doesn't have an episode number associated with it.

**Comment by AnimeDL** [comment]
See #672, this is already fixed in the latest commit, a new build just hasn't been made yet. You can build yourself in the meantime if you want, I've just been occupied with another project the last week or so

**Comment by shadeau9** [comment]
Awesome! Thank you! I only looked through open issues so I missed that one.

**Comment by shadeau9** [comment]
Built the new version and it fixes this issue. Thanks again! This software is amazing!
