### ISSUE TITLE
Using ffmpeg commands in gui

### ISSUE THREAD

**Issue by StrPlayer** [anidl/multi-downloader-nx#687]
how would i go about using ffmpeg commands to make files smaller after downloading an episode in the gui version

**Comment by Jaynator495** [comment]
You could put something like this in your cli-defaults.yml:
```
ffmpegOptions: ["-c:v hevc_nvenc", "-rc vbr_hq", "-preset slow", "-vbr 22"]
forceMuxer: "ffmpeg"
```

**Comment by StrPlayer** [comment]
Thank you and whats the option called to make it a mp4 instead of a mkv

**Comment by Jaynator495** [comment]
It's `mp4: true`

**Comment by StrPlayer** [comment]
thanks
