### ISSUE TITLE
[BUG]: (Not really a bug) I'm not sure where i'm supossed to put my token.

### ISSUE THREAD

**Issue by RexGhidorah** [anidl/multi-downloader-nx#695]
### Program version

5.0.0

### Operating System

Windows

### Type

GUI

### Service

AnimeOnegai

### Command used

Login

### Show ID

1234

### Episode

1

### Console Output

```Shell
[WARN] Private key missing

=== Multi Downloader NX GUI 5.0.0 ===

GUI server started on port 3000
[WS] Connection to public ws from '::1'
[WS] Connection from '::1'
[ERROR] Authentication not possible, manual authentication required due to recaptcha. In order to login use the --token flag. You can get the token by logging into the website, and opening the dev console and running the command "localStorage.ott_token"
[ERROR] Authentication not possible, manual authentication required due to recaptcha. In order to login use the --token flag. You can get the token by logging into the website, and opening the dev console and running the command "localStorage.ott_token"
[ERROR] Authentication not possible, manual authentication required due to recaptcha. In order to login use the --token flag. You can get the token by logging into the website, and opening the dev console and running the command "localStorage.ott_token"
```

### Additional Information

Hi!
I got the token but i'm not sure where i have tu put it.
I tried opening the "cmdhere.bat" and the command "--tokenflag [token]" but it didn't recognice it.
Help :,^

**Comment by RexGhidorah** [comment]
Hi!
I managed to log in with the CLI version but now i got this error:
`Requesting: [E.7201] ME ENCANTAN LAS MAGICAL GIRLS - 13 - Ep. 13
[WARN] Decryption not enabled!
[ERROR] You don't have access to download this content
Skip muxing since no vids are downloaded`
But I should have acces, i got Tier 2 subscription... I'm kinda sure i'm doing something wrong but i'm not sure what...

**Comment by Jaynator495** [comment]
You need to place a CDM in the widevine directory
