### ISSUE TITLE
[Feedback]: No video, just audio.

### ISSUE THREAD

**Issue by RexGhidorah** [anidl/multi-downloader-nx#698]
### Type

GUI

### Suggestion

Hi!
I'm not sure if there's actually an option for this but, is there a way to make it just download the audio and not video on multiple languages downloads?
For example, if you select original japanese and another one, program downloads: japanese video > japanese audio > selected subs > dub video > dub audio > selected subs.

And would be awesome if it just went: japanese video > japanese audio > selected subs > dub audio > selected subs.

The thing with downloading every video makes the download of the final file take forever :,D

**Comment by Jaynator495** [comment]
That depends on the service, for crunchy, hidive, and AO? Yes. For ADN? Not really. 
Use the `--dlvideoOnce` flag

**Comment by RexGhidorah** [comment]
> That depends on the service, for crunchy, hidive, and AO? Yes. For ADN? Not really. Use the `--dlvideoOnce` flag

Sorry!
I didn't put the service, totally my bad.
I was talking for Crunchy.
Is there a way to do that with the GUI version or is a thing only for CLI?

**Comment by Jaynator495** [comment]
Yes, you can add this to your cli-defaults.yml file:
```
dlVideoOnce: true
```

**Comment by RexGhidorah** [comment]
> Yes, you can add this to your cli-defaults.yml file:
> 
> ```
> dlVideoOnce: true
> ```

Thanx! :D 🙇
