### ISSUE TITLE
[BUG]:   Issues with Server Switching and Data Decryption

### ISSUE THREAD

**Issue by quamt** [anidl/multi-downloader-nx#714]
### Program version

5.0.3

### Operating System

Windows

### Type

GUI

### Service

Crunchyroll

### Command used

NIL

### Show ID

ALL

### Episode

ALL

### Console Output

```Shell
Full stream found! (✓1: adaptive_switch_dash/jpn/- )
Full stream found! ( 2: drm_adaptive_dash/jpn/- )
Full stream found! ( 3: drm_download_dash/jpn/- )
Downloading video...
Playlists URL: xxxxx
23503373be8b (adaptive_switch_dash/jpn/-)
Servers available:
	prod.gccrunchyroll.com
Available Video Qualities:
	[1] 428x240 (486KiB/s)
	[2] 640x360 (975KiB/s)
	[3] 848x480 (1944KiB/s)
	[4] 1280x720 (3903KiB/s)
	[5] 1920x1080 (7806KiB/s)
Available Audio Qualities:
	[1] 64kB/s
	[2] 96kB/s
	[3] 128kB/s
Selected quality: 
	Video: 1920x1080 (7806KiB/s)
	Audio: 128kB/s
	Server: prod.gccrunchyroll.com
xxxxxx
xxxxxx
xxxxxx

Decryption Needed, attempting to decrypt
Started decrypting video

> "mp4decrypt" --show-progress xxxxxxxxx
```

### Additional Information

I noticed a couple of issues during the download process that I wanted to bring to your attention:

Server Switching: 
It seems that the server is switching between Crunchy and Aka during downloads. 
My current settings are as follows:
```
# Set which stream to use
kstream: 1
# Set which server to use
server: 1
```

Data Decryption: 
Despite the server showing that it's non-encrypted, the data still appears to require decryption.

Additionally, the download gets stuck at some point after displaying:

```
Download and save init part...
Init part downloaded.
```

Could you please look into these issues and let me know if I should make any adjustments?

**Comment by Jaynator495** [comment]
The non DRM stream now has DRM, unfortunately

**Comment by quamt** [comment]
> The non DRM stream now has DRM, unfortunately

Understand.
Is that also why the server for each download changes? From Crunchy to Aka and vice versa.

**Comment by Jaynator495** [comment]
Yes and no, that's a side effect of the new play API, which chooses the best server based on load and geography (or at least, it's supposed to)

**Comment by quamt** [comment]
Oh. I see.
I guess that why there is now this error messages?
And would need to change the server.

```
Decryption Needed, attempting to decrypt
[ERROR] RequestError: ETIMEDOUT
[ERROR] Failed to get encryption keys
[ERROR] Download error: Unable to download episode


[ERROR] TypeError: fetch failed
[WARN] Chapter request failed, attempting old API
Old Chapter request successful
[ERROR] TypeError: fetch failed
[ERROR] Non-DRM Request Stream URLs FAILED!
```

**Comment by quamt** [comment]
Hm, I changed servers, and now an error message pops up:

```
# Set which stream to use
kstream: 2
# Set which server to use
server: 1
```
Same for this
```
# Set which stream to use
kstream: 2
# Set which server to use
server: 2
```


```
[ERROR] 403: Forbidden
[ERROR] <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
[ERROR] CAN'T FETCH VIDEO PLAYLISTS!
```

**Comment by Jaynator495** [comment]
Yea, kstream 2 and 3 no longer work, not sure if they will come back, but probably not. As for the rest of the errors, it looks like trouble communicating with Crunchyroll's servers

**Comment by quamt** [comment]
Ok. Understand. That's probably why there was an App update on Android.

**Comment by quamt** [comment]
I'm closing this as everything has been addressed.

**Comment by quamt** [comment]
Thank you very much.
