### ISSUE TITLE
[BUG]: [ERROR] Unable to download selected episode 1 [WARN] No full streams found!

### ISSUE THREAD

**Issue by kokoboko5** [anidl/multi-downloader-nx#734]
### Program version

5.1.4

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

aniDL --service "crunchy" -s G6WEC315N -e 1 --novids --noaudio --chapters false --dlsubs ar

### Show ID

G6WEC315N

### Episode

1

### Console Output

```Shell
=== Multi Downloader NX 5.1.4 ===

USER: ********
Your Country: ********

[S:G6WEC315N] No Longer Allowed in Another World (Season: 1) [SIMULCAST, SUB]
  - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
 ✓[01|E:GG1U2J9Q1] ☆ 1 - I Must Commit Double-Suicide! [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru

Requesting: [GG1U2J9Q1] No Longer Allowed in Another World - 1 - I Must Commit Double-Suicide!
[WARN] No full streams found!
[ERROR] Unable to download selected episode 1
```

**Comment by Jaynator495** [comment]
Do you have mp4decrypt and a CDM?

**Comment by kokoboko5** [comment]
> Do you have mp4decrypt and a CDM?

Yes I have
![image](https://github.com/anidl/multi-downloader-nx/assets/63605521/65904dba-e323-40ef-9887-d1e98b23fae3)

![image](https://github.com/anidl/multi-downloader-nx/assets/63605521/eb8200c6-2d5b-4ef5-86a7-a6314689e0da)

I found out what caused this problem

It was in the bin-path.yml file

By default it was like this

ffmpeg: "ffmpeg.exe"
mkvmerge: "mkvmerge.exe"
ffprobe: "ffprobe.exe"
mp4decrypt: "mp4decrypt.exe"

After I modified it

ffmpeg: ".\\bin\\ffmpeg.exe"
mkvmerge: ".\\bin\\mkvmerge.exe"
ffprobe: ".\\bin\\ffprobe.exe"
mp4decrypt: ".\\bin\\mp4decrypt.exe"

The script is now working

**Comment by RexGhidorah** [comment]
> The script is now working

I tried your solution and now it's more broken *cries*
![image](https://github.com/user-attachments/assets/5ad586eb-fd2f-4a5d-8e2c-4b605e182876)
