### ISSUE TITLE
[BUG]: Can't download from CR - No full streams found!

### ISSUE THREAD

**Issue by Thonolanj** [anidl/multi-downloader-nx#740]
### Program version

5.1.4

### Operating System

Linux

### Type

CLI

### Service

Crunchyroll

### Command used

./aniDL --service 'crunchy' --numbers 2 --fileName '${showTitle}/${showTitle} - S${season}E${episode} - ${title}' -q 4 --dlsubs all --dubLang eng -s GY2PCVE8V -e 2

### Show ID

GY2PCVE8V 

### Episode

2

### Console Output

```Shell
./aniDL --service 'crunchy' --numbers 2 --fileName '${showTitle}/${showTitle} - S${season}E${episode} - ${title}' -q 4 --dlsubs all --dubLang eng -s GY2PCVE8V -e 2

=== Multi Downloader NX 5.1.4 ===

USER: <redacted>
Your Country: US

[S:GY2PCVE8V] A Journey Through Another World: Raising Kids While Adventuring (Season: 1) [SIMULCAST, SUB, DUB]
  - Versions: en, es-419, pt-BR, de, ja
  - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [01|E:GD9UVMK7Q] ☆ 1 - Another World and Twins [23m50s, SUB, DUB, STREAM]
    - Versions: en, es-419, pt-BR, de, ja
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
 ✓[02|E:GQJUG5JW3] ☆ 2 - Nice to Meet You, Joule [23m50s, SUB, DUB, STREAM]
    - Versions: en, es-419, pt-BR, de, ja
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru

Requesting: [GQJUG5JW3] A Journey Through Another World: Raising Kids While Adventuring - 2 - Nice to Meet You, Joule
Chapter request successful
[WARN] No full streams found!
[ERROR] Unable to download selected episode 2
```

### Additional Information

Happens on any episode I try.

**Comment by Jaynator495** [comment]
Do you have a CDM and mp4decrypt?

**Comment by Thonolanj** [comment]
Yes I have both.

**Comment by Thonolanj** [comment]
Hidive encrypted download working.

**Comment by Thonolanj** [comment]
ok. sorry, my mp4decrypt was symlinked so I thought I had it. 
However the original file was borked, had to redownload it. 
I wish the error was more descriptive of missing any of the required files.

**Comment by Jaynator495** [comment]
> ok. sorry, my mp4decrypt was symlinked so I thought I had it. However the original file was borked, had to redownload it. I wish the error was more descriptive of missing any of the required files.

Yea, a lot of people seem to be having similar issues, the next version will be more clear about what the actual issue is

**Comment by RexGhidorah** [comment]
> Yea, a lot of people seem to be having similar issues, the next version will be more clear about what the actual issue is

Hi!
I'm having the same issue, can I get some help pls?
![image](https://github.com/user-attachments/assets/70182b68-992f-4a10-9926-e4f6a9bd3446)
![image](https://github.com/user-attachments/assets/90ad43c6-dfe4-47e1-adac-e354fd6572e9)
