### ISSUE TITLE
[BUG]: Certain titles not found but can be watched in normal browser's

### ISSUE THREAD

**Issue by quamt** [anidl/multi-downloader-nx#741]
### Program version

5.1.4

### Operating System

Windows

### Type

GUI

### Service

Crunchyroll

### Command used

NIL

### Show ID

G1QFP9G5E

### Episode

ALL

### Console Output

```Shell
Nothing Found.


Series is empty!
```

### Additional Information

Certain content/titles can be watched in normal browser's but doesn't show inside anidl search.

Searching for the title produces `Nothing Found.`
Using the Show ID, try to list episodes: `Series is empty!`
Examples: 
`G6Q4WD3ER - death bell bloody camp; 
G68VDQ776 - death kappa; 
G5JFDQE94 - chanbara beauty the movie vortex`

**Comment by quamt** [comment]
Has there been a change? 
It seems to find the shows now.

**Comment by Jaynator495** [comment]
Nope, if I had to guess, it was an issue on crunchy's end with a mismatch of season IDs, it wouldn't be the first time

**Comment by quamt** [comment]
Understand. 
I will close the ticket in that case.
