### ISSUE TITLE
[BUG]: no puedo  descargar esta todo bien y no puedo descargar nada

### ISSUE THREAD

**Issue by Josemaster2** [anidl/multi-downloader-nx#745]
### Program version

la ultima

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

no

### Show ID

GJ0H7QGJE

### Episode

1

### Console Output

```Shell
[WARN] Couldn't find versions on some episodes, fell back to old method.

------------------------------

[S1E2] - Rinne [✓ Japanese]
Requesting: [GMKUX1KG2] Why Does Nobody Remember Me in This World? - 2 - Rinne
Chapter request successful
[WARN] No full streams found!
[ERROR] Download error: Unable to download episode 2 from GJ0H7QGJE
```

### Additional Information

[WARN] Couldn't find versions on some episodes, fell back to old method.

------------------------------

[S1E2] - Rinne [✓ Japanese]
Requesting: [GMKUX1KG2] Why Does Nobody Remember Me in This World? - 2 - Rinne
Chapter request successful
[WARN] No full streams found!
[ERROR] Download error: Unable to download episode 2 from GJ0H7QGJE

**Comment by Jaynator495** [comment]
mp4decrypt isn't being detected, check to make sure your bin-path.yml is correct, or that you have added mp4decrypt to your system path

**Comment by Josemaster2** [comment]
explicame como se intala bien el programa por si hice algo mal,,,,,,todos los archivos nesesarios esta con la carpeta que descarge aqui,,,,,,del programa el que esta descargado y estado buscado el ploblema durate 5 horas y no se que le porque no  funciona,,,,,


una pregunta estas cosas se ponen  en el sistema de window y se pone hay o se intala pregunto que hay que hacer para que funcione bien
