### ISSUE TITLE
error al descargar video

### ISSUE THREAD

**Issue by Josemaster2** [anidl/multi-downloader-nx#746]
### Program version

la ultima

### Operating System

Windows

### Type

GUI

### Service

Crunchyroll

### Command used

no

### Show ID

GR8DN7N7R

### Episode

1

### Console Output

```Shell
[ERROR] 404: Not Found
[ERROR] {"code":"content.error.route_not_found","context":[]}
[ERROR] Request Stream URLs FAILED! Attempting fallback
[ERROR] 404: Not Found
[ERROR] {"code":"content.error.route_not_found","context":[]}
[ERROR] Fallback Request Stream URLs FAILED!
[ERROR] Download error: Unable to download episode 11 from GR8DN7N7R
```

### Additional Information

[ERROR] 404: Not Found
[ERROR] {"code":"content.error.route_not_found","context":[]}
[ERROR] Request Stream URLs FAILED! Attempting fallback
[ERROR] 404: Not Found
[ERROR] {"code":"content.error.route_not_found","context":[]}
[ERROR] Fallback Request Stream URLs FAILED!
[ERROR] Download error: Unable to download episode 11 from GR8DN7N7R

**Comment by Josemaster2** [comment]
![IMG_20240723_124735](https://github.com/user-attachments/assets/72cd3582-2392-49cc-b7b8-cdd552ece823)

**Comment by Josemaster2** [comment]
now it works for me

**Comment by AnimeDL** [comment]
Going to close this since this was a crunchyroll error
