### ISSUE TITLE
[BUG]: I can't download anything

### ISSUE THREAD

**Issue by RexGhidorah** [anidl/multi-downloader-nx#762]
### Program version

5.1.5

### Operating System

Windows

### Type

GUI

### Service

Crunchyroll

### Command used

"id":"GG5H5XQ7D","q":0,"e":"1","dubLang":["jpn","spa-419"],"dlsubs":["es-419"],"fileName":"[${service}] ${showTitle} - S${season}E${episode} [${height}p]","dlVideoOnce":true,"all":false,"but":false,"noaudio":false,"novids":false,"simul":false

### Show ID

GG5H5XQ7D

### Episode

1

### Console Output

```Shell
[S1E1] - The Man Who Became a Kaiju [✓ Spanish, ✓ Japanese]
Requesting: [GZ7UVG338] Kaiju No. 8 - 1 - The Man Who Became a Kaiju
Chapter request successful
[WARN] No full streams found!
[ERROR] Download error: Unable to download episode 1 from GG5H5XQ7D
```

### Additional Information

Hi!
Program was just working fine but now doen't want to download anything.
I have even tried changing the cdm and all but keeps showing the same error, on Crunchy and on AO is: "Requesting: [E.7602] ME ENCANTAN LAS MAGICAL GIRLS - 13 - Ep. 13
[ERROR] 500: Internal Server Error
[ERROR] {"message":"Internal Server Error"}

[ERROR] Request Stream URLs FAILED!
[ERROR] Download error: Unable to download episode 13 from 208"

**Comment by RexGhidorah** [comment]
![image](https://github.com/user-attachments/assets/6500f2b4-033b-4528-9196-0ba25a1be636)
This is my config path, all recently updated due to that error.

**Comment by RexGhidorah** [comment]
Pls someone help :,D

**Comment by RexGhidorah** [comment]
![image](https://github.com/user-attachments/assets/231cfbb3-8c04-41fd-bf37-5c20508eb182)
My CDM has the RSA thing so it shouldn't be that.

**Comment by Jaynator495** [comment]
Move all those executables one directory up, they don't go in the config directory

**Comment by Jaynator495** [comment]
Also for a comment you made on another post, on windows you need double backslash, since it tries to use it as an escape character

**Comment by RexGhidorah** [comment]
> Move all those executables one directory up, they don't go in the config directory

It worked, now I feel so dumb HAHAHAHA 😭
Sorry to bother, it won't be a failure at all if my rookie problem helps another one. Thanx for the help, i really appreciate it.
![image](https://github.com/user-attachments/assets/f5553da2-6af8-4919-b46d-f291e0f62208)

**Comment by RexGhidorah** [comment]
> Also for a comment you made on another post, on windows you need double backslash, since it tries to use it as an escape character

I come again, now AO doen't work haha :,v
![image](https://github.com/user-attachments/assets/390dfea7-9df1-4a61-8e9a-c374d71680ac)

**Comment by Jaynator495** [comment]
> > Also for a comment you made on another post, on windows you need double backslash, since it tries to use it as an escape character
> 
> I come again, now AO doen't work haha :,v ![image](https://private-user-images.githubusercontent.com/168611490/360573501-390dfea7-9df1-4a61-8e9a-c374d71680ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNTI5NDgsIm5iZiI6MTcyNDM1MjY0OCwicGF0aCI6Ii8xNjg2MTE0OTAvMzYwNTczNTAxLTM5MGRmZWE3LTlkZjEtNGE2MS04ZTlhLWMzNzRkNzE2ODBhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxODUwNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTI3ODcwMjg3M2IzY2JjZTlmY2M3OWU0YWRlMDVlZDdhNmVmZGM4NGQ0NTdkYTA2Y2EyMWQ5NTU4NjU2YTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QOqsURo4YkfcqFar7xyOAQbdADnQJcCbvYbNgrXv2no)

Did you login?

**Comment by RexGhidorah** [comment]
Yes, and I have an active subscription.

**Comment by RexGhidorah** [comment]
> Did you login?

I maybe not?
the ao_token file looks like this. I used:
`aniDL --service ao --token flag [token]`

![image](https://github.com/user-attachments/assets/44f6440b-4cae-4525-af2a-4eb80448e4e1)

**Comment by Jaynator495** [comment]
Ah, don't put "flag" there, just your token
