### ISSUE TITLE
[BUG]: AniDL not recognizing "--token" command

### ISSUE THREAD

**Issue by Username9980** [anidl/multi-downloader-nx#787]
### Program version

5.1.5

### Operating System

Windows

### Type

CLI

### Service

AnimeOnegai

### Command used

--token

### Show ID

0

### Episode

0

### Console Output

```Shell
[ERROR] Authentication not possible, manual authentication required due to recaptcha. In order to login use the --token flag. You can get the token by logging into the website, and opening the dev console and running the command "localStorage.ott_token"
```

### Additional Information

Whenever I try to run a command with the "--token" command and my token from the `localStorage.ott_token` command, it gives me this error above. What am I doing wrong?

**Comment by Jaynator495** [comment]
Are you using it in conjunction with --auth? If you are, don't

**Comment by Username9980** [comment]
> Are you using it in conjunction with --auth? If you are, don't

Tried without "--auth", AniDL didn't do anything except it said "Token saved"  and that's it.

**Comment by Jaynator495** [comment]
> > Are you using it in conjunction with --auth? If you are, don't
> 
> Tried without "--auth", AniDL didn't do anything except it said "Token saved"  and that's it.

That's all it needed to do, you can now download from AO
